import type {
  CampaignForecastMetricKey,
  LandBuiltEnvironmentMetricKey,
  LayerKey,
  SocioeconomicMetricKey,
  TerritorialMetricKey,
} from "@/types/api";

export type DashboardSearchItem = {
  id: string;
  label: string;
  description?: string;
  category: "layer" | "variable" | "module" | "tool";
  targetLayer?: LayerKey;
  targetSubLayer?: string;
  targetLandMetric?: LandBuiltEnvironmentMetricKey;
  targetTerritorialMetric?: TerritorialMetricKey;
  targetSocioeconomicMetric?: SocioeconomicMetricKey;
  targetCampaignMetric?: CampaignForecastMetricKey;
  focusElementId?: string;
  aliases?: string[];
};

export const dashboardSearchIndex: DashboardSearchItem[] = [
  {
    id: "population",
    label: "Población",
    description: "Datos territoriales",
    category: "layer",
    targetLayer: "population",
    targetSubLayer: "population",
    aliases: ["population total", "inhabitants", "población total", "habitantes"],
  },
  {
    id: "population-density",
    label: "Densidad de población",
    description: "Territorio / entorno construido",
    category: "variable",
    targetLayer: "landBuiltEnvironment",
    targetSubLayer: "populationDensity",
    targetLandMetric: "populationDensity",
    aliases: ["density", "densidad"],
  },
  {
    id: "average-age",
    label: "Edad media",
    description: "Estructura de edad",
    category: "variable",
    targetLayer: "ageStructure",
    targetSubLayer: "ageStructure",
    aliases: ["mean age", "average age", "edad media"],
  },
  {
    id: "age-structure",
    label: "Estructura de edad",
    description: "Datos territoriales",
    category: "layer",
    targetLayer: "ageStructure",
    targetSubLayer: "ageStructure",
    aliases: ["age cohorts", "population pyramid", "cohortes de edad", "pirámide de población"],
  },
  {
    id: "electoral-behavior",
    label: "Comportamiento electoral",
    description: "Resultados electorales",
    category: "layer",
    targetLayer: "electoralBehavior",
    targetSubLayer: "electoralResults",
    aliases: ["electoral results", "vote", "resultados electorales", "voto"],
  },
  {
    id: "winning-party",
    label: "Partido ganador",
    description: "Resultados electorales",
    category: "variable",
    targetLayer: "electoralBehavior",
    targetSubLayer: "electoralResults",
    aliases: ["winner", "party winner", "ganador", "partido ganador"],
  },
  {
    id: "participation",
    label: "Participación",
    description: "Resultados electorales",
    category: "variable",
    targetLayer: "electoralBehavior",
    targetSubLayer: "electoralResults",
    aliases: ["turnout", "participación"],
  },
  {
    id: "abstention",
    label: "Abstención",
    description: "Resultados electorales",
    category: "variable",
    targetLayer: "electoralBehavior",
    targetSubLayer: "electoralResults",
    aliases: ["abstention rate", "abstención"],
  },
  {
    id: "income-level",
    label: "Nivel de renta",
    description: "Datos territoriales",
    category: "layer",
    targetLayer: "incomeLevel",
    targetSubLayer: "incomeLevel",
    aliases: ["renta", "income"],
  },
  {
    id: "individual-income",
    label: "Renta individual",
    description: "Nivel de renta",
    category: "variable",
    targetLayer: "incomeLevel",
    targetSubLayer: "incomeLevel",
    aliases: ["personal income", "renta personal", "renta individual"],
  },
  {
    id: "household-income",
    label: "Renta del hogar",
    description: "Nivel de renta",
    category: "variable",
    targetLayer: "incomeLevel",
    targetSubLayer: "incomeLevel",
    aliases: ["family income", "renta familiar", "renta hogar"],
  },
  {
    id: "land-built-environment",
    label: "Territorio / entorno construido",
    description: "Datos territoriales",
    category: "layer",
    targetLayer: "landBuiltEnvironment",
    targetSubLayer: "landBuiltEnvironment",
    targetLandMetric: "populationDensity",
    aliases: ["built environment", "land", "entorno construido", "territorio"],
  },
  {
    id: "parcel-density",
    label: "Densidad parcelaria",
    description: "Territorio / entorno construido",
    category: "variable",
    targetLayer: "landBuiltEnvironment",
    targetSubLayer: "parcelDensity",
    targetLandMetric: "parcelDensity",
  },
  {
    id: "built-footprint",
    label: "Huella construida",
    description: "Territorio / entorno construido",
    category: "variable",
    targetLayer: "landBuiltEnvironment",
    targetSubLayer: "builtFootprint",
    targetLandMetric: "builtFootprint",
  },
  {
    id: "building-intensity",
    label: "Intensidad edificatoria",
    description: "Territorio / entorno construido",
    category: "variable",
    targetLayer: "landBuiltEnvironment",
    targetSubLayer: "buildingIntensity",
    targetLandMetric: "buildingIntensity",
  },
  {
    id: "urban-intelligence",
    label: "Inteligencia urbana",
    description: "Calidad de vida",
    category: "module",
    targetLayer: "housingIntelligence",
    targetSubLayer: "qualityLife",
    targetTerritorialMetric: "qualityLife",
    aliases: ["housing intelligence", "quality life", "inteligencia inmobiliaria", "calidad de vida"],
  },
  {
    id: "socioeconomic-intelligence",
    label: "Inteligencia socioeconómica",
    description: "Desarrollo social",
    category: "module",
    targetLayer: "socioeconomicIntelligence",
    targetSubLayer: "socialDevelopment",
    targetSocioeconomicMetric: "humanCapital",
  },
  {
    id: "human-capital",
    label: "Capital humano",
    description: "Inteligencia socioeconómica",
    category: "variable",
    targetLayer: "socioeconomicIntelligence",
    targetSubLayer: "socialDevelopment",
    targetSocioeconomicMetric: "humanCapital",
  },
  {
    id: "vulnerability",
    label: "Vulnerabilidad",
    description: "Inteligencia socioeconómica",
    category: "variable",
    targetLayer: "socioeconomicIntelligence",
    targetSubLayer: "socialDevelopment",
    targetSocioeconomicMetric: "vulnerability",
  },
  {
    id: "resilience",
    label: "Resiliencia",
    description: "Inteligencia socioeconómica",
    category: "variable",
    targetLayer: "socioeconomicIntelligence",
    targetSubLayer: "socialDevelopment",
    targetSocioeconomicMetric: "resilience",
  },
  {
    id: "productive-complexity",
    label: "Complejidad productiva",
    description: "Inteligencia socioeconómica",
    category: "variable",
    targetLayer: "socioeconomicIntelligence",
    targetSubLayer: "socialDevelopment",
    targetSocioeconomicMetric: "productiveComplexity",
  },
  {
    id: "inequality-pressure",
    label: "Presión de desigualdad",
    description: "Inteligencia socioeconómica",
    category: "variable",
    targetLayer: "socioeconomicIntelligence",
    targetSubLayer: "socialDevelopment",
    targetSocioeconomicMetric: "inequalityPressure",
  },
  {
    id: "campaign-builder",
    label: "Constructor de campaña",
    description: "Previsión electoral",
    category: "tool",
    targetLayer: "electoralForecasting",
    targetSubLayer: "campaignBuilder",
    targetCampaignMetric: "swingSections",
  },
  {
    id: "ask-soctrace",
    label: "Pregunta a soctrace",
    description: "Analista IA",
    category: "tool",
    focusElementId: "ask-soctrace-input",
    aliases: ["local analyst", "ai analyst", "analista local", "analista ia"],
  },
];
