import { ArrowDown, CheckCircle2, CircleAlert, Info } from "lucide-react";
import { type ReactNode } from "react";
import electoralJson from "@/features/campaigns/data/generated/mijas-2027-block-b-electoral-diagnosis.json";

type Point = [number, number];
type Geometry = { type: "MultiPolygon"; coordinates: Point[][][] };
type Inventory = { election_id:number; election_type:string; official_name:string; election_date:string; sections:number; polling_tables:number; candidacies:number; geography_year:number; source_file:string; known_limitation:string|null };
type Summary = { election_id:number; election_type:string; official_name:string; election_date:string; census:number; voters:number; participation_pct:number; abstention_pct:number; winner:string; winner_votes:number; winner_share_pct:number; runner_up:string; runner_up_votes:number; runner_up_share_pct:number; margin_votes:number; margin_pct_points:number; valid_candidacy_votes:number; source_valid_votes:number; blank_votes:number };
type Profile = { election_id:number; seccion_id:string; display_name:string; winner_candidacy:string; winner_family:string; winner_share_pct:number; runner_up_candidacy:string; margin_pct_points:number; margin_band:string; participation_pct:number; abstention_pct:number; winner_tie:boolean; valid_candidacy_votes:number; election_date:string; geography_year:number };
type WinnerHistory = { election_id:number; election_date:string; family_id:string; winner:string; winner_changed:boolean|null };
type Volatility = { election_id:number; election_date:string; family_id:string; pedersen_index_pct_points:number; formula:string };
type Comparison = { election_a:number; election_b:number; date_a:string; date_b:string; comparable_sections:number; different_winner_sections:number; average_participation_change_pp:number; comparability_status:string };
type Ranking = { election_id:number; metric:string; ranking_side:"top"|"bottom"; rank:number; display_name:string; value:number; unit:string };
type FamilyGeometry = { familyId:string; geometry:Geometry };
type Snapshot = { metadata:{snapshotVersion:string}; electionInventory:Inventory[]; municipalSummaries:Summary[]; sectionProfiles:Profile[]; sectionWinnerHistory:WinnerHistory[]; volatility:Volatility[]; crossElectionComparisons:Comparison[]; rankings:Ranking[]; latestElection:Inventory&Summary&{baseline_assessment:string}; municipalHarmonisation:{period:string;baseGeography:string;method:string;minimumAssignmentPercent:number;familyGeometries:FamilyGeometry[]}; evidenceReferences:{partyShare:{denominator:string;calculation:string;status:string};participation:{denominator:string;calculation:string;status:string};pedersen:{denominator:string;calculation:string;status:string}} };
type MunicipalitySnapshot = { sections:{id:string;label:string;geometry:Geometry}[] };

const data = electoralJson as unknown as Snapshot;
const integer = new Intl.NumberFormat("es-ES");
const decimal = new Intl.NumberFormat("es-ES",{minimumFractionDigits:2,maximumFractionDigits:4});
const summary=(id:number)=>{const item=data.municipalSummaries.find(x=>x.election_id===id);if(!item)throw new Error(`Missing election summary ${id}`);return item};
const label=(type:string,date:string)=>`${type.replace("PARLAMENTO_EUROPEO","Europeas").replace("MUNICIPALES","Municipales").replace("ANDALUZAS","Andaluzas").replace("CONGRESO","Congreso")} ${new Date(`${date}T12:00:00`).getFullYear()}`;


function Status({kind="verified",children}:{kind?:"verified"|"harmonised"|"movement"|"baseline"|"synthesis";children:ReactNode}){return <span className={`electoral-status electoral-status--${kind}`}><CheckCircle2/>{children}</span>}
function Evidence({value,unit,denominator,election,geography,scope,source,calculation,status,comparability}:{value:string;unit:string;denominator:string;election:string;geography:string;scope:string;source:string;calculation:string;status:string;comparability:string}){return <details className="electoral-evidence"><summary><Info/> Evidencia y método</summary><dl><div><dt>Valor</dt><dd>{value} {unit}</dd></div><div><dt>Denominador</dt><dd>{denominator}</dd></div><div><dt>Elección</dt><dd>{election}</dd></div><div><dt>Geografía</dt><dd>{geography}</dd></div><div><dt>Ámbito</dt><dd>{scope}</dd></div><div><dt>Fuente</dt><dd>{source}</dd></div><div><dt>Cálculo</dt><dd>{calculation}</dd></div><div><dt>Estado</dt><dd>{status}</dd></div><div><dt>Comparabilidad</dt><dd>{comparability}</dd></div></dl></details>}




export function ElectoralDiagnosisStory(){const latest={...data.latestElection,...summary(data.latestElection.election_id)};const compare=(a:number,b:number)=>data.crossElectionComparisons.find(x=>x.election_a===a&&x.election_b===b)!;const comparisons=[compare(1,10),compare(1,16),compare(10,16)];return <section id="electoral-landscape" className="electoral-diagnosis" aria-labelledby="electoral-title">
  <header className="electoral-opening"><div><Status>12 elecciones verificadas</Status><p>05 · Diagnóstico electoral</p><h2 id="electoral-title">Diagnóstico<br/>electoral</h2><span>Mijas no vota igual en todas las elecciones ni en todos sus territorios.</span></div></header>
  <section className="electoral-scene electoral-latest" aria-labelledby="electoral-latest-title"><div><Status kind="baseline">Línea de base contextual</Status><p>09 · Última elección cargada</p><h3 id="electoral-latest-title">Andaluzas<br/>2026.</h3><span className="context-warning"><CircleAlert/>Resultado de una elección regional. No puede trasladarse directamente a un escenario municipal.</span></div><div className="latest-result"><header><span>17 mayo 2026 · 41 secciones</span><strong>{latest.winner}</strong><small>{integer.format(latest.winner_votes)} votos · {decimal.format(latest.winner_share_pct)} %</small></header><article><span>Segunda candidatura</span><strong>{latest.runner_up}</strong><small>{decimal.format(latest.runner_up_share_pct)} %</small></article><article><span>Margen</span><strong>{decimal.format(latest.margin_pct_points)} pp</strong></article><article><span>Participación</span><strong>{decimal.format(latest.participation_pct)} %</strong></article><footer>{latest.winner} obtuvo la primera posición en 41 de 41 secciones.</footer><Evidence value={decimal.format(latest.winner_share_pct)} unit="%" denominator={`${integer.format(latest.valid_candidacy_votes)} votos a candidaturas`} election="Andaluzas · 17 mayo 2026" geography="Oficial provisional 2026 · 41 secciones" scope="Municipio de Mijas" source={latest.source_file} calculation={data.evidenceReferences.partyShare.calculation} status="Línea de base contextual verificada" comparability={`El campo almacenado de ${integer.format(latest.source_valid_votes)} votos válidos incluye ${integer.format(latest.blank_votes)} votos en blanco; no es una previsión municipal.`}/></div></section>
  <section className="electoral-scene electoral-type-change" aria-labelledby="electoral-type-title"><header><p>10 · Comparación por tipo</p><h3 id="electoral-type-title">Cambiar de elección cambia el mapa.</h3></header><div>{comparisons.map(x=><article key={`${x.election_a}-${x.election_b}`}><header><span>{label(summary(x.election_a).election_type,x.date_a)}</span><b>→</b><span>{label(summary(x.election_b).election_type,x.date_b)}</span></header><strong>{x.different_winner_sections}<small> / {x.comparable_sections}</small></strong><p>secciones con ganador distinto</p><footer>Participación media {x.average_participation_change_pp>0?"+":""}{decimal.format(x.average_participation_change_pp)} pp</footer></article>)}</div><p className="electoral-neutral-note">Comparación descriptiva de resultados agregados. No identifica motivaciones ni transferencias individuales.</p></section>
  <section className="electoral-scene electoral-geography" aria-labelledby="electoral-geography-title"><header><p>11 · Geografía comparable</p><h3 id="electoral-geography-title">Comparamos territorios equivalentes, no códigos que cambiaron.</h3></header><div className="geography-counts">{[{y:2015,n:28},{y:2019,n:30},{y:2023,n:37},{y:2026,n:41}].map((x,i)=><article key={x.y}><span>{x.y}</span><strong>{x.n}</strong><small>secciones</small>{i<3?<b>→</b>:null}</article>)}</div><div className="geography-method"><Status kind="harmonised">28 familias territoriales armonizadas</Status><p>La historia municipal vuelve a una base territorial común de 2015. Las comparaciones directas se usan únicamente cuando las fronteras son compatibles.</p><small>394 de 394 registros elección-sección disponen de geometría.</small></div><Evidence value="394 / 394" unit="registros con geometría" denominator="registros elección-sección" election="12 elecciones · 2014–2026" geography="Histórica oficial y armonizada" scope="Secciones de Mijas" source="Snapshot electoral verificado" calculation="unión por geografía anual; armonización espacial para historia municipal" status="Metodología geográfica verificada" comparability={data.municipalHarmonisation.method}/></section>
  <section className="electoral-closing"><div><Status kind="synthesis">Síntesis consultiva basada en evidencia electoral verificada</Status><p>12 · Síntesis</p><h3>Mijas combina competencia municipal, cambio territorial y niveles de participación que varían con fuerza según la elección.</h3><span>El mapa municipal de 2023 sigue siendo la referencia local correcta; las elecciones posteriores muestran cómo evolucionó el entorno electoral general.</span><a href="#target-profiles">Continuar a perfiles territoriales <ArrowDown/></a></div></section>
 </section>}
