import { ArrowDown, CheckCircle2, CircleAlert, Equal, Info, MapPin } from "lucide-react";
import { useMemo, useState, type ReactNode } from "react";
import electoralJson from "@/features/campaigns/data/generated/mijas-2027-block-b-electoral-diagnosis.json";
import municipalityJson from "@/features/campaigns/data/generated/mijas-2027-municipality.json";

type Point = [number, number];
type Geometry = { type: "MultiPolygon"; coordinates: Point[][][] };
type Inventory = { election_id:number; election_type:string; official_name:string; election_date:string; sections:number; polling_tables:number; candidacies:number; geography_year:number; source_file:string; known_limitation:string|null };
type Summary = { election_id:number; election_type:string; official_name:string; election_date:string; census:number; voters:number; participation_pct:number; abstention_pct:number; winner:string; winner_votes:number; winner_share_pct:number; runner_up:string; runner_up_votes:number; runner_up_share_pct:number; margin_votes:number; margin_pct_points:number; valid_candidacy_votes:number; source_valid_votes:number; blank_votes:number };
type Profile = { election_id:number; seccion_id:string; display_name:string; winner_candidacy:string; winner_family:string; winner_share_pct:number; runner_up_candidacy:string; margin_pct_points:number; margin_band:string; participation_pct:number; abstention_pct:number; winner_tie:boolean; valid_candidacy_votes:number; election_date:string; geography_year:number };
type WinnerHistory = { election_id:number; election_date:string; family_id:string; winner:string; winner_changed:boolean|null };
type Volatility = { election_id:number; election_date:string; family_id:string; pedersen_index_pct_points:number; formula:string };
type Comparison = { election_a:number; election_b:number; date_a:string; date_b:string; comparable_sections:number; different_winner_sections:number; average_participation_change_pp:number; comparability_status:string };
type Ranking = { election_id:number; metric:string; ranking_side:"top"|"bottom"; rank:number; display_name:string; value:number; unit:string };
type FamilyGeometry = { familyId:string; geometry:Geometry };
type Snapshot = { metadata:{snapshotVersion:string}; electionInventory:Inventory[]; municipalSummaries:Summary[]; sectionProfiles:Profile[]; sectionWinnerHistory:WinnerHistory[]; volatility:Volatility[]; crossElectionComparisons:Comparison[]; rankings:Ranking[]; latestElection:Inventory&Summary&{baseline_assessment:string}; municipalHarmonisation:{period:string;baseGeography:string;method:string;minimumAssignmentPercent:number;familyGeometries:FamilyGeometry[]}; evidenceReferences:{partyShare:{denominator:string;calculation:string;status:string};participation:{denominator:string;calculation:string;status:string};pedersen:{denominator:string;calculation:string;status:string}} };
type MunicipalitySnapshot = { sections:{id:string;label:string;geometry:Geometry}[] };

const data = electoralJson as unknown as Snapshot;
const municipality = municipalityJson as unknown as MunicipalitySnapshot;
const integer = new Intl.NumberFormat("es-ES");
const decimal = new Intl.NumberFormat("es-ES",{minimumFractionDigits:2,maximumFractionDigits:4});
const shortDate = new Intl.DateTimeFormat("es-ES",{day:"2-digit",month:"short",year:"numeric"});
const colors:Record<string,string>={PP:"#3b82f6",PSOE:"#ef5d78","PSOE-A":"#ef5d78",VOX:"#45c486",CS:"#e6b84a",Cs:"#e6b84a",OTHER:"#8795a1",LOCAL:"#ad7bc5"};
const color=(party:string)=>colors[party]??"#8795a1";
const summary=(id:number)=>{const item=data.municipalSummaries.find(x=>x.election_id===id);if(!item)throw new Error(`Missing election summary ${id}`);return item};
const profile=(id:number)=>data.sectionProfiles.filter(x=>x.election_id===id);
const ranking=(id:number,metric:string,side:"top"|"bottom")=>{const item=data.rankings.find(x=>x.election_id===id&&x.metric===metric&&x.ranking_side===side&&x.rank===1);if(!item)throw new Error(`Missing ranking ${id}/${metric}/${side}`);return item};
const label=(type:string,date:string)=>`${type.replace("PARLAMENTO_EUROPEO","Europeas").replace("MUNICIPALES","Municipales").replace("ANDALUZAS","Andaluzas").replace("CONGRESO","Congreso")} ${new Date(`${date}T12:00:00`).getFullYear()}`;

function projector(geometries:Geometry[]){const pts=geometries.flatMap(g=>g.coordinates.flatMap(p=>p.flatMap(r=>r)));const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),w=960,h=650,p=28,s=Math.min((w-2*p)/(maxX-minX),(h-2*p)/(maxY-minY)),ox=(w-(maxX-minX)*s)/2,oy=(h-(maxY-minY)*s)/2;const point=([x,y]:Point)=>[ox+(x-minX)*s,h-oy-(y-minY)*s];return(g:Geometry)=>g.coordinates.map(poly=>poly.map(r=>r.map((q,i)=>`${i?"L":"M"}${point(q).map(v=>v.toFixed(1)).join(" ")}`).join(" ")+" Z").join(" ")).join(" ")}

function Status({kind="verified",children}:{kind?:"verified"|"harmonised"|"movement"|"baseline"|"synthesis";children:ReactNode}){return <span className={`electoral-status electoral-status--${kind}`}><CheckCircle2/>{children}</span>}
function Evidence({value,unit,denominator,election,geography,scope,source,calculation,status,comparability}:{value:string;unit:string;denominator:string;election:string;geography:string;scope:string;source:string;calculation:string;status:string;comparability:string}){return <details className="electoral-evidence"><summary><Info/> Evidencia y método</summary><dl><div><dt>Valor</dt><dd>{value} {unit}</dd></div><div><dt>Denominador</dt><dd>{denominator}</dd></div><div><dt>Elección</dt><dd>{election}</dd></div><div><dt>Geografía</dt><dd>{geography}</dd></div><div><dt>Ámbito</dt><dd>{scope}</dd></div><div><dt>Fuente</dt><dd>{source}</dd></div><div><dt>Cálculo</dt><dd>{calculation}</dd></div><div><dt>Estado</dt><dd>{status}</dd></div><div><dt>Comparabilidad</dt><dd>{comparability}</dd></div></dl></details>}

function ElectionTimeline(){const ordered=[...data.electionInventory].sort((a,b)=>a.election_date.localeCompare(b.election_date));const [selected,setSelected]=useState(ordered[ordered.length-1].election_id);const active=summary(selected);const inv=ordered.find(x=>x.election_id===selected)!;const ties=profile(selected).filter(x=>x.winner_tie);return <div className="electoral-timeline"><div className="electoral-timeline-track" role="tablist" aria-label="Elecciones disponibles">{ordered.map((item,index)=><button key={item.election_id} role="tab" aria-selected={selected===item.election_id} onClick={()=>setSelected(item.election_id)}><i className={selected===item.election_id?"active":""}/><span>{item.election_type==="PARLAMENTO_EUROPEO"?"UE":item.election_type==="MUNICIPALES"?"MUN":item.election_type==="ANDALUZAS"?"AND":"CON"}</span><strong>{new Date(`${item.election_date}T12:00:00`).getFullYear()}</strong>{index===ordered.length-1?<small>Última</small>:null}</button>)}</div><article className="electoral-timeline-detail" aria-live="polite"><header><div><p>{inv.official_name}</p><h4>{shortDate.format(new Date(`${inv.election_date}T12:00:00`))}</h4></div>{selected===data.latestElection.election_id?<Status kind="baseline">Última elección cargada</Status>:<Status>Resultado verificado</Status>}</header><div><span>Ganador municipal</span><strong style={{color:color(active.winner)}}>{active.winner}</strong><small>{decimal.format(active.winner_share_pct)} %</small></div><div><span>Participación</span><strong>{decimal.format(active.participation_pct)} %</strong></div><div><span>Margen</span><strong>{decimal.format(active.margin_pct_points)} pp</strong></div>{ties.length?<p className="electoral-tie-note"><Equal/> {ties.length} empate{ties.length>1?"s":""} en primera posición: {ties.map(x=>x.display_name.replace(/^Sección \d+ · /,"")).join(", ")}.</p>:null}<Evidence value={decimal.format(active.winner_share_pct)} unit="%" denominator="votos a candidaturas" election={`${inv.official_name} · ${inv.election_date}`} geography={`${inv.geography_year} · ${inv.sections} secciones`} scope="Municipio de Mijas" source={inv.source_file} calculation={data.evidenceReferences.partyShare.calculation} status="Resultado electoral verificado" comparability="Lectura dentro de la geografía de la elección"/></article></div>}

type MapMode="winner"|"margin"|"participation"|"abstention";
function MunicipalMap(){const rows=profile(1);const joined=municipality.sections.map(s=>({...s,result:rows.find(r=>r.seccion_id===s.id)})).filter(x=>x.result);const path=useMemo(()=>projector(joined.map(x=>x.geometry)),[joined]);const [mode,setMode]=useState<MapMode>("winner");const [selected,setSelected]=useState(joined[0].id);const active=joined.find(x=>x.id===selected)??joined[0];const fill=(r:Profile)=>mode==="winner"?color(r.winner_family):mode==="margin"?r.margin_pct_points<5?"#f6b26b":r.margin_pct_points<10?"#e77832":"#8f351d":mode==="participation"?`rgba(59,130,246,${.2+r.participation_pct/100})`:`rgba(173,123,197,${.2+r.abstention_pct/100})`;return <div className="electoral-map"><header><div><span>Municipales · 28 mayo 2023</span><strong>{mode==="winner"?"Ganador por sección":mode==="margin"?"Margen entre primero y segundo":mode==="participation"?"Participación":"Abstención"}</strong></div><Status>37 secciones oficiales</Status></header><svg viewBox="0 0 960 650" aria-label={`Mapa municipal 2023: ${mode}`}>{joined.map(x=><path key={x.id} d={path(x.geometry)} fill={fill(x.result!)} className={x.id===active.id?"selected":""} fillRule="evenodd" tabIndex={0} role="button" aria-label={`${x.result!.display_name}: ${mode==="winner"?x.result!.winner_candidacy:`${decimal.format(x.result![mode==="margin"?"margin_pct_points":mode==="participation"?"participation_pct":"abstention_pct"])} ${mode==="margin"?"puntos porcentuales":"por ciento"}`}${x.result!.winner_tie?", empate en primera posición":""}`} onClick={()=>setSelected(x.id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(x.id)}}}><title>{x.result!.display_name}</title></path>)}</svg><div className="electoral-map-modes">{(["winner","margin","participation","abstention"] as MapMode[]).map(item=><button key={item} className={mode===item?"active":""} aria-pressed={mode===item} onClick={()=>setMode(item)}>{item==="winner"?"Ganador":item==="margin"?"Margen":item==="participation"?"Participación":"Abstención"}</button>)}</div><aside aria-live="polite"><p><MapPin/>{active.result!.display_name}</p>{active.result!.winner_tie?<span className="tie"><Equal/> Empate en primera posición</span>:null}<strong>{mode==="winner"?active.result!.winner_candidacy:`${decimal.format(active.result![mode==="margin"?"margin_pct_points":mode==="participation"?"participation_pct":"abstention_pct"])}${mode==="margin"?" pp":" %"}`}</strong><small>{mode==="winner"?`${decimal.format(active.result!.winner_share_pct)} % · margen ${decimal.format(active.result!.margin_pct_points)} pp`:mode==="margin"?active.result!.margin_band.replace("margin_under_5_pp","Menos de 5 pp").replace("margin_5_to_under_10_pp","De 5 a menos de 10 pp").replace("margin_10_pp_or_more","10 pp o más"):"Sobre censo electoral"}</small></aside></div>}

function FamilyMap({electionId,title}:{electionId:number;title:string}){const rows=data.sectionWinnerHistory.filter(x=>x.election_id===electionId);const geoms=data.municipalHarmonisation.familyGeometries;const path=useMemo(()=>projector(geoms.map(x=>x.geometry)),[geoms]);return <article className="family-map"><header><span>{title}</span><strong>{rows.filter(x=>x.winner==="PP").length} PP · {rows.filter(x=>x.winner==="PSOE").length} PSOE · {rows.filter(x=>x.winner==="CS").length} Cs</strong></header><svg viewBox="0 0 960 650" aria-label={`Ganador de las 28 familias territoriales, ${title}`}>{geoms.map(g=>{const row=rows.find(r=>r.family_id===g.familyId)!;return <path key={g.familyId} d={path(g.geometry)} fill={color(row.winner)} fillRule="evenodd" className={row.winner_changed?"changed":"retained"}><title>{g.familyId}: {row.winner}{row.winner_changed?", cambió ganador":", retuvo ganador"}</title></path>})}</svg><footer><span><i className="changed"/>Cambió ganador</span><span><i className="retained"/>Mantuvo ganador</span></footer></article>}

export function ElectoralDiagnosisStory(){const municipal2023=summary(1);const latest={...data.latestElection,...summary(data.latestElection.election_id)};const narrow=ranking(1,"first_second_margin","bottom"),wide=ranking(1,"first_second_margin","top"),partHigh=ranking(1,"participation","top"),partLow=ranking(1,"participation","bottom");const win2023=data.sectionWinnerHistory.filter(x=>x.election_id===1);const changed=win2023.filter(x=>x.winner_changed).length;const retained=win2023.filter(x=>x.winner_changed===false).length;const volatility2019=data.volatility.filter(x=>x.election_id===4),volatility2023=data.volatility.filter(x=>x.election_id===1);const mean=(rows:Volatility[])=>rows.reduce((s,x)=>s+x.pedersen_index_pct_points,0)/rows.length;const compare=(a:number,b:number)=>data.crossElectionComparisons.find(x=>x.election_a===a&&x.election_b===b)!;const comparisons=[compare(1,10),compare(1,16),compare(10,16)];const municipalHistory=[summary(11),summary(4),summary(1)];return <section id="electoral-landscape" className="electoral-diagnosis" aria-labelledby="electoral-title">
  <header className="electoral-opening"><div><Status>12 elecciones verificadas</Status><p>05 · Diagnóstico electoral</p><h2 id="electoral-title">Diagnóstico<br/>electoral</h2><span>Mijas no vota igual en todas las elecciones ni en todos sus territorios.</span></div></header>
  <section className="electoral-scene electoral-elections" aria-labelledby="electoral-elections-title"><header><p>01 · Secuencia electoral</p><h3 id="electoral-elections-title">Doce elecciones.<br/>Distintas fotografías.</h3><span>Explore la secuencia para ver cómo cambian ganador, participación y margen según el tipo de elección.</span></header><ElectionTimeline/></section>
  <section className="electoral-scene electoral-municipal" aria-labelledby="electoral-municipal-title"><div className="electoral-municipal-copy"><Status>Resultado municipal verificado</Status><p>02 · Municipales 2023</p><h3 id="electoral-municipal-title">Una diferencia municipal de <em>{decimal.format(municipal2023.margin_pct_points)} puntos.</em></h3><div><span>Ganador municipal</span><strong>{municipal2023.winner}</strong><small>{decimal.format(municipal2023.winner_share_pct)} %</small></div><p>Participación {decimal.format(municipal2023.participation_pct)} % · abstención {decimal.format(municipal2023.abstention_pct)} %.</p><Evidence value={decimal.format(municipal2023.margin_pct_points)} unit="puntos porcentuales" denominator="votos a candidaturas" election="Municipales · 28 mayo 2023" geography="37 secciones oficiales de 2023" scope="Municipio de Mijas" source="Snapshot electoral verificado" calculation="cuota del primero − cuota del segundo" status="Resultado electoral verificado" comparability="Base municipal directa"/></div><MunicipalMap/></section>
  <section className="electoral-scene electoral-competition" aria-labelledby="electoral-competition-title"><header><p>03 · Diferencias territoriales</p><h3 id="electoral-competition-title">La competencia no fue uniforme.</h3><span>El resultado municipal fue próximo a escala municipal, pero no igual de próximo en cada sección.</span></header><div className="margin-extremes"><article><span>Margen más estrecho</span><h4>{narrow.display_name.replace(/^Sección \d+ · /,"")}</h4><strong>{decimal.format(narrow.value)} pp</strong></article><i/><article><span>Margen más amplio</span><h4>{wide.display_name.replace(/^Sección \d+ · /,"")}</h4><strong>{decimal.format(wide.value)} pp</strong></article></div><div className="margin-bands"><span><i/>Menos de 5 pp</span><span><i/>De 5 a menos de 10 pp</span><span><i/>10 pp o más</span></div><Evidence value={`${decimal.format(narrow.value)}–${decimal.format(wide.value)}`} unit="puntos porcentuales" denominator="votos a candidaturas" election="Municipales · 28 mayo 2023" geography="37 secciones oficiales" scope="Secciones de Mijas" source="Snapshot electoral verificado" calculation="cuota del primero − cuota del segundo" status="Resultado electoral verificado" comparability="Comparación dentro de la misma elección"/></section>
  <section className="electoral-scene electoral-change" aria-labelledby="electoral-change-title"><header><Status kind="harmonised">Comparación armonizada</Status><p>04 · Cambio del mapa municipal</p><h3 id="electoral-change-title">El mapa municipal cambió.</h3><span>La comparación reúne las secciones de ambos años en 28 territorios equivalentes.</span></header><div className="family-map-pair"><FamilyMap electionId={4} title="Municipales 2019"/><b>→</b><FamilyMap electionId={1} title="Municipales 2023"/></div><div className="electoral-retention"><article><strong>{changed}</strong><span>de 28 cambiaron ganador</span></article><article><strong>{retained}</strong><span>mantuvieron ganador</span></article></div><Evidence value={`${changed} cambios · ${retained} permanencias`} unit="familias" denominator="28 familias territoriales" election="Municipales 2019 → Municipales 2023" geography={data.municipalHarmonisation.baseGeography} scope="Municipio de Mijas" source="Snapshot electoral armonizado" calculation="ganador recalculado tras agregar votos a familias territoriales equivalentes" status="Comparación armonizada" comparability={`Asignación espacial validada · confianza mínima ${decimal.format(data.municipalHarmonisation.minimumAssignmentPercent)} %`}/></section>
  <section className="electoral-scene electoral-movement" aria-labelledby="electoral-movement-title"><div><Status kind="movement">Movimiento electoral descriptivo</Status><p>05 · Distribución agregada del voto</p><h3 id="electoral-movement-title">Más movimiento en el último ciclo municipal.</h3><p>La proporción agregada del voto que cambió entre familias políticas fue mayor entre 2019 y 2023.</p></div><div className="movement-comparison"><article><span>2015 → 2019</span><strong>{decimal.format(mean(volatility2019))}</strong><small>puntos porcentuales medios</small><i style={{width:`${100*mean(volatility2019)/mean(volatility2023)}%`}}/></article><article><span>2019 → 2023</span><strong>{decimal.format(mean(volatility2023))}</strong><small>puntos porcentuales medios</small><i style={{width:"100%"}}/></article></div><details className="movement-method"><summary><Info/> Cómo se calcula</summary><p>La medida suma los cambios absolutos de cuota de las familias políticas normalizadas y divide el resultado entre dos. Las entradas y salidas se tratan como movimientos desde o hacia cero. No estima transferencias de votantes individuales.</p><code>{data.evidenceReferences.pedersen.calculation}</code></details></section>
  <section className="electoral-scene electoral-participation" aria-labelledby="electoral-participation-title"><header><p>06 · Participación</p><h3 id="electoral-participation-title">La elección cambia la movilización observada.</h3><span>La participación no se mantiene fija entre procesos electorales.</span></header><div className="municipal-participation">{municipalHistory.map(x=><article key={x.election_id}><span>{new Date(`${x.election_date}T12:00:00`).getFullYear()}</span><i style={{height:`${x.participation_pct}%`}}/><strong>{decimal.format(x.participation_pct)} %</strong></article>)}</div><div className="participation-comparisons">{comparisons.map(x=><article key={`${x.election_a}-${x.election_b}`}><span>{label(summary(x.election_a).election_type,x.date_a)}</span><b>→</b><span>{label(summary(x.election_b).election_type,x.date_b)}</span><strong>{x.average_participation_change_pp>0?"+":""}{decimal.format(x.average_participation_change_pp)} pp</strong></article>)}</div><div className="participation-territory"><span>Municipales 2023</span><p>Mayor participación: <b>{partHigh.display_name.replace(/^Sección \d+ · /,"")} · {decimal.format(partHigh.value)} %</b></p><p>Menor participación: <b>{partLow.display_name.replace(/^Sección \d+ · /,"")} · {decimal.format(partLow.value)} %</b></p></div><Evidence value={decimal.format(municipal2023.participation_pct)} unit="%" denominator="censo electoral" election="Municipales · 28 mayo 2023" geography="37 secciones oficiales" scope="Municipio y secciones de Mijas" source="Snapshot electoral verificado" calculation={data.evidenceReferences.participation.calculation} status="Resultado electoral verificado" comparability="Cambios directos solo entre las 37 secciones compatibles"/></section>
  <section className="electoral-scene electoral-latest" aria-labelledby="electoral-latest-title"><div><Status kind="baseline">Línea de base contextual</Status><p>07 · Última elección cargada</p><h3 id="electoral-latest-title">Andaluzas<br/>2026.</h3><span className="context-warning"><CircleAlert/>Resultado de una elección regional. No puede trasladarse directamente a un escenario municipal.</span></div><div className="latest-result"><header><span>17 mayo 2026 · 41 secciones</span><strong>{latest.winner}</strong><small>{integer.format(latest.winner_votes)} votos · {decimal.format(latest.winner_share_pct)} %</small></header><article><span>Segunda candidatura</span><strong>{latest.runner_up}</strong><small>{decimal.format(latest.runner_up_share_pct)} %</small></article><article><span>Margen</span><strong>{decimal.format(latest.margin_pct_points)} pp</strong></article><article><span>Participación</span><strong>{decimal.format(latest.participation_pct)} %</strong></article><footer>{latest.winner} obtuvo la primera posición en 41 de 41 secciones.</footer><Evidence value={decimal.format(latest.winner_share_pct)} unit="%" denominator={`${integer.format(latest.valid_candidacy_votes)} votos a candidaturas`} election="Andaluzas · 17 mayo 2026" geography="Oficial provisional 2026 · 41 secciones" scope="Municipio de Mijas" source={latest.source_file} calculation={data.evidenceReferences.partyShare.calculation} status="Línea de base contextual verificada" comparability={`El campo almacenado de ${integer.format(latest.source_valid_votes)} votos válidos incluye ${integer.format(latest.blank_votes)} votos en blanco; no es una previsión municipal.`}/></div></section>
  <section className="electoral-scene electoral-type-change" aria-labelledby="electoral-type-title"><header><p>08 · Comparación por tipo</p><h3 id="electoral-type-title">Cambiar de elección cambia el mapa.</h3></header><div>{comparisons.map(x=><article key={`${x.election_a}-${x.election_b}`}><header><span>{label(summary(x.election_a).election_type,x.date_a)}</span><b>→</b><span>{label(summary(x.election_b).election_type,x.date_b)}</span></header><strong>{x.different_winner_sections}<small> / {x.comparable_sections}</small></strong><p>secciones con ganador distinto</p><footer>Participación media {x.average_participation_change_pp>0?"+":""}{decimal.format(x.average_participation_change_pp)} pp</footer></article>)}</div><p className="electoral-neutral-note">Comparación descriptiva de resultados agregados. No identifica motivaciones ni transferencias individuales.</p></section>
  <section className="electoral-scene electoral-geography" aria-labelledby="electoral-geography-title"><header><p>09 · Geografía comparable</p><h3 id="electoral-geography-title">Comparamos territorios equivalentes, no códigos que cambiaron.</h3></header><div className="geography-counts">{[{y:2015,n:28},{y:2019,n:30},{y:2023,n:37},{y:2026,n:41}].map((x,i)=><article key={x.y}><span>{x.y}</span><strong>{x.n}</strong><small>secciones</small>{i<3?<b>→</b>:null}</article>)}</div><div className="geography-method"><Status kind="harmonised">28 familias territoriales armonizadas</Status><p>La historia municipal vuelve a una base territorial común de 2015. Las comparaciones directas se usan únicamente cuando las fronteras son compatibles.</p><small>394 de 394 registros elección-sección disponen de geometría.</small></div><Evidence value="394 / 394" unit="registros con geometría" denominator="registros elección-sección" election="12 elecciones · 2014–2026" geography="Histórica oficial y armonizada" scope="Secciones de Mijas" source="Snapshot electoral verificado" calculation="unión por geografía anual; armonización espacial para historia municipal" status="Metodología geográfica verificada" comparability={data.municipalHarmonisation.method}/></section>
  <section className="electoral-closing"><div><Status kind="synthesis">Síntesis consultiva basada en evidencia electoral verificada</Status><p>10 · Síntesis</p><h3>Mijas combina competencia municipal, cambio territorial y niveles de participación que varían con fuerza según la elección.</h3><span>El mapa municipal de 2023 sigue siendo la referencia local correcta; las elecciones posteriores muestran cómo evolucionó el entorno electoral general.</span><a href="#target-profiles">Continuar a perfiles territoriales <ArrowDown/></a></div></section>
 </section>}
