import { ArrowRight, Menu, Printer, X } from "lucide-react";
import { lazy, Suspense, useMemo, useState, type ComponentType } from "react";
import municipalityJson from "@/features/campaigns/data/generated/mijas-2027-municipality.json";
import electoralJson from "@/features/campaigns/data/generated/mijas-2027-block-b-electoral-diagnosis.json";
import clustersJson from "@/features/campaigns/data/generated/mijas-2027-block-d-territorial-clusters.json";
import territoryIndexJson from "@/features/campaigns/data/generated/block-c/territory-index.json";
import { mijas2027TypologyPresentation as typologies } from "@/features/campaigns/data/mijas-2027-typologies";
import { campaignSourceLine } from "@/features/campaigns/data/clientSources";
import "./ExecutiveCampaign.css";

type Point=[number,number]; type Geometry={type:"MultiPolygon";coordinates:Point[][][]};
type Section={id:string;label:string;geometry:Geometry};
type Profile={election_id:number;seccion_id:string;display_name:string;winner_family:string;winner_candidacy:string;winner_share_pct:number;margin_pct_points:number;participation_pct:number};
type Winner={election_id:number;family_id:string;winner:string;winner_changed:boolean|null};
type Election={election_id:number;election_date:string;election_type:string};
type Summary={election_id:number;winner:string;runner_up:string;winner_share_pct:number;runner_up_share_pct:number;participation_pct:number;margin_pct_points:number};
type Cluster={cluster_id:keyof typeof typologies.groups;section_count:number;population_represented:number;top_above:string[];top_below:string[]};
type IndexItem={sectionId:string;displayName:string;metrics:Record<string,string|number|null>};
const municipality=municipalityJson as unknown as {sections:Section[]};
const electoral=electoralJson as unknown as {sectionProfiles:Profile[];sectionWinnerHistory:Winner[];electionInventory:Election[];municipalSummaries:Summary[];municipalHarmonisation:{familyGeometries:{familyId:string;geometry:Geometry}[]}};
const clusters=(clustersJson as unknown as {clusterProfiles:Cluster[]}).clusterProfiles;
const territoryIndex=territoryIndexJson as unknown as IndexItem[];
const colors=["#e7a65d","#70b2aa","#9b8dcc","#dc7f70","#8dab70"];
const party:Record<string,string>={PP:"#5295ee",PSOE:"#ed6680","PSOE-A":"#ed6680",CS:"#e6b84a",Cs:"#e6b84a"};
const num=new Intl.NumberFormat("es-ES");

function projector(geometries:Geometry[]){const pts=geometries.flatMap(g=>g.coordinates.flatMap(p=>p.flatMap(r=>r)));const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);const [minX,maxX,minY,maxY]=[Math.min(...xs),Math.max(...xs),Math.min(...ys),Math.max(...ys)];const w=900,h=620,p=18,s=Math.min((w-2*p)/(maxX-minX),(h-2*p)/(maxY-minY));return(g:Geometry)=>g.coordinates.map(poly=>poly.map(r=>r.map(([x,y],i)=>`${i?"L":"M"}${(p+(x-minX)*s).toFixed(1)} ${(h-p-(y-minY)*s).toFixed(1)}`).join(" ")+" Z").join(" ")).join(" ")}

function CommercialSectionMap({mode="neutral",selected,onSelect,className=""}:{mode?:"neutral"|"population"|"variation"|"electoral"|"typology"|"participation";selected?:string;onSelect?:(id:string)=>void;className?:string}){
 const profiles=electoral.sectionProfiles.filter(x=>x.election_id===1); const path=useMemo(()=>projector(municipality.sections.map(x=>x.geometry)),[]);
 const membership=new Map((clustersJson as any).territoryMembership.map((x:any)=>[x.seccion_id,x.cluster_id]));
 const populations=territoryIndex.map(x=>Number(x.metrics.population));const minPopulation=Math.min(...populations),maxPopulation=Math.max(...populations);
 return <svg className={`exec-map ${className}`} viewBox="0 0 900 620" preserveAspectRatio="xMidYMid meet" role="img" aria-label="Mapa real de las 37 secciones de Mijas">{municipality.sections.map(s=>{const p=profiles.find(x=>x.seccion_id===s.id);const group=membership.get(s.id) as string|undefined;const item=territoryIndex.find(x=>x.sectionId===s.id);const population=Number(item?.metrics.population),variation=Number(item?.metrics.growth_percent_2023_2024);let fill="#18344a";if(mode==="population"){const t=(population-minPopulation)/Math.max(1,maxPopulation-minPopulation);fill=`hsl(205 58% ${76-t*52}%)`}if(mode==="variation")fill=variation>1?"#53b69a":variation<0?"#d86f76":"#d8c58a";if(mode==="electoral")fill=party[p?.winner_family||""]||"#64748b";if(mode==="typology")fill=colors[Math.max(0,Number(group?.replace("Group ",""))-1)];if(mode==="participation")fill=`hsl(205 65% ${74-(p?.participation_pct||50)*.65}%)`;return <path key={s.id} d={path(s.geometry)} fill={fill} className={selected===s.id?"selected":""} tabIndex={onSelect?0:undefined} role={onSelect?"button":undefined} onClick={()=>onSelect?.(s.id)} onKeyDown={e=>{if(onSelect&&(e.key==="Enter"||e.key===" "))onSelect(s.id)}}><title>{s.label}{mode==="population"?` · ${num.format(population)} residentes`:mode==="variation"?` · ${variation.toFixed(2)} %`:p?` · ${p.winner_candidacy} · ${p.participation_pct.toFixed(2)} %`:""}</title></path>})}</svg>
}
const MijasMap=CommercialSectionMap;

function FamilyElectionMap({electionId,label}:{electionId:number;label:string}){const geos=electoral.municipalHarmonisation.familyGeometries;const path=useMemo(()=>projector(geos.map(x=>x.geometry)),[geos]);const rows=electoral.sectionWinnerHistory.filter(x=>x.election_id===electionId);return <figure className={`exec-family-map exec-family-map--${electionId}`}><figcaption>{label}</figcaption><svg viewBox="0 0 900 620" preserveAspectRatio="xMidYMid meet" role="img" aria-label={`Mapa electoral armonizado de ${label}`}>{geos.map(g=>{const row=rows.find(x=>x.family_id===g.familyId);const changed=electoral.sectionWinnerHistory.find(x=>x.election_id===1&&x.family_id===g.familyId)?.winner_changed;return <path key={g.familyId} d={path(g.geometry)} fill={party[row?.winner||""]||"#788694"} className={changed?"changed":"stable"}><title>{g.familyId} · {row?.winner}</title></path>})}</svg><div className="exec-comparison-legend"><span><i style={{background:party.PP}}/>PP</span><span><i style={{background:party.PSOE}}/>PSOE</span><span><i style={{background:party.CS}}/>Cs</span><span><i className="outline"/>Cambió</span></div></figure>}
function LocatorMap({sectionId}:{sectionId:string}){const path=useMemo(()=>projector(municipality.sections.map(x=>x.geometry)),[]);return <svg className="exec-locator" viewBox="0 0 900 620" role="img" aria-label={`Localizador de ${sectionId}`}>{municipality.sections.map(s=><path key={s.id} d={path(s.geometry)} className={s.id===sectionId?"active":""}/>)}</svg>}
const electionLabel=(type:string)=>type.replace("PARLAMENTO_EUROPEO","Europeas").replace("MUNICIPALES","Municipales").replace("ANDALUZAS","Andaluzas").replace("CONGRESO","Congreso");

const detailModules:Record<string,React.LazyExoticComponent<ComponentType>>={
 municipality:lazy(async()=>({default:(await import("./MunicipalityStory")).MunicipalityStory})),
 evolution:lazy(async()=>({default:(await import("./TerritorialEvolutionStory")).TerritorialEvolutionStory})),
 profile:lazy(async()=>({default:(await import("./MunicipalProfileStory")).MunicipalProfileStory})),
 electoral:lazy(async()=>({default:(await import("./ElectoralDiagnosisStory")).ElectoralDiagnosisStory})),
 territories:lazy(async()=>({default:(await import("./TerritorialProfilesStory")).TerritorialProfilesStory})),
 typologies:lazy(async()=>({default:(await import("./TerritorialTypologyStory")).TerritorialTypologyStory})),
 relationships:lazy(async()=>({default:(await import("./TerritorialRelationshipsStory")).TerritorialRelationshipsStory})),
};
function Explore({target,label}:{target:keyof typeof detailModules;label:string}){const [open,setOpen]=useState(false);const Detail=detailModules[target];return <div className="exec-explore"><button onClick={()=>setOpen(v=>!v)} aria-expanded={open}>{open?"Cerrar análisis":label} <ArrowRight/></button>{open?<div className="exec-depth"><Suspense fallback={<p>Preparando análisis verificado…</p>}><Detail/></Suspense></div>:null}</div>}
function Scene({id,kicker,title,children,dark=false}:{id:string;kicker:string;title:string;children:React.ReactNode;dark?:boolean}){return <section id={id} className={`exec-scene ${dark?"exec-scene--dark":""}`}><header><p>{kicker}</p><h2>{title}</h2></header>{children}</section>}

export function ExecutiveHeader(){const [open,setOpen]=useState(false);return <><header className="exec-header"><a href="#cover">soctrace <span>· Mijas 2027</span></a><nav><button onClick={()=>setOpen(true)}><Menu/> Explorar</button><a href="#your-campaign">Tu campaña</a></nav></header>{open?<div className="exec-drawer" role="dialog" aria-modal="true" aria-label="Explorar el informe"><button className="exec-drawer-close" onClick={()=>setOpen(false)}><X/> Cerrar</button><div><section><p>Mijas</p><a href="#snapshot" onClick={()=>setOpen(false)}>Radiografía</a><a href="#growth" onClick={()=>setOpen(false)}>Evolución</a><a href="#built" onClick={()=>setOpen(false)}>Vivienda y territorio</a></section><section><p>Electoral</p><a href="#electoral" onClick={()=>setOpen(false)}>Resultados</a><a href="#participation" onClick={()=>setOpen(false)}>Participación</a><a href="#change" onClick={()=>setOpen(false)}>Evolución electoral</a><a href="#relationships" onClick={()=>setOpen(false)}>Relaciones</a></section><section><p>Territorios</p><a href="#territories" onClick={()=>setOpen(false)}>Perfiles</a><a href="#typologies" onClick={()=>setOpen(false)}>Tipologías</a></section><section><p>Producto</p><a href="#your-campaign" onClick={()=>setOpen(false)}>Tu campaña</a><a href="#methodology-annex" onClick={()=>setOpen(false)}>Metodología</a></section></div></div>:null}</>}

export function ExecutiveCampaign(){const [territory,setTerritory]=useState(territoryIndex[0].sectionId);const current=territoryIndex.find(x=>x.sectionId===territory)!;const metric=current.metrics;return <>
 <section id="cover" className="exec-cover"><div className="exec-cover-brand">soctrace</div><div><p>Campaign Intelligence</p><h1>Mijas 2027</h1><h2>Entender Mijas antes de decidir la campaña.</h2><span>Inteligencia territorial y electoral para comprender cómo cambia el municipio, cómo se comporta electoralmente y qué diferencias existen entre sus territorios.</span><small>94.320 residentes · 41 secciones electorales actuales · 12 procesos electorales analizados</small><a href="#snapshot">Descubrir Mijas <ArrowRight/></a></div></section>
 <Scene id="snapshot" kicker="Mijas en 60 segundos" title="Mijas no es un único municipio."><p className="exec-lead">El crecimiento, la edad, la renta, la forma urbana, la participación y el voto dibujan realidades territoriales diferentes.</p><div className="exec-map-layout"><MijasMap/><div className="exec-metrics"><article><strong>+7.764</strong><span>residentes · +8,97 % desde 2021</span></article><article><strong>23,6 %</strong><span>de la población en cinco secciones</span></article><article><strong>38,0 → 69,4 %</strong><span>rango territorial de participación</span></article></div></div><blockquote>Para competir en Mijas primero hay que entender sus diferencias.</blockquote><Explore target="municipality" label="Explorar el territorio →"/></Scene>
 <Scene id="growth" kicker="01 · Escala municipal" title="Mijas crece con fuerza." dark><div className="exec-growth"><span>86.556</span><i>→</i><strong>94.320</strong></div><p className="exec-lead">+7.764 residentes · +8,97 %. Último dato disponible · 2025.</p><div className="exec-bars" aria-label="Evolución de población 2021 a 2025">{[86556,88313,91407,92941,94320].map((v,i)=><div key={v}><i style={{height:`${45+(v-86556)/220}px`}}/><span>{2021+i}</span><b>{num.format(v)}</b></div>)}</div><div className="exec-population-pair"><div className="exec-population-map"><h3>Población por sección</h3><p>La población municipal crece, pero no se distribuye de manera uniforme entre las secciones.</p><MijasMap mode="population" className="exec-map--population"/><div className="exec-sequential-legend" aria-label="Leyenda de población"><span>Menor población</span><i/><span>Mayor población</span></div><strong>Las cinco secciones con mayor población concentran 21.752 residentes.</strong></div><div className="exec-population-map"><h3>Variación de población</h3><p>Cambio reciente comparable sobre la misma geometría y con idéntico encuadre.</p><MijasMap mode="variation" className="exec-map--variation"/><div className="exec-category-legend"><span><i style={{background:"#d86f76"}}/>Descenso</span><span><i style={{background:"#d8c58a"}}/>Estable</span><span><i style={{background:"#53b69a"}}/>Crecimiento</span></div></div></div><Explore target="evolution" label="Explorar la evolución territorial →"/></Scene>
 <Scene id="typologies" kicker="Tipologías" title="Cinco Mijas diferentes."><p className="exec-lead">37 secciones. Cinco patrones territoriales compartidos.</p><div className="exec-summary-strip"><strong>5 <span>familias</span></strong><strong>37 <span>secciones</span></strong><strong>92.211 <span>residentes</span></strong></div><div className="exec-report-map"><MijasMap mode="typology"/><div className="exec-map-legend">{clusters.map((c,i)=><span key={c.cluster_id}><i style={{background:colors[i]}}/>{c.cluster_id}</span>)}</div></div><div className="exec-type-list">{clusters.map((c,i)=><article key={c.cluster_id} style={{borderColor:colors[i]}}><h3>{typologies.groups[c.cluster_id].title}</h3><p>{c.section_count} secciones · {num.format(c.population_represented)} residentes</p><span>{typologies.groups[c.cluster_id].subtitle}</span></article>)}</div><div id="structure-vote" className="exec-subscene"><h3>Territorios socialmente parecidos no siempre votan igual.</h3><p>Estructura territorial, comportamiento electoral y lectura integrada muestran facetas distintas del mismo municipio.</p><div className="exec-map-trio"><figure><figcaption>Estructura</figcaption><MijasMap mode="typology"/></figure><figure><figcaption>Electoral</figcaption><MijasMap mode="electoral"/></figure><figure><figcaption>Integrada</figcaption><MijasMap mode="typology"/></figure></div></div><div id="representative-territories" className="exec-subscene"><h3>Territorios representativos.</h3><div className="exec-representatives">{clusters.map((c,i)=><article key={c.cluster_id}><LocatorMap sectionId={(c as Cluster&{representative_section:string}).representative_section}/><small>{c.cluster_id}</small><h4>{(c as Cluster&{representative_name:string}).representative_name.replace(/^Sección \d+ · /,"")}</h4><p>{typologies.groups[c.cluster_id].subtitle}</p><i style={{background:colors[i]}}/></article>)}</div></div><Explore target="typologies" label="Explorar tipologías →"/></Scene>
 <Scene id="electoral" kicker="Municipales 2023" title="Mijas tampoco vota igual." dark><div id="election-chronology" className="exec-subscene"><h3>Doce elecciones. Distintas fotografías.</h3><div className="exec-chronology">{[...electoral.electionInventory].sort((a,b)=>a.election_date.localeCompare(b.election_date)).map(e=>{const s=electoral.municipalSummaries.find(x=>x.election_id===e.election_id)!;return <article key={e.election_id}><time>{e.election_date.slice(0,4)}</time><div><strong>{electionLabel(e.election_type)}</strong><span>{s.winner} · participación {s.participation_pct.toFixed(1).replace(".",",")} % · margen {s.margin_pct_points.toFixed(2).replace(".",",")} pp</span></div></article>})}</div></div><div id="municipal-2023-summary" className="exec-municipal-summary"><p>02 · Municipales 2023</p><h3>PSOE-A y PP quedaron separados por solo 2,03 puntos en el conjunto de Mijas.</h3><div className="exec-municipal-rule"/><p className="exec-lead">El resultado municipal fue ajustado en el conjunto del municipio, aunque la distancia entre primera y segunda fuerza cambia significativamente según la sección.</p><div className="exec-electoral-metrics"><article><strong>33,98 %</strong><span>PSOE-A · ganador municipal</span></article><article><strong>PP</strong><span>segunda fuerza</span></article><article><strong>2,03 puntos</strong><span>margen entre primera y segunda fuerza</span></article><article><strong>51,82 %</strong><span>participación</span></article></div><div className="exec-margin-contrast"><h4>La diferencia entre las dos primeras fuerzas no fue igual en todas las secciones.</h4><div><article><strong>0,15</strong><span>puntos</span><b>Las Cañadas</b></article><i aria-hidden="true"/><article><strong>22,04</strong><span>puntos</span><b>Riviera Norte</b></article></div></div><div className="exec-municipal-map"><h4>Ganador por sección</h4><MijasMap mode="electoral" className="exec-map--municipal-2023"/><div className="exec-party-legend"><span><i style={{background:party["PSOE-A"]}}/>PSOE-A</span><span><i style={{background:party.PP}}/>PP</span><span><i style={{background:"#788694"}}/>Otras / empate</span></div></div><a className="exec-flat-link" href="#change">Explorar el mapa electoral →</a></div></Scene>
 <Scene id="change" kicker="Comparación armonizada" title="Entre 2019 y 2023, siete territorios cambiaron de ganador."><div id="municipal-map-change" className="exec-map-change"><p className="exec-lead">Para comparar ambas elecciones, soctrace agrupa las secciones en 28 territorios equivalentes y evita comparar directamente límites censales que cambiaron entre convocatorias.</p><div className="exec-family-pair"><FamilyElectionMap electionId={4} label="Municipales 2019"/><FamilyElectionMap electionId={1} label="Municipales 2023"/></div><div className="exec-election-shift"><article><span>2019</span><strong>PP 16 · PSOE 11 · Cs 1</strong></article><ArrowRight/><article><span>2023</span><strong>PP 10 · PSOE 18 · Cs 0</strong></article></div><strong className="exec-change-total">7 de 28 territorios cambiaron de ganador.</strong><h3>Cambió de ganador</h3><ul className="exec-changed">{electoral.sectionWinnerHistory.filter(x=>x.election_id===1&&x.winner_changed).map(x=>{const before=electoral.sectionWinnerHistory.find(y=>y.election_id===4&&y.family_id===x.family_id);const name=electoral.sectionProfiles.find(y=>y.seccion_id===x.family_id)?.display_name.replace(/^Sección \d+ · /,"")||x.family_id;return <li key={x.family_id}><strong>{name}</strong><span>{before?.winner} → {x.winner}</span></li>})}</ul><p className="exec-change-conclusion">El 25 % de los territorios comparables cambió de fuerza ganadora.</p><details className="exec-comparison-method"><summary>Cómo hacemos comparables 2019 y 2023 →</summary><p>La comparación utiliza 28 familias territoriales armonizadas para considerar los cambios de límites censales. Es una comparación descriptiva de ganadores agregados y no identifica transferencias individuales de voto.</p></details></div></Scene>
 <Scene id="participation" kicker="Participación y movilización" title="En unas zonas vota casi 7 de cada 10 electores. En otras, menos de 4." dark><div className="exec-participation"><article><span>Mijas Este</span><strong>69,42 %</strong><i style={{width:"69.42%"}}/></article><article><span>Torrenueva</span><strong>38,00 %</strong><i style={{width:"38%"}}/></article></div><p className="exec-lead">La participación tampoco se distribuye de forma uniforme. Una campaña también debe entender dónde y cuándo se moviliza el electorado.</p><Explore target="electoral" label="Explorar participación →"/></Scene>
 <Scene id="relationships" kicker="Relaciones" title="Lo intuitivo no siempre es cierto."><p className="exec-lead">Cruzar variables permite distinguir relaciones consistentes de explicaciones que desaparecen al incorporar el contexto territorial.</p><div className="exec-relations"><article><span>Relación territorial consistente</span><h3>Estudios superiores ↔ voto</h3><p>Las secciones con más estudios superiores mostraron diferencias consistentes en las cuotas de PP y PSOE.</p></article><article><span>Relación condicionada</span><h3>Renta ↔ voto municipal</h3><p>La relación aparente se debilita al considerar educación, edad y densidad.</p></article><article><span>Evidencia débil</span><h3>Edad o crecimiento ↔ participación</h3><p>La evidencia disponible no sostiene una explicación simple.</p></article></div><blockquote>Una campaña basada en datos también consiste en descartar explicaciones que los datos no sostienen.</blockquote><Explore target="relationships" label="Explorar relaciones →"/></Scene>
 <Scene id="built" kicker="Vivienda y territorio" title="La forma de vivir también dibuja Mijas." dark><div className="exec-metrics"><article><strong>27.964</strong><span>parcelas analizadas</span></article><article><strong>84.593</strong><span>partes de edificio</span></article><article><strong>Compacta ↔ dispersa</strong><span>intensidad construida y parcela media</span></article></div><Explore target="profile" label="Explorar vivienda y territorio →"/></Scene>
 <Scene id="territories" kicker="Explora cualquier territorio" title="37 territorios. 37 historias diferentes."><p className="exec-lead">Toca cualquier sección para conocerla.</p><div className="exec-territory"><MijasMap selected={territory} onSelect={setTerritory}/><aside aria-live="polite"><small>Perfil territorial</small><h3>{current.displayName.replace(/^Sección \d+ · /,"")}</h3><dl><div><dt>Población</dt><dd>{num.format(Number(metric.population))}</dd></div><div><dt>Crecimiento reciente</dt><dd>{Number(metric.growth_percent_2023_2024).toFixed(2).replace(".",",")} %</dd></div><div><dt>Edad media</dt><dd>{Number(metric.average_age).toFixed(1).replace(".",",")} años</dd></div><div><dt>Participación municipal</dt><dd>{Number(metric.participation_municipal_2023).toFixed(2).replace(".",",")} %</dd></div><div><dt>Ganador</dt><dd>{String(metric.winner_municipal_2023)}</dd></div><div><dt>Margen</dt><dd>{Number(metric.margin_municipal_2023).toFixed(2).replace(".",",")} pp</dd></div></dl></aside></div><Explore target="territories" label="Ver perfil completo →"/></Scene>
 <section id="your-campaign" className="exec-campaign"><p>Hasta aquí hemos analizado Mijas.</p><h2>Falta una variable.<br/><em>Tu candidatura.</em></h2><div className="exec-questions"><strong>¿Dónde debes competir?</strong><strong>¿Dónde puedes crecer?</strong><strong>¿Dónde necesitas movilizar?</strong></div><p>La respuesta cambia para cada candidatura.</p><div className="exec-preview"><small>Ejemplo de módulo personalizado</small><h3>TU CAMPAÑA · MIJAS 2027</h3>{["Consolidar","Competir","Movilizar","Investigar"].map(x=><span key={x}>{x}</span>)}</div><details><summary>Todo lo que podemos responder para tu candidatura →</summary><p>Incorporamos tu punto de partida, objetivos, candidato, organización y recursos para convertir la evidencia territorial en decisiones.</p></details></section>
 <section id="final-cta" className="exec-final"><p>Mijas ya está analizada.</p><h2>Ahora diseñemos tu estrategia.</h2><a href="/request-demo?context=Mijas%202027%20Campaign%20Intelligence">Diseñar mi campaña con soctrace</a><a className="secondary" href="/request-demo?context=Mijas%202027%20Campaign%20Intelligence">Solicitar una sesión estratégica</a></section>
 <section id="methodology-annex" className="exec-method"><h2>Fuentes</h2><strong>{campaignSourceLine}</strong><p>Los indicadores combinan fuentes públicas oficiales, armonización territorial y análisis propios de soctrace. Las comparaciones históricas usan territorios equivalentes; los resultados electorales conservan la identidad y el año de cada elección.</p><button onClick={()=>window.print()}><Printer/> Imprimir / Guardar PDF</button></section>
 </>}
