import { ArrowRight } from "lucide-react";
import { useMemo } from "react";
import electoralJson from "@/features/campaigns/data/generated/mijas-2027-block-b-electoral-diagnosis.json";
import victoryJson from "@/features/campaigns/data/generated/mijas-2027-psoe-2023-victory-client.json";

type Point=[number,number];type Geometry={type:"MultiPolygon";coordinates:Point[][][]};
type Winner={election_id:number;family_id:string;winner:string;winner_changed:boolean|null};
type Electoral={sectionWinnerHistory:Winner[];municipalHarmonisation:{familyGeometries:{familyId:string;geometry:Geometry}[]}};
type Transition={family_id:string;display_name:string;transition:string};
const electoral=electoralJson as unknown as Electoral;
const transitions=(victoryJson as unknown as {transitions:Transition[]}).transitions;
const party:Record<string,string>={PP:"#5295ee",PSOE:"#ed6680",CS:"#e6b84a"};
const name=(value:string)=>value.replace(/^Sección \d+ · /,"").replace("Barrio de las flores Oeste","Barrio de las Flores Oeste").replace("Doña Ermita / Pol San Rafael","Doña Ermita / Pol. San Rafael");

function projector(geometries:Geometry[]){const pts=geometries.flatMap(g=>g.coordinates.flatMap(p=>p.flatMap(r=>r))),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),w=900,h=620,p=18,s=Math.min((w-2*p)/(maxX-minX),(h-2*p)/(maxY-minY));return(g:Geometry)=>g.coordinates.map(poly=>poly.map(r=>r.map(([x,y],i)=>`${i?"L":"M"}${(p+(x-minX)*s).toFixed(1)} ${(h-p-(y-minY)*s).toFixed(1)}`).join(" ")+" Z").join(" ")).join(" ")}

function FamilyElectionMap({electionId,label}:{electionId:number;label:string}){const geos=electoral.municipalHarmonisation.familyGeometries,path=useMemo(()=>projector(geos.map(x=>x.geometry)),[geos]),rows=electoral.sectionWinnerHistory.filter(x=>x.election_id===electionId);return <figure className={`exec-family-map exec-family-map--${electionId}`}><figcaption>{label}</figcaption><svg viewBox="0 0 900 620" preserveAspectRatio="xMidYMid meet" role="img" aria-label={`Mapa electoral armonizado de ${label}`}>{geos.map(g=>{const row=rows.find(x=>x.family_id===g.familyId),changed=electoral.sectionWinnerHistory.find(x=>x.election_id===1&&x.family_id===g.familyId)?.winner_changed;return <path key={g.familyId} d={path(g.geometry)} fill={party[row?.winner||""]||"#788694"} className={changed?"changed":"stable"}><title>{g.familyId} · {row?.winner}</title></path>})}</svg><div className="exec-comparison-legend"><span><i style={{background:party.PP}}/>PP</span><span><i style={{background:party.PSOE}}/>PSOE</span><span><i style={{background:party.CS}}/>Cs</span><span><i className="outline"/>Cambió</span></div></figure>}

export function HarmonizedElectionComparison(){return <div id="municipal-map-change" className="exec-map-change"><p className="exec-lead">Para comparar ambas elecciones, soctrace agrupa las secciones en 28 territorios equivalentes y evita comparar directamente límites censales que cambiaron entre convocatorias.</p><div className="exec-family-pair"><FamilyElectionMap electionId={4} label="Municipales 2019"/><FamilyElectionMap electionId={1} label="Municipales 2023"/></div><p className="exec-election-shift-legend">Total de secciones en las que cada partido fue fuerza más votada</p><div className="exec-election-shift"><article><span>2019</span><strong>PP 16 · PSOE 11 · Cs 1</strong></article><ArrowRight/><article><span>2023</span><strong>PP 10 · PSOE 18 · Cs 0</strong></article></div><strong className="exec-change-total">7 de 28 territorios cambiaron de ganador.</strong><h3>Cambió de ganador</h3><ul className="exec-changed">{transitions.map(item=><li key={item.family_id}><strong>{name(item.display_name)}</strong><span>{item.transition.replace("CS","Cs")}</span></li>)}</ul><p className="exec-change-conclusion">El 25 % de los territorios comparables cambió de fuerza ganadora.</p><details className="exec-comparison-method"><summary>Cómo hacemos comparables 2019 y 2023 →</summary><p>La comparación utiliza 28 familias territoriales armonizadas para considerar los cambios de límites censales. Es una comparación descriptiva de ganadores agregados y no identifica transferencias individuales de voto.</p></details></div>}
