import { useMemo } from "react";
import clientJson from "@/features/campaigns/data/generated/mijas-2027-psoe-2023-victory-client.json";
import municipalityJson from "@/features/campaigns/data/generated/mijas-2027-municipality.json";
import { HarmonizedElectionComparison } from "./HarmonizedElectionComparison";
import "./PsoeVictoryStory.css";

type Point=[number,number];type Geometry={type:"MultiPolygon";coordinates:Point[][][]};
type Geo={id:string;label:string;geometry:Geometry};
type GeoRow={section_id:string;display_name:string;psoe_minus_pp_pp:number};
type ChangeRow={family_id:string;display_name:string;winner_2019:string;winner_2023:string};
type RankRow={family_id:string;display_name:string;psoe_delta_pp:number;pp_delta_pp:number};
type Client={municipal:Record<string,number>;geography:{counts:{PSOE:number;PP:number;tie:number};rows:GeoRow[];psoeTop:GeoRow[];ppTop:GeoRow[];closest:GeoRow};transitions:{family_id:string;display_name:string;transition:string;spatial_assignment_confidence_pct:number}[];familyWinners:ChangeRow[];partyLeadership:Record<string,Record<string,number>>;partyChange:{party:string;share_2019_pct:number;share_2023_pct:number;delta_pp:number}[];pmp:{municipal_share_pct:number;valid_2019_predecessor:boolean};csRelationships:{x:string;y:string;pearson:number}[];participation:Record<string,{mean_delta_pp:number}>;participationPsoe:{pearson:number};context:{context_variable:string;electoral_variable:string;pearson:number}[];firstTimeVoterVerdict:string;rankings:{psoeGains:RankRow[];ppLosses:RankRow[]}};
const client=clientJson as Client;
const municipality=municipalityJson as unknown as {sections:Geo[]};
const one=new Intl.NumberFormat("es-ES",{minimumFractionDigits:1,maximumFractionDigits:1});
const two=new Intl.NumberFormat("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2});
const integer=new Intl.NumberFormat("es-ES");
const short=(name:string)=>name.replace(/^Sección \d+ · /,"").replace("Barrio de los ríos","Barrio de los Ríos").replace("Barrio de las flores Oeste","Barrio de las Flores Oeste").replace("Doña Ermita / Pol San Rafael","Doña Ermita / Pol. San Rafael");
function projector(items:Geometry[]){const pts=items.flatMap(g=>g.coordinates.flatMap(p=>p.flatMap(r=>r))),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),w=960,h=650,p=25,s=Math.min((w-2*p)/(maxX-minX),(h-2*p)/(maxY-minY)),ox=(w-(maxX-minX)*s)/2,oy=(h-(maxY-minY)*s)/2,point=([x,y]:Point)=>[ox+(x-minX)*s,h-oy-(y-minY)*s];return(g:Geometry)=>g.coordinates.map(poly=>poly.map(r=>r.map((q,i)=>`${i?"L":"M"}${point(q).map(v=>v.toFixed(1)).join(" ")}`).join(" ")+" Z").join(" ")).join(" ")}
function advantageColor(value:number){const strength=Math.min(1,Math.abs(value)/22.1),light=92-strength*48;return value>=0?`hsl(347 68% ${light}%)`:`hsl(215 72% ${light}%)`}
function GeographyMap(){const path=useMemo(()=>projector(municipality.sections.map(x=>x.geometry)),[]),rows=new Map(client.geography.rows.map(x=>[x.section_id,x]));return <svg className="victory-geo-map" viewBox="0 0 960 650" role="img" aria-label="Diferencia territorial entre la proporción de voto de PSOE y PP en 2023">{municipality.sections.map(g=>{const row=rows.get(g.id)!;return <path key={g.id} data-section-id={g.id} data-margin={row.psoe_minus_pp_pp} d={path(g.geometry)} fill={advantageColor(row.psoe_minus_pp_pp)}><title>{row.display_name} · {row.psoe_minus_pp_pp>=0?"PSOE":"PP"} +{one.format(Math.abs(row.psoe_minus_pp_pp))} pp</title></path>})}</svg>}
function Slide({number,title,headline,children,className="",id}:{number:string;title:string;headline:string;children:React.ReactNode;className?:string;id?:string}){return <section id={id} className={`victory-slide ${className}`} data-victory-module={number} aria-labelledby={`victory-${number}`}><header><p>{number} · {title}</p><h3 id={`victory-${number}`}>{headline}</h3></header>{children}</section>}
const relationship=(target:string)=>client.csRelationships.find(x=>x.y===target)!;
const contextLabel:Record<string,string>={higher_studies_context_pct:"Estudios superiores ↔ cambio PP",population_context:"Población ↔ cambio PP",income_individual_context:"Renta ↔ cambio PP",under_30_context_pct:"Menores de 30 ↔ cambio PP"};
export function PsoeVictoryStory(){const parties=Object.fromEntries(client.partyChange.map(x=>[x.party,x]));const both=new Set(client.rankings.psoeGains.map(x=>x.family_id).filter(id=>client.rankings.ppLosses.some(y=>y.family_id===id)));return <div className="psoe-victory-story">
 <section className="victory-intro"><p>MUNICIPALES 2023</p><h2>Claves territoriales de la victoria del PSOE.</h2><span>El PSOE fue la fuerza más votada en Mijas por solo 512 votos. El resultado municipal fue muy ajustado, pero el camino hasta esa victoria no fue igual en todo el territorio.</span><strong>Ocho claves para entender qué cambió entre 2019 y 2023.</strong></section>
 <Slide number="01" title="El resultado" headline="El PSOE ganó Mijas por solo 512 votos." className="victory-result"><div className="victory-result-kpis"><article><span>PSOE-A</span><strong>{one.format(client.municipal.psoe_share_pct)} %</strong></article><article><span>PP</span><strong>{one.format(client.municipal.pp_share_pct)} %</strong></article><article><span>Diferencia</span><strong>{integer.format(client.municipal.psoe_minus_pp_votes)} votos</strong><small>{one.format(client.municipal.psoe_minus_pp_pp)} pp</small></article></div><div className="victory-bars"><div><span>PSOE-A</span><i style={{width:`${client.municipal.psoe_share_pct}%`}}/><b>{one.format(client.municipal.psoe_share_pct)}</b></div><div><span>PP</span><i style={{width:`${client.municipal.pp_share_pct}%`}}/><b>{one.format(client.municipal.pp_share_pct)}</b></div></div><p className="victory-secondary">Participación · {one.format(client.municipal.participation_pct)} %</p><p className="victory-conclusion">Fue la elección municipal más ajustada de las tres comparables de 2015, 2019 y 2023.</p></Slide>
 <Slide number="02" title="La geografía de la victoria" headline="El equilibrio municipal escondía diferencias territoriales mucho mayores." className="victory-geography"><div className="victory-balance"><article><strong>{client.geography.counts.PSOE} de 37</strong><span>PSOE por delante del PP</span></article><article><strong>{client.geography.counts.PP} de 37</strong><span>PP por delante del PSOE</span></article></div><figure><GeographyMap/><figcaption><span>Ventaja PSOE</span><i/><span>0</span><i/><span>Ventaja PP</span></figcaption></figure><div className="victory-examples"><article><span>Mayor ventaja PSOE</span><strong>{short(client.geography.psoeTop[0].display_name)}</strong><b>+{one.format(client.geography.psoeTop[0].psoe_minus_pp_pp)} pp</b></article><article><span>Resultado próximo</span><strong>{short(client.geography.closest.display_name)}</strong><b>{one.format(Math.abs(client.geography.closest.psoe_minus_pp_pp))} pp</b></article><article><span>Mayor ventaja PP</span><strong>{short(client.geography.ppTop[0].display_name)}</strong><b>+{one.format(Math.abs(client.geography.ppTop[0].psoe_minus_pp_pp))} pp</b></article></div><details><summary>Ver territorios con mayores ventajas</summary><div className="victory-two-lists"><ol>{client.geography.psoeTop.slice(0,5).map(x=><li key={x.section_id}><span>{short(x.display_name)}</span><b>+{one.format(x.psoe_minus_pp_pp)} pp</b></li>)}</ol><ol>{client.geography.ppTop.slice(0,5).map(x=><li key={x.section_id}><span>{short(x.display_name)}</span><b>+{one.format(Math.abs(x.psoe_minus_pp_pp))} pp</b></li>)}</ol></div></details><p className="victory-conclusion">La ventaja socialista no fue homogénea: convivieron territorios claramente favorables al PSOE con otros donde el PP dominó con amplitud.</p></Slide>
 <Slide id="change" number="03" title="El mapa electoral cambió" headline="Entre 2019 y 2023, siete territorios cambiaron de ganador." className="victory-change"><HarmonizedElectionComparison/></Slide>
 <Slide number="04" title="El tablero político se reordenó" headline="El crecimiento del PSOE convivió con el desplome de Ciudadanos y el avance de otras fuerzas." className="victory-parties"><div className="victory-party-grid">{["PSOE","PP","CS","VOX"].map(p=><article key={p}><span>{p==="CS"?"Ciudadanos":p}</span><strong>{one.format(parties[p].share_2019_pct)} % → {one.format(parties[p].share_2023_pct)} %</strong><b>{parties[p].delta_pp>=0?"+":""}{one.format(parties[p].delta_pp)} pp</b></article>)}<article><span>Por Mi Pueblo</span><strong>{one.format(client.pmp.municipal_share_pct)} % en 2023</strong><small>Sin predecesor comparable validado en 2019</small></article></div><h4>Qué dice la evidencia territorial</h4><p>La caída de Ciudadanos coincidió territorialmente más con aumentos del PP y VOX que con aumentos del PSOE.</p><div className="victory-correlations"><span>Cs ↔ PP <b>r = {two.format(relationship("pp_delta_pp").pearson)}</b></span><span>Cs ↔ VOX <b>r = {two.format(relationship("vox_delta_pp").pearson)}</b></span><span>Cs ↔ PSOE <b>r = {two.format(relationship("psoe_delta_pp").pearson)}</b></span></div><p>Cuanto mayor fue la caída territorial de Ciudadanos, mayor tendió a ser el crecimiento del PP y VOX. La relación con el crecimiento socialista fue mucho más débil.</p><aside>Esto no permite identificar transferencias individuales de voto.</aside></Slide>
 <Slide number="05" title="¿La participación explicó la victoria?" headline="Los datos no apoyan una explicación basada principalmente en la movilización." className="victory-turnout"><div className="victory-turnout-grid">{[["Territorios liderados por PSOE","psoe_won_2023"],["Territorios liderados por PP","pp_won_2023"],["Territorios que cambiaron","winner_changed"],["Territorios sin cambio","winner_unchanged"]].map(([label,key])=><article key={key}><span>{label}</span><strong>{one.format(client.participation[key].mean_delta_pp)} pp</strong><small>Δ participación 2019→2023</small></article>)}</div><div className="victory-null"><span>Participación ↔ avance PSOE</span><strong>Relación prácticamente nula</strong><small>Pearson {client.participationPsoe.pearson.toFixed(3).replace(".",",")}</small></div><p>El avance socialista no se concentró claramente en los territorios donde aumentó la participación.</p><p className="victory-conclusion">No aparece una relación territorial clara. La victoria no puede explicarse de forma simple como un efecto de mayor movilización.</p></Slide>
 <Slide number="06" title="Mientras cambiaba el voto, también cambiaba Mijas" headline="El contexto territorial importa, pero no permite atribuir causas individuales." className="victory-context"><div className="victory-context-grid">{client.context.filter(x=>contextLabel[x.context_variable]).map(x=><article key={x.context_variable}><span>{contextLabel[x.context_variable]}</span><strong>r ≈ {x.pearson>=0?"+":""}{one.format(x.pearson)}</strong><small>Relación territorial {Math.abs(x.pearson)>=.7?"fuerte":"descriptiva"}</small></article>)}</div><p>Los territorios con mayor presencia de estudios superiores muestran, en este análisis contextual, mayores incrementos del PP. Esto describe territorios, no el voto individual de sus residentes.</p></Slide>
 <Slide number="07" title="Dónde cambió más el equilibrio" headline="Los mayores avances socialistas se concentraron en territorios concretos." className="victory-rankings"><div className="victory-rank-columns"><article><h4>Mayores avances PSOE</h4><ol>{client.rankings.psoeGains.slice(0,5).map(x=><li key={x.family_id} className={both.has(x.family_id)?"both":""}><span>{short(x.display_name)}</span><b>+{one.format(x.psoe_delta_pp)} pp</b></li>)}</ol><details><summary>Ver puestos 6–10</summary><ol start={6}>{client.rankings.psoeGains.slice(5).map(x=><li key={x.family_id}><span>{short(x.display_name)}</span><b>+{one.format(x.psoe_delta_pp)} pp</b></li>)}</ol></details></article><article><h4>Mayores retrocesos PP</h4><ol>{client.rankings.ppLosses.slice(0,5).map(x=><li key={x.family_id} className={both.has(x.family_id)?"both":""}><span>{short(x.display_name)}</span><b>{one.format(x.pp_delta_pp)} pp</b></li>)}</ol><details><summary>Ver puestos 6–10</summary><ol start={6}>{client.rankings.ppLosses.slice(5).map(x=><li key={x.family_id}><span>{short(x.display_name)}</span><b>{one.format(x.pp_delta_pp)} pp</b></li>)}</ol></details></article></div><p className="victory-shared"><i/> Aparece en ambas clasificaciones</p><p className="victory-conclusion">El nuevo equilibrio municipal se construyó de forma desigual: algunos territorios combinan avance socialista y retroceso popular, mientras en otros ambos partidos evolucionaron de forma diferente.</p></Slide>
 <Slide number="08" title="Qué sabemos — y qué no" headline="La victoria del PSOE no tuvo una única explicación." className="victory-synthesis"><div className="victory-evidence-levels"><article><h4>Comprobado</h4><ul><li>PSOE ganó por 512 votos y 2,0 pp.</li><li>PSOE por delante del PP en 24 de 37 secciones.</li><li>7 de 28 territorios cambiaron ganador.</li><li>PSOE pasó 11 → 18; PP pasó 16 → 10.</li><li>Ciudadanos cayó 14,8 pp.</li></ul></article><article><h4>Indicios territoriales</h4><ul><li>La caída de Cs coincide más con avances PP/VOX que PSOE.</li><li>Por Mi Pueblo fue más fuerte donde el balance PSOE–PP era más favorable al PSOE.</li><li>Ciertos perfiles territoriales se relacionan con cambios del PP.</li></ul><small>Relaciones territoriales; no causalidad.</small></article><article><h4>No podemos afirmar</h4><ul><li>Que votantes de Cs se trasladaron a una candidatura concreta.</li><li>Que la participación causó la victoria.</li><li>Que jóvenes o primeros votantes dieron la victoria al PSOE.</li><li>Que VOX dividió causalmente el voto de la derecha.</li><li>Que Por Mi Pueblo causó un resultado concreto.</li></ul></article></div><p className="victory-closing-line">Entender una elección no consiste en encontrar una causa única, sino en localizar qué cambió, dónde cambió y qué patrones se repiten.</p></Slide>
 </div>}
