import { ArrowLeft, ArrowRight, CheckCircle2, CircleAlert, GitCompareArrows, Info, MapPin, Search, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import indexJson from "@/features/campaigns/data/generated/block-c/territory-index.json";
import geometriesJson from "@/features/campaigns/data/generated/block-c/territory-geometries.json";
import typologiesJson from "@/features/campaigns/data/generated/mijas-2027-block-d-territorial-clusters.json";
import { mijas2027TypologyPresentation } from "@/features/campaigns/data/mijas-2027-typologies";
import "./TerritorialProfilesStory.css";

type Point=[number,number]; type Geometry={type:"MultiPolygon";coordinates:Point[][][]};
declare global { interface String { replaceAll(searchValue:string,replaceValue:string):string } }
type IndexItem={sectionId:string;displayName:string;metrics:Record<string,number|string|null>;completeness:{completeness_pct:number;evidence_confidence:string;direct_comparison_metrics:number;harmonised_metrics:number;provisional_metrics:number;missing_metrics:number;warnings:string};crosswalk:Record<string,string|number|null>};
type Geo={sectionId:string;displayName:string;geometry:Geometry;centroid:{type:"Point";coordinates:Point}};
type Detail={sectionId:string;displayName:string;identity:{geometry:Geometry};metrics:Record<string,number|string|null>;completeness:IndexItem["completeness"];factualSummary:{order:number;statement:string;metricKeys:string}[];municipal2023PartyResults:{canonical_party:string;votes:number;vote_share_pct:number;municipal_difference_pp:number;section_rank:number;winner_tie:boolean;principal_candidacy:boolean}[];demographicHistory:Record<string,string|number|null>|null;municipalHistory:Record<string,string|number|null>[];current2026:(Record<string,unknown>&{seccion_id:string;display_name:string;winner:string;winner_share_pct:number;participation_pct:number;margin_pct_points:number;accessibility_score:number|null;recorded_service_count:number;comparison_status:string;newly_created:boolean;principalPartyResults:{canonical_party:string;vote_share_pct:number}[]})[];rankings:{metric:string;rank_desc:number;percentile_pct:number;quintile:number}[]};

const index=indexJson as IndexItem[],geometries=geometriesJson as Geo[];
const typologyMembership=new Map((typologiesJson.territoryMembership as {seccion_id:string;cluster_id:string;transitional:boolean;stability:number}[]).map(item=>[item.seccion_id,item]));
const profileModules=import.meta.glob("../data/generated/block-c/territory-profiles/*.json",{import:"default"}) as Record<string,()=>Promise<Detail>>;
const integer=new Intl.NumberFormat("es-ES"),decimal=new Intl.NumberFormat("es-ES",{minimumFractionDigits:2,maximumFractionDigits:4}),eur=new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR",maximumFractionDigits:0});
const parties:Record<string,string>={PP:"#4b8ee8",PSOE:"#ef6078","PSOE-A":"#ef6078",VOX:"#55bd8a",CS:"#eab94d",Cs:"#eab94d",OTHER:"#81909a",LOCAL:"#a579c5"};
const partyColor=(value:string)=>parties[value]??"#81909a";
const metrics={population:["Población 2024","population"],growth:["Cambio 2023–2024","growth_percent_2023_2024"],density:["Densidad 2024","density_per_km2"],age:["Edad media 2024","average_age"],young:["Menores de 30","under_30_pct"],older:["Mayores de 65","over_65_pct"],income:["Renta individual 2023","income_individual"],household:["Renta del hogar 2023","income_household"],built:["Intensidad construida","building_intensity"],participation:["Participación municipal","participation_municipal_2023"],margin:["Margen municipal","margin_municipal_2023"],winner:["Ganador municipal","winner_municipal_2023"]} as const;
type Layer=keyof typeof metrics;
function projector(items:Geometry[]){const pts=items.flatMap(g=>g.coordinates.flatMap(p=>p.flatMap(r=>r))),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),w=960,h=660,p=24,s=Math.min((w-2*p)/(maxX-minX),(h-2*p)/(maxY-minY)),ox=(w-(maxX-minX)*s)/2,oy=(h-(maxY-minY)*s)/2,point=([x,y]:Point)=>[ox+(x-minX)*s,h-oy-(y-minY)*s];return(g:Geometry)=>g.coordinates.map(poly=>poly.map(r=>r.map((q,i)=>`${i?"L":"M"}${point(q).map(v=>v.toFixed(1)).join(" ")}`).join(" ")+" Z").join(" ")).join(" ")}
const n=(v:unknown)=>typeof v==="number"?v:0;
function position(value:number,difference:number,unit:string){const threshold=unit==="€"?500:unit==="años"?.35:.75;return <span className={`territory-position ${Math.abs(difference)<=threshold?"near":difference>0?"above":"below"}`}>{Math.abs(difference)<=threshold?"Cerca de la referencia municipal":difference>0?"Por encima de la referencia municipal":"Por debajo de la referencia municipal"} · {difference>0?"+":""}{decimal.format(difference)} {unit}</span>}
function EvidenceBadge({kind}:{kind:"direct"|"harmonised"|"provisional"|"framing"}){return <span className={`territory-evidence-badge ${kind}`}>{kind==="direct"?<CheckCircle2/>:<Info/>}{kind==="direct"?"Dato directo verificado":kind==="harmonised"?"Historia armonizada":kind==="provisional"?"Evidencia provisional 2026":"Marco consultivo"}</span>}
function Figure({label,value,note}:{label:string;value:string;note?:React.ReactNode}){return <article className="territory-figure"><span>{label}</span><strong>{value}</strong>{note}</article>}

function TerritoryMap({selected,layer,onSelect}:{selected:string;layer:Layer;onSelect:(id:string)=>void}){const path=useMemo(()=>projector(geometries.map(g=>g.geometry)),[]),key=metrics[layer][1],values=index.map(i=>n(i.metrics[key])).filter(Number.isFinite),min=Math.min(...values),max=Math.max(...values);const fill=(item:IndexItem)=>{const value=item.metrics[key];if(layer==="winner")return partyColor(String(value));const t=(n(value)-min)/Math.max(max-min,.0001);return `hsl(${205-160*t} 62% ${24+31*t}%)`};return <svg className="territory-map-svg" viewBox="0 0 960 660" aria-label={`Mapa de 37 secciones: ${metrics[layer][0]}`}>{geometries.map(geo=>{const item=index.find(i=>i.sectionId===geo.sectionId)!;return <path key={geo.sectionId} d={path(geo.geometry)} fill={fill(item)} className={selected===geo.sectionId?"selected":""} role="button" tabIndex={0} aria-label={`${item.displayName}: ${item.metrics[key]}`} onClick={()=>onSelect(item.sectionId)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();onSelect(item.sectionId)}}}><title>{item.displayName}</title></path>})}</svg>}

export function TerritorialProfilesStory(){
 const initial=new URLSearchParams(location.search).get("territory");const [selected,setSelected]=useState(index.some(i=>i.sectionId===initial)?initial!:index[0].sectionId),[layer,setLayer]=useState<Layer>("population"),[query,setQuery]=useState(""),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(false),[compare,setCompare]=useState<string[]>([]),[expanded,setExpanded]=useState(false);
 const item=index.find(i=>i.sectionId===selected)!,filtered=index.filter(i=>(i.sectionId+" "+i.displayName).toLowerCase().includes(query.toLowerCase())),positionIndex=index.findIndex(i=>i.sectionId===selected);
 useEffect(()=>{let active=true;setDetail(null);setError(false);const loader=profileModules[`../data/generated/block-c/territory-profiles/${selected}.json`];loader?.().then(value=>{if(active)setDetail(value)}).catch(()=>{if(active)setError(true)});const url=new URL(location.href);url.searchParams.set("territory",selected);history.replaceState(history.state,"",url);return()=>{active=false}},[selected]);
 const choose=(id:string)=>{setSelected(id);document.querySelector(".territory-profile-header")?.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"})};
 const toggleCompare=(id:string)=>setCompare(current=>current.includes(id)?current.filter(x=>x!==id):current.length<2?[...current,id]:[current[1],id]);
 return <section id="target-profiles" className="territorial-profiles" aria-labelledby="territorial-title">
  {typologyMembership.get(item.sectionId)?<aside className="territory-typology-context"><a className="territory-typology-badge" href="#territorial-typologies"><i style={{background:mijas2027TypologyPresentation.palette[Number(typologyMembership.get(item.sectionId)!.cluster_id.replace("Group ",""))-1]}}/><span><b>{typologyMembership.get(item.sectionId)!.cluster_id}</b>{mijas2027TypologyPresentation.groups[typologyMembership.get(item.sectionId)!.cluster_id as keyof typeof mijas2027TypologyPresentation.groups].title}</span>{typologyMembership.get(item.sectionId)!.transitional?<em>Asignación transicional</em>:null}<small>Agrupación analítica con estabilidad moderada · ver método y límites</small></a></aside>:null}
  <header className="territory-opening"><div><EvidenceBadge kind="framing"/><p>10 · Perfiles territoriales</p><h2 id="territorial-title">Perfiles<br/>territoriales</h2><blockquote>“Cada sección combina una realidad demográfica, urbana y electoral diferente.”</blockquote><span>Explorar el municipio territorio a territorio permite comprender diferencias que desaparecen en los promedios municipales.</span><div className="territory-trust"><strong>37</strong> secciones oficiales <i/> 30 con cobertura alta <i/> 7 con cobertura moderada <i/> 88,10–92,86% de completitud</div></div></header>
  <section className="territory-explorer" aria-labelledby="territory-explorer-title"><header><p>01 · Un municipio, 37 perfiles</p><h3 id="territory-explorer-title">Los promedios municipales ocultan diferencias territoriales.</h3></header><div className="territory-explorer-tools"><label><Search/>Buscar sección<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre o ID"/></label><label>Capa de evidencia<select value={layer} onChange={e=>setLayer(e.target.value as Layer)}><optgroup label="Población"><option value="population">Población 2024</option><option value="growth">Cambio 2023–2024</option><option value="density">Densidad 2024</option></optgroup><optgroup label="Demografía"><option value="age">Edad media</option><option value="young">Menores de 30</option><option value="older">Mayores de 65</option></optgroup><optgroup label="Contexto económico"><option value="income">Renta individual</option><option value="household">Renta del hogar</option></optgroup><optgroup label="Forma urbana"><option value="built">Intensidad construida</option></optgroup><optgroup label="Comportamiento electoral"><option value="participation">Participación municipal</option><option value="margin">Margen municipal</option><option value="winner">Ganador municipal</option></optgroup></select></label></div><div className="territory-explorer-layout"><div className="territory-map-frame"><TerritoryMap selected={selected} layer={layer} onSelect={choose}/><div className="territory-map-caption"><span>{metrics[layer][0]}</span><strong><MapPin/>{item.displayName}</strong><button onClick={()=>choose(selected)}>Abrir perfil</button></div></div><aside className="territory-search-results" aria-label="Territorios"><span>{filtered.length} secciones</span>{filtered.map(result=><button key={result.sectionId} className={selected===result.sectionId?"active":""} onClick={()=>choose(result.sectionId)}><small>{result.sectionId.slice(-3)}</small>{result.displayName.replace(/^Sección \d+ · /,"")}</button>)}</aside></div></section>
  <section className="territory-profile-header" aria-live="polite"><div><EvidenceBadge kind="direct"/><p>{item.sectionId}</p><h3>{item.displayName.replace(/^Sección \d+ · /,"")}</h3><div className="territory-profile-nav"><button onClick={()=>choose(index[(positionIndex+36)%37].sectionId)}><ArrowLeft/>Anterior</button><button onClick={()=>document.querySelector(".territory-explorer")?.scrollIntoView()}><MapPin/>Volver al mapa</button><button onClick={()=>choose(index[(positionIndex+1)%37].sectionId)}>Siguiente<ArrowRight/></button></div></div><div className="territory-locator"><TerritoryMap selected={selected} layer="population" onSelect={choose}/></div>{error?<div className="territory-load-error"><CircleAlert/><strong>El detalle no está disponible.</strong><span>El índice territorial y el mapa siguen operativos.</span></div>:!detail?<div className="territory-loader">Preparando perfil verificado…</div>:<><div className="territory-essential"><Figure label="Población · 2024" value={integer.format(n(detail.metrics.population))}/><Figure label="Cambio · 2023–2024" value={`${n(detail.metrics.growth_absolute_2023_2024)>0?"+":""}${integer.format(n(detail.metrics.growth_absolute_2023_2024))}`}/><Figure label="Renta individual · 2023" value={eur.format(n(detail.metrics.income_individual))}/><Figure label="Municipales · 2023" value={String(detail.metrics.winner_municipal_2023)} note={<small>Margen {decimal.format(n(detail.metrics.margin_municipal_2023))} pp</small>}/></div><div className="territory-facts">{detail.factualSummary.slice(0,expanded?8:4).map(f=><p key={f.order}>{f.statement}</p>)}<button onClick={()=>setExpanded(x=>!x)}>{expanded?"Mostrar síntesis breve":"Ver las 8 afirmaciones verificadas"}</button></div></>}</section>
  {detail?<>
  <section className="territory-scene territory-demographic"><header><p>02 · Quién vive aquí</p><h3>Composición demográfica.</h3><EvidenceBadge kind="direct"/></header><div className="territory-composition"><Figure label="Población 2024" value={integer.format(n(detail.metrics.population))} note={<small>{decimal.format(n(detail.metrics.municipal_population_share_pct))}% del municipio</small>}/><Figure label="Edad media" value={`${decimal.format(n(detail.metrics.average_age))} años`} note={position(n(detail.metrics.average_age),n(detail.metrics.average_age_difference_years),"años")}/><Figure label="Menores de 30" value={`${decimal.format(n(detail.metrics.under_30_pct))}%`} note={position(n(detail.metrics.under_30_pct),n(detail.metrics.under_30_difference_pp),"pp")}/><Figure label="65 años o más" value={`${decimal.format(n(detail.metrics.over_65_pct))}%`} note={position(n(detail.metrics.over_65_pct),n(detail.metrics.over_65_difference_pp),"pp")}/></div><div className="sex-balance"><span>Hombres {decimal.format(n(detail.metrics.men_pct))}%</span><i><b style={{width:`${n(detail.metrics.men_pct)}%`}}/></i><span>Mujeres {decimal.format(n(detail.metrics.women_pct))}%</span></div><p className="territory-note">Indicador de dependencia: {decimal.format(n(detail.metrics.dependency_ratio))}. Descripción demográfica; no infiere estructura familiar ni estilo de vida.</p></section>
  <section className="territory-scene territory-change"><header><p>03 · Cómo cambia</p><h3>Dos escalas temporales,<br/>dos geografías.</h3></header><div className="change-direct"><EvidenceBadge kind="direct"/><Figure label="Población 2023" value={integer.format(n(detail.metrics.population)-n(detail.metrics.growth_absolute_2023_2024))}/><b>→</b><Figure label="Población 2024" value={integer.format(n(detail.metrics.population))}/><strong>{n(detail.metrics.growth_absolute_2023_2024)>0?"+":""}{integer.format(n(detail.metrics.growth_absolute_2023_2024))} · {decimal.format(n(detail.metrics.growth_percent_2023_2024))}%</strong></div><div className="change-harmonised"><EvidenceBadge kind="harmonised"/><h4>Familia territorial {detail.metrics.demographic_family_id}</h4>{detail.demographicHistory?<><p>{integer.format(n(detail.demographicHistory.population_2021))} en 2021 → {integer.format(n(detail.demographicHistory.population_2025))} en 2025</p><strong>{String(detail.demographicHistory.trend_classification).replaceAll("_"," ")}</strong><small>Contribución al crecimiento municipal: {decimal.format(n(detail.demographicHistory.contribution_to_municipal_growth_pct))}%</small></>:<p>Historia armonizada no disponible.</p>}<footer>La evolución de largo plazo se calcula mediante familias territoriales estables para considerar divisiones de secciones.</footer></div></section>
  <section className="territory-scene territory-economic"><header><p>04 · Posición económica</p><h3>Renta individual y del hogar no son la misma medida.</h3></header><div><Figure label="Renta individual · 2023" value={eur.format(n(detail.metrics.income_individual))} note={position(n(detail.metrics.income_individual),n(detail.metrics.individual_income_difference_eur),"€")}/><Figure label="Renta del hogar · 2023" value={eur.format(n(detail.metrics.income_household))} note={position(n(detail.metrics.income_household),n(detail.metrics.household_income_difference_eur),"€")}/></div><p>Posición municipal: rango {detail.metrics.income_rank} de 37 · quintil {detail.metrics.income_quintile}. Cambio individual 2019–2023: {n(detail.metrics.individual_change_2019_2023)>0?"+":""}{eur.format(n(detail.metrics.individual_change_2019_2023))}.</p></section>
  <section className="territory-scene territory-built"><header><p>05 · Forma urbana</p><h3>De la forma compacta a la dispersa.</h3></header><div className="built-continuum"><span>Compacta</span><i><b style={{left:`${Math.min(96,Math.max(4,n(detail.metrics.urban_intensity_index)))}%`}}/></i><span>Dispersa</span></div><div><Figure label="Huella construida" value={`${integer.format(n(detail.metrics.built_footprint_m2))} m²`}/><Figure label="Intensidad construida" value={decimal.format(n(detail.metrics.building_intensity))}/><Figure label="Parcela media" value={`${integer.format(n(detail.metrics.average_plot_size_m2))} m²`}/><Figure label="Densidad parcelaria" value={`${decimal.format(n(detail.metrics.parcel_density_per_km2))}/km²`}/><Figure label="Partes de edificio" value={integer.format(n(detail.metrics.num_building_parts))}/></div><p>Se omiten precio de mercado, valor catastral, ratio e indicador inmobiliario porque eran referencias municipales repetidas y no variación territorial.</p></section>
  <section className="territory-scene territory-electoral-profile"><header><p>06 · Municipales 2023</p><h3>Resultado electoral de la sección.</h3></header><div className="electoral-profile-lead"><strong style={{color:partyColor(String(detail.metrics.winner_municipal_2023))}}>{String(detail.metrics.winner_municipal_2023)}</strong><span>{decimal.format(n(detail.metrics.winner_share_municipal_2023))}% · margen {decimal.format(n(detail.metrics.margin_municipal_2023))} pp</span>{detail.municipal2023PartyResults.some(r=>r.winner_tie)?<b>Empate en primera posición</b>:null}</div><div className="electoral-profile-facts"><span>Censo {integer.format(n(detail.metrics.census_municipal_2023))}</span><span>Participación {decimal.format(n(detail.metrics.participation_municipal_2023))}%</span><span>Abstención {decimal.format(n(detail.metrics.abstention_municipal_2023))}%</span><span>Segunda: {String(detail.metrics.runner_up_municipal_2023)} · {decimal.format(n(detail.metrics.runner_up_share_municipal_2023))}%</span><span>Tercera: {String(detail.metrics.third_party_municipal_2023)}</span><span>Fragmentación {decimal.format(n(detail.metrics.fragmentation_municipal_2023))}</span></div><div className="party-bars">{detail.municipal2023PartyResults.filter(r=>r.principal_candidacy).map(r=><article key={r.canonical_party}><span><i style={{background:partyColor(r.canonical_party)}}/>{r.canonical_party}</span><b style={{width:`${r.vote_share_pct}%`,background:partyColor(r.canonical_party)}}/><strong>{decimal.format(r.vote_share_pct)}%</strong><small>{r.municipal_difference_pp>0?"+":""}{decimal.format(r.municipal_difference_pp)} pp frente al municipio</small></article>)}</div></section>
  <section className="territory-scene territory-election-context"><header><p>07 · Tipos de elección</p><h3>El resultado puede cambiar según la elección.</h3></header><div>{[["Municipales 2023","municipal_2023"],["Congreso 2023","congress_2023"],["Europeas 2024","european_2024"]].map(([label,key],idx)=><article key={key}><span>{label}</span><strong style={{color:partyColor(String(detail.metrics[`winner_${key}`]))}}>{String(detail.metrics[`winner_${key}`])}</strong><small>{decimal.format(n(detail.metrics[`winner_share_${key}`]))}% · participación {decimal.format(n(detail.metrics[`participation_${key}`]))}% · margen {decimal.format(n(detail.metrics[`margin_${key}`]))} pp</small>{idx?<em>{String(detail.metrics[`winner_${key}`])===String(detail.metrics.winner_municipal_2023)?"Mismo ganador que en Municipales":"Ganador distinto a Municipales"} · cambio participación {decimal.format(n(detail.metrics[`participation_${key}`])-n(detail.metrics.participation_municipal_2023))} pp</em>:null}</article>)}</div></section>
  <section className="territory-scene territory-history"><header><EvidenceBadge kind="harmonised"/><p>08 · Historia municipal</p><h3>Familia territorial {String(detail.metrics.municipal_electoral_family_id).slice(-3)}.</h3></header>{["2907001012","2907001029"].includes(String(detail.metrics.municipal_electoral_family_id))?<p className="limited-warning"><CircleAlert/>Comparabilidad limitada: el solape de correspondencia es inferior al 90%.</p>:null}<div>{detail.municipalHistory.map(row=><article key={String(row.election_date)}><span>{String(row.election_date).slice(0,4)}</span><strong style={{color:partyColor(String(row.winner))}}>{String(row.winner)}</strong><small>Participación {decimal.format(n(row.participation_pct))}% · margen {decimal.format(n(row.margin_pct_points))} pp</small>{row.pedersen_index_pct_points!=null?<em>Movimiento agregado {decimal.format(n(row.pedersen_index_pct_points))} pp</em>:<em>Primera referencia de la serie</em>}</article>)}</div><p>No estima transferencias de votantes individuales. Confianza mínima de asignación: {decimal.format(n(detail.municipalHistory[0]?.minimum_assignment_confidence_pct))}%.</p></section>
  <section className="territory-scene territory-current"><header><EvidenceBadge kind="provisional"/><p>09 · Contexto actual</p><h3>Geografía provisional 2026.</h3></header>{detail.current2026.length?detail.current2026.map(current=><article key={current.seccion_id}><header><span>{current.seccion_id} · {current.display_name}</span><small>{current.comparison_status}</small></header><div><Figure label="Andaluzas 2026" value={`${current.winner} · ${decimal.format(current.winner_share_pct)}%`} note={<small>Participación {decimal.format(current.participation_pct)}% · margen {decimal.format(current.margin_pct_points)} pp</small>}/><Figure label="Accesibilidad OSM" value={current.accessibility_score==null?"No disponible":decimal.format(current.accessibility_score)} note={<small>{current.recorded_service_count} servicios registrados</small>}/></div><details><summary>Distancias y evidencia provisional</summary><p>Los valores ausentes permanecen como “no disponible”; nunca se convierten en cero.</p></details></article>):<p>No existe una correspondencia 2026 cargada para este perfil.</p>}</section>
  <section className="territory-scene territory-evidence"><header><p>10 · Evidencia y límites</p><h3>{decimal.format(detail.completeness.completeness_pct)}% de cobertura.</h3></header><div><Figure label="Métricas directas" value={String(detail.completeness.direct_comparison_metrics)}/><Figure label="Métricas armonizadas" value={String(detail.completeness.harmonised_metrics)}/><Figure label="Métricas provisionales" value={String(detail.completeness.provisional_metrics)}/><Figure label="Métricas ausentes" value={String(detail.completeness.missing_metrics)}/></div><details><summary><Info/>Fuentes, cálculo y comparabilidad</summary><p>Años fuente: 2019–2026. Geografía primaria: 37 secciones oficiales 2023/2024. Historia: familias armonizadas. Contexto actual: 41 secciones provisionales 2026.</p><p>{detail.completeness.warnings}</p></details></section>
  <section className="territory-scene territory-comparison"><header><p>11 · Comparar dos secciones</p><h3>Diferencias factuales,<br/>sin jerarquías.</h3></header><div className="comparison-picker">{index.map(option=><button key={option.sectionId} className={compare.includes(option.sectionId)?"active":""} onClick={()=>toggleCompare(option.sectionId)} aria-pressed={compare.includes(option.sectionId)}>{option.sectionId.slice(-3)}</button>)}</div><p>{compare.length}/2 territorios seleccionados. Solo perfiles de la misma geografía primaria.</p>{compare.length===2?<div className="comparison-table">{["population","growth_percent_2023_2024","density_per_km2","average_age","under_30_pct","over_65_pct","income_individual","income_household","building_intensity","average_plot_size_m2","participation_municipal_2023","margin_municipal_2023"].map(key=><article key={key}><span>{key.replaceAll("_"," ")}</span>{compare.map(id=><strong key={id}>{decimal.format(n(index.find(i=>i.sectionId===id)?.metrics[key]))}</strong>)}</article>)}</div>:<div className="comparison-empty"><GitCompareArrows/>Selecciona dos secciones para activar la comparación.</div>}</section>
  </>:null}
  <footer className="territory-closing"><p>12 · Volver al municipio</p><h3>Comprender Mijas exige moverse entre la escala municipal y el detalle territorial.</h3><span>Ninguna sección representa por sí sola al conjunto del municipio.</span><a href="#territorial-typologies">Continuar a tipologías territoriales <ArrowRight/></a></footer>
 </section>
}
