import { ArrowRight, ExternalLink, Info, Link2, MapPin } from "lucide-react";
import { useMemo,useState } from "react";
import projectionJson from "@/features/campaigns/data/generated/mijas-2027-block-e-client.json";
import geometriesJson from "@/features/campaigns/data/generated/block-c/territory-geometries.json";
import { mijas2027TypologyPresentation as typologyConfig } from "@/features/campaigns/data/mijas-2027-typologies";
import "./TerritorialRelationshipsStory.css";

type Point=[number,number];type Geometry={type:"MultiPolygon";coordinates:Point[][][]};type Geo={sectionId:string;displayName:string;geometry:Geometry};
type Relationship={relationship_id:string;x:string;y:string;election_context:string;geography:string;n:number;pearson:number;spearman:number;ci_low:number;ci_high:number;adjusted_p_value:number;influential_observation_result:string;robustness_category:string;evidence_status:string};
type Partial={relationship_id:string;x:string;y:string;controls:string;n:number;raw_correlation:number;partial_correlation:number;interpretation_status:string};
type SectionPoint={sectionId:string;displayName:string;[key:string]:string|number};
type Model={model:string;adjusted_r_squared:number;loocv_rmse:number;r_squared:number;predictor_count:number};
type Consistency={relationship:string;municipal_pearson:number;congress_pearson:number;european_pearson:number;classification:string};
type Historical={x:string;y:string;pearson:number;spearman:number;n:number;geography:string;sensitivity_status:string;crosswalk:string};
type Typology={variable:string;group:string;n:number;mean:number;stddev:number;mean_without_transitional:number;small_sample_warning:boolean};
type Residual={section_id:string;display_name:string;main_model:string;observed:number;fitted:number;standardized_residual:number;cooks_distance:number};
type Edge={source:string;target:string;direction:string;magnitude:number;election:string};
type Projection={metadata:Record<string,unknown>;geographyDefinitions:Record<string,string>;selectedRelationships:Relationship[];selectedPartialRelationships:Partial[];sectionPoints:SectionPoint[];models:Model[];electionConsistency:Consistency[];historicalSensitivity:Historical[];typologyComparisons:Typology[];residualTerritories:Residual[];robustnessCounts:Record<string,number>;representativeFindings:{relationship_id:string;plain_factual_statement:string;status:string;pearson:number}[];reducedRelationshipNetwork:Edge[];limitations:string[]};
const data=projectionJson as unknown as Projection,geometries=geometriesJson as unknown as Geo[];
const decimal=new Intl.NumberFormat("es-ES",{minimumFractionDigits:2,maximumFractionDigits:4});
const labels:Record<string,string>={pct_higher_studies:"Estudios superiores",income_individual:"Renta individual",density_per_km2:"Densidad",average_age:"Edad media",under_30_pct:"Menores de 30",over_65_pct:"Mayores de 65",growth_percent_2023_2024:"Crecimiento",participation_municipal_2023:"Participación municipal",share_pp:"PP",share_psoe:"PSOE",share_vox:"VOX",margin_municipal_2023:"Margen",fragmentation_municipal_2023:"Fragmentación",congress_2023_share_pp:"PP · Congreso",congress_2023_share_psoe:"PSOE · Congreso",european_2024_share_pp:"PP · Europeas",european_2024_share_psoe:"PSOE · Europeas"};
const partyColor=(key:string)=>key.includes("psoe")?"#e85d75":key.includes("pp")?"#4e8bd7":"#738c91";
const profileHref=(id:string)=>`?territory=${id}#target-profiles`;
const relationship=(id:string)=>data.selectedRelationships.find(x=>x.relationship_id===id)!;
const partial=(id:string)=>data.selectedPartialRelationships.find(x=>x.relationship_id===id)!;
const model=(id:string)=>data.models.find(x=>x.model===id)!;
function Evidence({item}:{item:Relationship}){return <details className="relations-evidence"><summary>Ver evidencia</summary><p>{item.geography} · n={item.n} · Pearson {item.pearson.toFixed(4)} · Spearman {item.spearman.toFixed(4)} · intervalo [{item.ci_low.toFixed(4)}, {item.ci_high.toFixed(4)}] · FDR {item.adjusted_p_value.toFixed(4)} · influencia {item.influential_observation_result} · {item.robustness_category} · {item.evidence_status}.</p></details>}
function Scatter({xKey,yKey,onSelect,selected}:{xKey:string;yKey:string;onSelect:(id:string)=>void;selected:string}){const values=data.sectionPoints,xy=values.map(p=>[Number(p[xKey]),Number(p[yKey])] as Point),xs=xy.map(x=>x[0]),ys=xy.map(x=>x[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),sx=(x:number)=>55+(x-minX)/(maxX-minX||1)*590,sy=(y:number)=>400-(y-minY)/(maxY-minY||1)*330;const mx=xs.reduce((a,b)=>a+b)/xs.length,my=ys.reduce((a,b)=>a+b)/ys.length,slope=xs.reduce((s,x,i)=>s+(x-mx)*(ys[i]-my),0)/xs.reduce((s,x)=>s+(x-mx)**2,0),line=[minX,maxX].map(x=>[sx(x),sy(my+slope*(x-mx))]);return <svg className="relations-scatter" viewBox="0 0 700 450" aria-label={`${labels[xKey]} y ${labels[yKey]}`}><line x1="55" y1="400" x2="655" y2="400"/><line x1="55" y1="45" x2="55" y2="400"/><line className="trend" x1={line[0][0]} y1={line[0][1]} x2={line[1][0]} y2={line[1][1]}/><text x="350" y="438">{labels[xKey]}</text><text x="15" y="30">{labels[yKey]}</text>{values.map((p,i)=><circle key={p.sectionId} cx={sx(xs[i])} cy={sy(ys[i])} r={selected===p.sectionId?8:5} fill={partyColor(yKey)} className={selected===p.sectionId?"selected":""} role="button" tabIndex={0} aria-label={`${p.displayName}: ${decimal.format(xs[i])}, ${decimal.format(ys[i])}`} onClick={()=>onSelect(p.sectionId)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onSelect(p.sectionId)}}}><title>{p.displayName}</title></circle>)}</svg>}
function RawAdjusted({title,raw,adjusted}:{title:string;raw:number;adjusted:number}){const scale=(v:number)=>50+v*42;return <article className="raw-adjusted"><h4>{title}</h4><div><span>Relación territorial directa</span><i><b style={{left:`${scale(raw)}%`}}/></i><strong>{raw.toFixed(4)}</strong></div><div><span>Ajustada por contexto</span><i><b style={{left:`${scale(adjusted)}%`}}/></i><strong>{adjusted.toFixed(4)}</strong></div></article>}
function Projector(){return useMemo(()=>{const pts=geometries.flatMap(g=>g.geometry.coordinates.flatMap(p=>p.flatMap(r=>r))),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),a=Math.min(...xs),b=Math.max(...xs),c=Math.min(...ys),d=Math.max(...ys),s=Math.min(850/(b-a),560/(d-c));return(g:Geometry)=>g.coordinates.map(poly=>poly.map(r=>r.map((q,i)=>`${i?"L":"M"}${50+(q[0]-a)*s} ${610-(q[1]-c)*s}`).join(" ")+" Z").join(" ")).join(" ")},[])}
function ResidualMap({selected,onSelect}:{selected:string;onSelect:(id:string)=>void}){const path=Projector(),highlight=new Set(data.residualTerritories.map(x=>x.section_id));return <svg className="relations-map" viewBox="0 0 960 660" aria-label="Territorios con residuos destacados">{geometries.map(g=><path key={g.sectionId} d={path(g.geometry)} fill={highlight.has(g.sectionId)?"#d8905f":"#26373d"} className={selected===g.sectionId?"selected":""} role={highlight.has(g.sectionId)?"button":undefined} tabIndex={highlight.has(g.sectionId)?0:undefined} onClick={()=>highlight.has(g.sectionId)&&onSelect(g.sectionId)}><title>{g.displayName}</title></path>)}</svg>}

export function TerritorialRelationshipsStory(){const [selectedPoint,setSelectedPoint]=useState(data.sectionPoints[0].sectionId),[party,setParty]=useState<"pp"|"psoe">("pp"),[residual,setResidual]=useState("2907001002"),[edge,setEdge]=useState(0);const selected=data.sectionPoints.find(x=>x.sectionId===selectedPoint)!;const residualRows=data.residualTerritories.filter(x=>x.section_id===residual);const chosenEdge=data.reducedRelationshipNetwork[edge];const typologyVars=['participation_municipal_2023','share_pp','share_psoe'];return <section id="territorial-relationships" className="territorial-relationships" aria-labelledby="relations-title">
 <header className="relations-opening"><div><span>08 · Relaciones territoriales</span><h2 id="relations-title">Coincidir no significa explicar.</h2><p>Algunas variables se mueven juntas entre territorios, pero muchas relaciones aparentes cambian cuando se considera el contexto territorial más amplio.</p><aside><Info/>Estas relaciones describen secciones, no votantes individuales.</aside></div></header>
 <section className="relations-scene relations-causality"><header><span>01 · Asociación y explicación</span><h3>Dos variables pueden moverse juntas sin que una cause la otra.</h3></header><div><article><b>1</b><h4>Asociación observada</h4><p>Dos medidas varían de forma parecida entre secciones.</p></article><article><b>2</b><h4>Relación ajustada</h4><p>Se incorporan variables contextuales seleccionadas.</p></article><article className="not-established"><b>3</b><h4>Explicación causal</h4><p>No queda establecida por este análisis territorial.</p></article></div></section>
 <section className="relations-scene relations-education"><header><span>02 · La relación más consistente</span><h3>Estudios superiores y distribución territorial del voto.</h3><p>Las secciones con mayor presencia de estudios superiores tendieron a mostrar más apoyo al PP y menos al PSOE, especialmente en elecciones generales y europeas.</p></header><div className="relations-party-tabs"><button className={party==="pp"?"active":""} onClick={()=>setParty("pp")}>PP</button><button className={party==="psoe"?"active":""} onClick={()=>setParty("psoe")}>PSOE</button></div><div className="relations-scatter-layout"><Scatter xKey="pct_higher_studies" yKey={party==="pp"?"share_pp":"share_psoe"} selected={selectedPoint} onSelect={setSelectedPoint}/><aside><strong>{selected.displayName}</strong><a href={profileHref(selected.sectionId)}>Abrir perfil territorial <ExternalLink/></a>{["municipal_2023","congress_2023","european_2024"].map(context=>{const suffix=context==="municipal_2023"?`share_${party}`:`${context.replace("municipal_2023","")}_share_${party}`;const item=data.selectedRelationships.find(x=>x.x==="pct_higher_studies"&&x.y===suffix)!;return <article key={context}><span>{context.replaceAll("_"," ")}</span><b>{item.pearson.toFixed(4)}</b></article>})}<p>Ajustada en Municipales: {partial(`P_pct_higher_studies__share_${party}`).partial_correlation.toFixed(4)}</p><Evidence item={relationship(`R_pct_higher_studies__share_${party}`)}/></aside></div></section>
 <section className="relations-scene relations-controls"><header><span>03 · Antes y después de los controles</span><h3>Una relación intensa puede casi desaparecer.</h3><p>Cuando edad, educación, renta y contexto urbano se consideran conjuntamente, algunas relaciones directas se atenúan o cambian de signo. Esto no representa un efecto causal verdadero.</p></header><div className="relations-raw-grid"><RawAdjusted title="Renta ↔ PP" raw={partial('P_income_individual__share_pp').raw_correlation} adjusted={partial('P_income_individual__share_pp').partial_correlation}/><RawAdjusted title="Renta ↔ PSOE" raw={partial('P_income_individual__share_psoe').raw_correlation} adjusted={partial('P_income_individual__share_psoe').partial_correlation}/><RawAdjusted title="Densidad ↔ PP" raw={partial('P_density_per_km2__share_pp').raw_correlation} adjusted={partial('P_density_per_km2__share_pp').partial_correlation}/><RawAdjusted title="Densidad ↔ PSOE" raw={partial('P_density_per_km2__share_psoe').raw_correlation} adjusted={partial('P_density_per_km2__share_psoe').partial_correlation}/></div></section>
 <section className="relations-scene relations-income"><header><span>04 · La elección importa</span><h3>La renta se relaciona de forma distinta según la elección.</h3></header><div>{data.electionConsistency.filter(x=>x.relationship.startsWith('income_individual')).map(row=><article key={row.relationship}><h4>{row.relationship.endsWith('share_pp')?'Renta ↔ PP':'Renta ↔ PSOE'}</h4>{[['Municipales',row.municipal_pearson],['Congreso',row.congress_pearson],['Europeas',row.european_pearson]].map(([label,value])=><div key={String(label)}><span>{label}</span><i><b style={{width:`${Math.abs(Number(value))*100}%`}}/></i><strong>{Number(value).toFixed(4)}</strong></div>)}<small>Dirección consistente; intensidad dependiente del tipo de elección.</small></article>)}</div><p>La asociación municipal directa queda fuertemente condicionada al ajustar por educación, edad y densidad. No se infieren motivaciones.</p></section>
 <section className="relations-scene relations-participation"><header><span>05 · Un resultado negativo central</span><h3>La participación no tiene una explicación territorial simple.</h3></header><div className="relations-model-hero"><strong>{model('participation_municipal_2023').adjusted_r_squared.toFixed(4)}</strong><span>R² ajustado</span><strong>{model('participation_municipal_2023').loocv_rmse.toFixed(4)} pp</strong><span>error fuera de muestra</span></div><div className="relations-weak-list">{[['Edad media','R_average_age__participation_municipal_2023'],['Menores de 30','R_under_30_pct__participation_municipal_2023'],['Mayores de 65','R_over_65_pct__participation_municipal_2023'],['Crecimiento','R_growth_percent_2023_2024__participation_municipal_2023']].map(([label,id])=><article key={id}><span>{label}</span><strong>{relationship(id).pearson.toFixed(4)}</strong><small>relación débil o inconclusa</small></article>)}<article><span>Densidad ajustada</span><strong>{partial('P_density_per_km2__participation_municipal_2023').partial_correlation.toFixed(4)}</strong><small>relación ajustada</small></article></div><p>Edad, crecimiento, renta y densidad no ofrecen por sí solos una explicación fiable de la participación municipal. Investigar causas requeriría evidencia adicional.</p></section>
 <section className="relations-scene relations-models"><header><span>06 · Estructura descriptiva</span><h3>La geografía de PP y PSOE muestra más estructura que la participación.</h3></header><div>{[['PP','share_pp'],['PSOE','share_psoe'],['Participación','participation_municipal_2023']].map(([label,key])=>{const m=model(key);return <article key={key}><span>{label}</span><strong>{m.adjusted_r_squared.toFixed(4)}</strong><small>R² ajustado</small><i><b style={{width:`${Math.max(0,m.adjusted_r_squared)*100}%`}}/></i><p>Error de validación: {m.loocv_rmse.toFixed(4)} pp</p></article>})}</div><aside>Modelos descriptivos: no son pronósticos, no estiman comportamientos individuales y no deben utilizarse como predicciones de voto.</aside></section>
 <section className="relations-scene relations-elections"><header><span>07 · Consistencia electoral</span><h3>Una relación general no se traslada automáticamente a una elección municipal.</h3></header><div>{data.electionConsistency.map(row=><article key={row.relationship}><h4>{row.relationship.split('__').map(x=>labels[x]??x).join(' ↔ ')}</h4><div>{[['M',row.municipal_pearson],['C',row.congress_pearson],['E',row.european_pearson]].map(([e,v])=><span key={String(e)} style={{height:`${20+Math.abs(Number(v))*90}px`}} className={Number(v)<0?'negative':''}><b>{e}</b><small>{Number(v).toFixed(2)}</small></span>)}</div><p>{row.classification==='cross-election consistent'?'Dirección consistente; intensidad variable.':'Débil o dependiente de la elección.'}</p></article>)}</div></section>
 <section className="relations-scene relations-history"><header><span>08 · Cambios 2019–2023</span><h3>Sensibilidad histórica sobre 28 familias armonizadas.</h3><p>Los predictores actuales se promedian dentro de familias históricas. Son asociaciones descriptivas, no evidencia causal contemporánea ni transferencias individuales.</p></header><div>{data.historicalSensitivity.map(item=><article key={item.x+item.y}><span>{labels[item.x]??item.x} ↔ {item.y.replaceAll('_',' ')}</span><strong>{item.pearson.toFixed(4)}</strong><small>Spearman {item.spearman.toFixed(4)} · n={item.n} · {item.sensitivity_status}</small></article>)}</div></section>
 <section className="relations-scene relations-typologies"><header><span>09 · Diferencias entre tipologías</span><h3>Las familias resumen similitudes, no eliminan la diversidad interna.</h3></header><div>{typologyVars.map(variable=><article key={variable}><h4>{labels[variable]}</h4>{data.typologyComparisons.filter(x=>x.variable===variable).map(row=><div key={row.group}><span><i style={{background:typologyConfig.palette[Number(row.group.replace('Group ',''))-1]}}/>{row.group}<small>{typologyConfig.groups[row.group as keyof typeof typologyConfig.groups].title}</small></span><b style={{width:`${row.mean}%`}}/><strong>{row.mean.toFixed(4)}%</strong><em>sin transicionales {row.mean_without_transitional.toFixed(4)}% · dispersión {row.stddev.toFixed(2)}</em></div>)}</article>)}</div><aside>Muestras pequeñas por familia. Las medias no describen votantes homogéneos ni segmentos estratégicos.</aside></section>
 <section className="relations-scene relations-residuals"><header><span>10 · Fuera del patrón general</span><h3>Territorios no resumidos completamente por el modelo municipal.</h3></header><div className="relations-residual-layout"><div><ResidualMap selected={residual} onSelect={setResidual}/></div><aside>{Array.from(new Map(data.residualTerritories.map(x=>[x.section_id,x])).values()).map(item=><button key={item.section_id} onClick={()=>setResidual(item.section_id)} className={residual===item.section_id?'active':''}><MapPin/>{item.display_name}</button>)}<h4>{residualRows[0]?.display_name}</h4>{residualRows.map(row=><article key={row.main_model}><span>{labels[row.main_model]??row.main_model}</span><p>Observado {row.observed.toFixed(3)} · descripción del modelo {row.fitted.toFixed(3)}</p><strong>{row.standardized_residual>0?'Por encima':'Por debajo'} · {row.standardized_residual.toFixed(3)} DE</strong></article>)}<a href={profileHref(residual)}>Abrir perfil completo <ExternalLink/></a></aside></div></section>
 <section className="relations-scene relations-hierarchy"><header><span>11 · Jerarquía de evidencia</span><h3>La solidez se clasifica; nunca se supone.</h3></header><div>{Object.entries(data.robustnessCounts).map(([category,count])=><article key={category} className={category.toLowerCase().replaceAll(' ','-')}><strong>{count}</strong><h4>{category}</h4><p>{category.startsWith('Robust')?'Efecto consistente y resistente a observaciones influyentes; no implica causalidad.':category.startsWith('Conditional')?'Cambia con controles, elección o dominio contextual.':category.startsWith('Election')?'Solo aparece de forma clara en un contexto electoral.':'Efecto pequeño, incierto o sensible.'}</p></article>)}</div><details><summary>Ejemplos trazables</summary>{data.representativeFindings.slice(0,6).map(x=><p key={x.relationship_id}>{x.plain_factual_statement} · r={x.pearson.toFixed(4)} · {x.status}</p>)}</details></section>
 <section className="relations-scene relations-network"><header><span>12 · Red reducida</span><h3>Dieciocho conexiones para leer relaciones, no causas.</h3></header><div className="relations-network-layout"><nav aria-label="Relaciones de la red">{data.reducedRelationshipNetwork.map((item,i)=><button key={i} onClick={()=>setEdge(i)} className={edge===i?'active':''}><i className={item.direction}/>{labels[item.source]??item.source} ↔ {labels[item.target]??item.target}</button>)}</nav><article><Link2/><span>{chosenEdge.election.replaceAll('_',' ')}</span><h4>{labels[chosenEdge.source]??chosenEdge.source}<br/>↔<br/>{labels[chosenEdge.target]??chosenEdge.target}</h4><strong className={chosenEdge.direction}>{chosenEdge.direction==='positive'?'+':'−'}{chosenEdge.magnitude.toFixed(4)}</strong><p>Magnitud descriptiva. El grosor y signo representan asociación, no dirección causal.</p></article></div><details><summary>Alternativa tabular accesible</summary><table><thead><tr><th>Origen</th><th>Resultado</th><th>Signo</th><th>Magnitud</th><th>Elección</th></tr></thead><tbody>{data.reducedRelationshipNetwork.map((x,i)=><tr key={i}><td>{labels[x.source]??x.source}</td><td>{labels[x.target]??x.target}</td><td>{x.direction}</td><td>{x.magnitude.toFixed(4)}</td><td>{x.election}</td></tr>)}</tbody></table></details><p>La red analítica completa de 134 conexiones permanece en la metodología diferida.</p></section>
 <section className="relations-scene relations-myths"><header><span>13 · Lo que la evidencia no sostiene</span><h3>Descartar explicaciones no sustentadas también mejora la inteligencia analítica.</h3></header><div>{[['Edad','No explica por sí sola la participación.'],['Crecimiento','No explica la participación municipal.'],['Densidad','No conserva una relación independiente intensa con PP o PSOE tras los controles.'],['Renta','No funciona como explicación municipal independiente al incorporar contexto.'],['Accesibilidad 2026','Presenta relaciones débiles con la mayoría de resultados y permanece en 41 secciones separadas.'],['Secciones','Una asociación territorial no establece preferencias individuales.']].map(([a,b])=><article key={a}><span>{a}</span><p>{b}</p></article>)}</div></section>
 <footer className="relations-closing"><span>14 · Síntesis consultiva basada en análisis territorial multivariable</span><h3>Los patrones territoriales solo son útiles cuando sus límites permanecen visibles.</h3><p>Educación, renta y contexto electoral muestran estructuras consistentes; la participación y varias relaciones urbanas aparentes requieren más evidencia.</p><a href="#your-campaign">¿Qué significa todo esto para tu candidatura? <ArrowRight/></a></footer>
 </section>}
