import { Info, MapPin } from "lucide-react";
import { useMemo,useState } from "react";
import projectionJson from "@/features/campaigns/data/generated/mijas-2027-block-e-client.json";
import autonomousJson from "@/features/campaigns/data/generated/mijas-2027-autonomous-consistency.json";
import geometriesJson from "@/features/campaigns/data/generated/block-c/territory-geometries.json";
import { mijas2027TypologyPresentation as typologyConfig } from "@/features/campaigns/data/mijas-2027-typologies";
import "./TerritorialRelationshipsStory.css";

type Point=[number,number];type Geometry={type:"MultiPolygon";coordinates:Point[][][]};type Geo={sectionId:string;displayName:string;geometry:Geometry};
type Relationship={relationship_id:string;x:string;y:string;election_context:string;geography:string;n:number;pearson:number;spearman:number;ci_low:number;ci_high:number;adjusted_p_value:number;influential_observation_result:string;robustness_category:string;evidence_status:string};
type Partial={relationship_id:string;x:string;y:string;controls:string;n:number;raw_correlation:number;partial_correlation:number;interpretation_status:string};
type SectionPoint={sectionId:string;displayName:string;[key:string]:string|number};
type Model={model:string;adjusted_r_squared:number;loocv_rmse:number;r_squared:number;predictor_count:number};
type Consistency={relationship:string;municipal_pearson:number;congress_pearson:number;european_pearson:number;classification:string};
type AutonomousConsistency={relationship:string;autonomous_pearson:number;autonomous_spearman:number;n:number;missing:number};
type Historical={x:string;y:string;pearson:number;spearman:number;n:number;geography:string;sensitivity_status:string;crosswalk:string};
type Typology={variable:string;group:string;n:number;mean:number;stddev:number;mean_without_transitional:number;small_sample_warning:boolean};
type Residual={section_id:string;display_name:string;main_model:string;observed:number;fitted:number;standardized_residual:number;cooks_distance:number};
type Projection={metadata:Record<string,unknown>;geographyDefinitions:Record<string,string>;selectedRelationships:Relationship[];selectedPartialRelationships:Partial[];sectionPoints:SectionPoint[];models:Model[];electionConsistency:Consistency[];historicalSensitivity:Historical[];typologyComparisons:Typology[];residualTerritories:Residual[]};
const descriptiveModelCards=[
 {label:"PP",key:"share_pp",percentage:"≈ 62 %",status:"Estructura territorial alta",explanation:"de las diferencias territoriales de apoyo al PP quedan descritas por el modelo territorial.",accent:"pp"},
 {label:"PSOE",key:"share_psoe",percentage:"≈ 54 %",status:"Estructura territorial relevante",explanation:"de las diferencias territoriales de apoyo al PSOE quedan descritas por el modelo territorial.",accent:"psoe"},
 {label:"Participación",key:"participation_municipal_2023",percentage:"≈ 2 %",status:"Estructura territorial débil",explanation:"de las diferencias territoriales de participación quedan descritas por las variables disponibles.",accent:"participation"},
] as const;
const data=projectionJson as unknown as Projection,geometries=geometriesJson as unknown as Geo[];
const autonomousByRelationship=new Map((autonomousJson.relationships as AutonomousConsistency[]).map(row=>[row.relationship,row]));
const decimal=new Intl.NumberFormat("es-ES",{minimumFractionDigits:2,maximumFractionDigits:4});
const twoDecimals=new Intl.NumberFormat("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2});
const labels:Record<string,string>={pct_higher_studies:"Estudios superiores",income_individual:"Renta individual",density_per_km2:"Densidad",average_age:"Edad media",under_30_pct:"Menores de 30",over_65_pct:"Mayores de 65",growth_percent_2023_2024:"Crecimiento",pct_unemployed:"Población desempleada",building_intensity:"Intensidad edificatoria",built_footprint_density:"Densidad de ocupación edificada",individual_change_2019_2023:"Cambio de renta individual 2019–2023",participation_municipal_2023:"Participación municipal",share_pp:"PP",share_psoe:"PSOE",share_vox:"VOX",margin_municipal_2023:"Margen",fragmentation_municipal_2023:"Fragmentación",congress_2023_share_pp:"PP · Congreso",congress_2023_share_psoe:"PSOE · Congreso",european_2024_share_pp:"PP · Europeas",european_2024_share_psoe:"PSOE · Europeas",european_2024_margin:"Margen · Europeas"};
const partyColor=(key:string)=>key.includes("psoe")?"#e85d75":key.includes("pp")?"#4e8bd7":"#738c91";
const relationship=(id:string)=>data.selectedRelationships.find(x=>x.relationship_id===id)!;
const partial=(id:string)=>data.selectedPartialRelationships.find(x=>x.relationship_id===id)!;
const model=(id:string)=>data.models.find(x=>x.model===id)!;
const residualOptions=Array.from(new Map(data.residualTerritories.map(row=>[row.section_id,row])).values()).filter(row=>geometries.some(geo=>geo.sectionId===row.section_id));
const defaultResidualId=residualOptions[0]?.section_id??"";
function Scatter({xKey,yKey,onSelect,selected}:{xKey:string;yKey:string;onSelect:(id:string)=>void;selected:string}){const values=data.sectionPoints,xy=values.map(p=>[Number(p[xKey]),Number(p[yKey])] as Point),xs=xy.map(x=>x[0]),ys=xy.map(x=>x[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),sx=(x:number)=>55+(x-minX)/(maxX-minX||1)*590,sy=(y:number)=>460-(y-minY)/(maxY-minY||1)*390;const mx=xs.reduce((a,b)=>a+b)/xs.length,my=ys.reduce((a,b)=>a+b)/ys.length,slope=xs.reduce((s,x,i)=>s+(x-mx)*(ys[i]-my),0)/xs.reduce((s,x)=>s+(x-mx)**2,0),line=[minX,maxX].map(x=>[sx(x),sy(my+slope*(x-mx))]);return <svg className="relations-scatter" viewBox="0 0 700 520" aria-label={`${labels[xKey]} y ${labels[yKey]}`}><line x1="55" y1="460" x2="655" y2="460"/><line x1="55" y1="45" x2="55" y2="460"/><line className="trend" x1={line[0][0]} y1={line[0][1]} x2={line[1][0]} y2={line[1][1]}/><text x="350" y="505">{labels[xKey]}</text><text x="15" y="30">{labels[yKey]}</text>{values.map((p,i)=><circle key={p.sectionId} cx={sx(xs[i])} cy={sy(ys[i])} r={selected===p.sectionId?8:5} fill={partyColor(yKey)} className={selected===p.sectionId?"selected":""} role="button" tabIndex={0} aria-label={`${p.displayName}: ${decimal.format(xs[i])}, ${decimal.format(ys[i])}`} onClick={()=>onSelect(p.sectionId)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onSelect(p.sectionId)}}}><title>{p.displayName}</title></circle>)}</svg>}
function RawAdjusted({title,raw,adjusted}:{title:string;raw:number;adjusted:number}){const scale=(v:number)=>50+v*42;return <article className="raw-adjusted"><h4>{title}</h4><div><span>Relación territorial directa</span><i><b style={{left:`${scale(raw)}%`}}/></i><strong>{raw.toFixed(4)}</strong></div><div><span>Ajustada por contexto</span><i><b style={{left:`${scale(adjusted)}%`}}/></i><strong>{adjusted.toFixed(4)}</strong></div></article>}
function Projector(){return useMemo(()=>{const pts=geometries.flatMap(g=>g.geometry.coordinates.flatMap(p=>p.flatMap(r=>r))),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),a=Math.min(...xs),b=Math.max(...xs),c=Math.min(...ys),d=Math.max(...ys),s=Math.min(850/(b-a),560/(d-c));return(g:Geometry)=>g.coordinates.map(poly=>poly.map(r=>r.map((q,i)=>`${i?"L":"M"}${50+(q[0]-a)*s} ${610-(q[1]-c)*s}`).join(" ")+" Z").join(" ")).join(" ")},[])}
function ResidualMap({selected,onSelect}:{selected:string;onSelect:(id:string)=>void}){const path=Projector(),selectable=new Set(residualOptions.map(x=>x.section_id)),selectedGeo=geometries.find(g=>g.sectionId===selected);return <figure className="relations-residual-map-frame" data-selected-section={selected}><svg className="relations-map" viewBox="0 0 960 660" preserveAspectRatio="xMidYMid meet" role="img" aria-label={`Mapa localizador de ${selectedGeo?.displayName??"territorio seleccionado"}`}>{geometries.map(g=>{const isSelectable=selectable.has(g.sectionId),isSelected=selected===g.sectionId;return <path key={g.sectionId} d={path(g.geometry)} className={isSelected?"selected":isSelectable?"residual":"context"} role={isSelectable?"button":undefined} tabIndex={isSelectable?0:undefined} aria-label={isSelectable?g.displayName:undefined} onClick={()=>isSelectable&&onSelect(g.sectionId)} onKeyDown={event=>{if(isSelectable&&(event.key==="Enter"||event.key===" ")){event.preventDefault();onSelect(g.sectionId)}}}><title>{g.displayName}</title></path>})}</svg><figcaption><span>Territorio seleccionado</span><strong>{selectedGeo?.displayName}</strong></figcaption></figure>}

export function TerritorialRelationshipsStory(){const [selectedPoint,setSelectedPoint]=useState(data.sectionPoints[0].sectionId),[party,setParty]=useState<"pp"|"psoe">("pp"),[residual,setResidual]=useState(defaultResidualId);const selected=data.sectionPoints.find(x=>x.sectionId===selectedPoint)!;const residualRows=data.residualTerritories.filter(x=>x.section_id===residual);const typologyVars=['participation_municipal_2023','share_pp','share_psoe'];return <section id="territorial-relationships" className="territorial-relationships" aria-labelledby="relations-title">
 <section className="relations-scene relations-education"><header><span>La relación más consistente</span><h3 id="relations-title">Estudios superiores y distribución territorial del voto.</h3><p>Las secciones con mayor presencia de estudios superiores tendieron a mostrar más apoyo al PP y menos al PSOE, especialmente en elecciones generales y europeas.</p></header><div className="relations-party-tabs"><button className={party==="pp"?"active":""} onClick={()=>setParty("pp")}>PP</button><button className={party==="psoe"?"active":""} onClick={()=>setParty("psoe")}>PSOE</button></div><div className="relations-scatter-layout"><Scatter xKey="pct_higher_studies" yKey={party==="pp"?"share_pp":"share_psoe"} selected={selectedPoint} onSelect={setSelectedPoint}/><aside><strong>{selected.displayName}</strong>{["municipal_2023","congress_2023","european_2024"].map(context=>{const suffix=context==="municipal_2023"?`share_${party}`:`${context.replace("municipal_2023","")}_share_${party}`;const item=data.selectedRelationships.find(x=>x.x==="pct_higher_studies"&&x.y===suffix)!;return <article key={context}><span>{context.replaceAll("_"," ")}</span><b>{item.pearson.toFixed(4)}</b></article>})}<p>Ajustada en Municipales: {partial(`P_pct_higher_studies__share_${party}`).partial_correlation.toFixed(4)}</p></aside></div></section>
 <section className="relations-scene relations-controls"><header><span>03 · Antes y después de los controles</span><h3>Una relación intensa puede casi desaparecer.</h3><p>Cuando edad, educación, renta y contexto urbano se consideran conjuntamente, algunas relaciones directas se atenúan o cambian de signo. Esto no representa un efecto causal verdadero.</p></header><div className="relations-raw-grid"><RawAdjusted title="Renta ↔ PP" raw={partial('P_income_individual__share_pp').raw_correlation} adjusted={partial('P_income_individual__share_pp').partial_correlation}/><RawAdjusted title="Renta ↔ PSOE" raw={partial('P_income_individual__share_psoe').raw_correlation} adjusted={partial('P_income_individual__share_psoe').partial_correlation}/><RawAdjusted title="Densidad ↔ PP" raw={partial('P_density_per_km2__share_pp').raw_correlation} adjusted={partial('P_density_per_km2__share_pp').partial_correlation}/><RawAdjusted title="Densidad ↔ PSOE" raw={partial('P_density_per_km2__share_psoe').raw_correlation} adjusted={partial('P_density_per_km2__share_psoe').partial_correlation}/></div></section>
 <section className="relations-scene relations-income"><header><span>04 · La elección importa</span><h3>La renta se relaciona de forma distinta según la elección.</h3></header><div>{data.electionConsistency.filter(x=>x.relationship.startsWith('income_individual')).map(row=><article key={row.relationship}><h4>{row.relationship.endsWith('share_pp')?'Renta ↔ PP':'Renta ↔ PSOE'}</h4>{[['Municipales',row.municipal_pearson],['Congreso',row.congress_pearson],['Europeas',row.european_pearson]].map(([label,value])=><div key={String(label)}><span>{label}</span><i><b style={{width:`${Math.abs(Number(value))*100}%`}}/></i><strong>{Number(value).toFixed(4)}</strong></div>)}<small>Dirección consistente; intensidad dependiente del tipo de elección.</small></article>)}</div><p>La asociación municipal directa queda fuertemente condicionada al ajustar por educación, edad y densidad. No se infieren motivaciones.</p></section>
 <section className="relations-scene relations-participation"><header><span>05 · Un resultado negativo central</span><h3>La participación no tiene una explicación territorial simple.</h3></header><div className="relations-model-hero"><strong>{twoDecimals.format(model('participation_municipal_2023').adjusted_r_squared)}</strong><span>R² ajustado</span><strong>{twoDecimals.format(model('participation_municipal_2023').loocv_rmse)} pp</strong><span>error fuera de muestra</span></div><div className="relations-weak-list">{[['Edad media','R_average_age__participation_municipal_2023'],['Menores de 30','R_under_30_pct__participation_municipal_2023'],['Mayores de 65','R_over_65_pct__participation_municipal_2023'],['Crecimiento','R_growth_percent_2023_2024__participation_municipal_2023']].map(([label,id])=><article key={id}><span>{label}</span><strong>{twoDecimals.format(relationship(id).pearson)}</strong><small>relación débil o inconclusa</small></article>)}<article><span>Densidad ajustada</span><strong>{twoDecimals.format(partial('P_density_per_km2__participation_municipal_2023').partial_correlation)}</strong><small>relación ajustada</small></article></div><p>Edad, crecimiento, renta y densidad no ofrecen por sí solos una explicación fiable de la participación municipal. Investigar causas requeriría evidencia adicional.</p></section>
 <section className="relations-scene relations-models"><header><span>06 · Estructura descriptiva</span><h3>La geografía de PP y PSOE muestra más estructura que la participación.</h3></header><div className="relations-model-cards">{descriptiveModelCards.map(card=>{const m=model(card.key),adjusted=m.adjusted_r_squared.toFixed(4).replace(".",","),error=m.loocv_rmse.toFixed(1).replace(".",",");return <article key={card.key} className={`relations-model-card relations-model-card--${card.accent}`}><span className="relations-model-label">{card.label}</span><strong>{card.percentage}</strong><h4>{card.status}</h4><p>{card.explanation}</p><small title={`Valores completos: R² ajustado ${m.adjusted_r_squared.toFixed(4)}; error de validación ${m.loocv_rmse.toFixed(4)} pp`}>R² ajustado: {adjusted} · error de validación: {error} pp</small></article>})}</div><div className="relations-model-reading"><h4>El voto tiene una geografía más estructurada que la participación.</h4><p>Las características territoriales ayudan a comprender una parte importante de dónde PP y PSOE obtienen más o menos apoyo. En cambio, las diferencias de participación dependen de factores que los datos territoriales disponibles no capturan suficientemente.</p></div><aside className="relations-model-implication"><strong>Lectura estratégica</strong><p>La inteligencia territorial ofrece una base útil para analizar apoyo electoral y diferencias entre zonas. Para estudiar movilización y abstención con mayor precisión sería necesario incorporar información adicional de campaña, organización, contacto o investigación cualitativa.</p></aside><p className="relations-validation-help"><Info/> <span><strong>Error de validación:</strong> diferencia media aproximada entre el valor observado y el descrito por el modelo al comprobarlo fuera de la muestra de ajuste.</span></p><p className="relations-model-caveat">Modelos descriptivos: no son pronósticos, no estiman comportamientos individuales y no deben utilizarse como predicciones de voto.</p></section>
 <section className="relations-scene relations-elections"><header><span>07 · Consistencia electoral</span><h3>Una relación general no se traslada automáticamente a una elección municipal.</h3></header><div className="relations-election-legend" aria-label="Tipos de elección">{[['M','Elecciones Municipales'],['C','Elecciones al Congreso'],['E','Elecciones Europeas'],['A','Elecciones Autonómicas']].map(([letter,label])=><span key={letter}><b>{letter}</b>{label}</span>)}</div><div className="relations-election-grid">{data.electionConsistency.map(row=>{const autonomous=autonomousByRelationship.get(row.relationship);if(!autonomous) return null;return <article key={row.relationship}><h4>{row.relationship.split('__').map(x=>labels[x]??x).join(' ↔ ')}</h4><div>{[['M',row.municipal_pearson],['C',row.congress_pearson],['E',row.european_pearson],['A',autonomous.autonomous_pearson]].map(([e,v])=><span key={String(e)} style={{height:`${20+Math.abs(Number(v))*90}px`}} className={Number(v)<0?'negative':''}><b>{e}</b><small>{Number(v).toFixed(2)}</small></span>)}</div><p>{row.classification==='cross-election consistent'?'Dirección consistente; intensidad variable.':'Débil o dependiente de la elección.'}</p></article>})}</div><details className="relations-election-evidence"><summary>Base comparable de la elección autonómica</summary><p><strong>Elecciones Autonómicas · Andalucía 2026.</strong> Los recuentos de sus 41 secciones se sumaron en los 37 territorios de referencia mediante correspondencias espaciales verificadas; después se recalcularon participación, porcentajes de voto y margen. Las barras A muestran Pearson con n=37 y sin observaciones ausentes.</p></details><p className="relations-election-caveat">Una relación observada en una convocatoria no puede trasladarse automáticamente a otra.</p></section>
 <section className="relations-scene relations-history"><header><span>08 · Cambios 2019–2023</span><h3>Sensibilidad histórica sobre 28 familias armonizadas.</h3><p>Los predictores actuales se promedian dentro de familias históricas. Son asociaciones descriptivas, no evidencia causal contemporánea ni transferencias individuales.</p></header><div>{data.historicalSensitivity.map(item=><article key={item.x+item.y}><span>{labels[item.x]??item.x} ↔ {item.y.replaceAll('_',' ')}</span><strong>{item.pearson.toFixed(4)}</strong><small>Spearman {item.spearman.toFixed(4)} · n={item.n} · {item.sensitivity_status}</small></article>)}</div></section>
 <section className="relations-scene relations-typologies"><header><span>09 · Diferencias entre tipologías</span><h3>Las familias resumen similitudes, no eliminan la diversidad interna.</h3></header><div>{typologyVars.map(variable=><article key={variable}><h4>{labels[variable]}</h4>{data.typologyComparisons.filter(x=>x.variable===variable).map(row=><div key={row.group}><span><i style={{background:typologyConfig.palette[Number(row.group.replace('Group ',''))-1]}}/>{row.group}<small>{typologyConfig.groups[row.group as keyof typeof typologyConfig.groups].title}</small></span><b style={{width:`${row.mean}%`}}/><strong>{row.mean.toFixed(4)}%</strong><em>sin transicionales {row.mean_without_transitional.toFixed(4)}% · dispersión {row.stddev.toFixed(2)}</em></div>)}</article>)}</div><aside>Muestras pequeñas por familia. Las medias no describen votantes homogéneos ni segmentos estratégicos.</aside></section>
 <section className="relations-scene relations-residuals"><header><span>10 · Fuera del patrón general</span><h3>Territorios no resumidos completamente por el modelo municipal.</h3></header><div className="relations-residual-layout"><ResidualMap selected={residual} onSelect={setResidual}/><aside><nav aria-label="Territorios fuera del patrón general">{residualOptions.map(item=><button key={item.section_id} type="button" data-section-id={item.section_id} onClick={()=>setResidual(item.section_id)} className={residual===item.section_id?'active':''} aria-pressed={residual===item.section_id}><MapPin/>{item.display_name}</button>)}</nav><h4>{residualRows[0]?.display_name}</h4>{residualRows.map(row=><article key={row.main_model}><span>{labels[row.main_model]??row.main_model}</span><p>Observado {row.observed.toFixed(3)} · descripción del modelo {row.fitted.toFixed(3)}</p><strong>{row.standardized_residual>0?'Por encima':'Por debajo'} · {row.standardized_residual.toFixed(3)} DE</strong></article>)}</aside></div></section>
 </section>}
