import { GitCompareArrows, Info } from "lucide-react";
import { useMemo, useState } from "react";
import dossierJson from "@/features/campaigns/data/generated/mijas-2027-block-d-territorial-clusters.json";
import indexJson from "@/features/campaigns/data/generated/block-c/territory-index.json";
import geometriesJson from "@/features/campaigns/data/generated/block-c/territory-geometries.json";
import { mijas2027TypologyPresentation as presentation } from "@/features/campaigns/data/mijas-2027-typologies";
import "./TerritorialTypologyStory.css";

type Point=[number,number]; type Geometry={type:"MultiPolygon";coordinates:Point[][][]};
type Geo={sectionId:string;displayName:string;geometry:Geometry};
type IndexItem={sectionId:string;displayName:string;metrics:Record<string,number|string|null>};
type Membership={seccion_id:string;display_name:string;cluster_id:string;second_nearest_cluster:string;distance:number;assignment_margin:number;silhouette:number;stability:number;assignment_confidence:string;transitional:boolean};
type Profile={cluster_id:string;section_count:number;population_represented:number;section_ids:string[];representative_section:string;representative_name:string;nearest_cluster:string;nearest_cluster_distance:number;original_means:Record<string,number>;original_medians:Record<string,number>;top_above:string[];top_below:string[];within_cluster_dispersion:number};
type Outlier={seccion_id:string;display_name:string;cluster_id:string;outlier_score:number;driver_features:string;client_singularity_flag:boolean};
const dossier=dossierJson as unknown as {clusterProfiles:Profile[];territoryMembership:Membership[];outliers:Outlier[];structuralGrouping:{sectionId:string;clusterId:string}[];electoralGrouping:{sectionId:string;clusterId:string}[];integratedGrouping:{sectionId:string;clusterId:string}[];solutionComparison:{solution_a:string;solution_b:string;adjusted_rand_index:number}[];selectedSolution:{metrics:{silhouette:number;calinski_harabasz:number;davies_bouldin:number;cluster_sizes:string;minimum_cluster_size:number};spatialDiagnostics:{adjacencyConsistency:number;disconnectedComponents:Record<string,number>}};alternativeSolution:{metrics:{silhouette:number;calinski_harabasz:number;davies_bouldin:number;cluster_sizes:string}};stability:{meanRandomInitializationARI:number;meanSubsampleARI:number};featureCatalogue:{feature:string;source:string;year:number|string;status:string}[];limitations:string[]};
const index=indexJson as IndexItem[], geometries=geometriesJson as unknown as Geo[];
const groups=Object.keys(presentation.groups) as (keyof typeof presentation.groups)[];
const integer=new Intl.NumberFormat("es-ES"), decimal=new Intl.NumberFormat("es-ES",{maximumFractionDigits:2}), oneDecimal=new Intl.NumberFormat("es-ES",{minimumFractionDigits:1,maximumFractionDigits:1}), compact=new Intl.NumberFormat("es-ES",{notation:"compact",maximumFractionDigits:1});
const featureMeta:Record<string,{label:string;unit:string}>={density_per_km2:{label:"Densidad",unit:"hab./km²"},growth_percent_2023_2024:{label:"Crecimiento 2023–2024",unit:"%"},average_age:{label:"Edad media",unit:"años"},income_individual:{label:"Renta individual",unit:"€"},building_intensity:{label:"Intensidad construida",unit:"ratio"},pct_higher_studies:{label:"Estudios superiores",unit:"%"},participation_municipal_2023:{label:"Participación municipal 2023",unit:"%"},margin_municipal_2023:{label:"Margen municipal 2023",unit:"pp"},share_pp:{label:"Proporción PP",unit:"%"},share_psoe:{label:"Proporción PSOE",unit:"%"}};
function projector(items:Geometry[]){const pts=items.flatMap(g=>g.coordinates.flatMap(p=>p.flatMap(r=>r))),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),w=960,h=660,p=24,s=Math.min((w-2*p)/(maxX-minX),(h-2*p)/(maxY-minY)),ox=(w-(maxX-minX)*s)/2,oy=(h-(maxY-minY)*s)/2,point=([x,y]:Point)=>[ox+(x-minX)*s,h-oy-(y-minY)*s];return(g:Geometry)=>g.coordinates.map(poly=>poly.map(r=>r.map((q,i)=>`${i?"L":"M"}${point(q).map(v=>v.toFixed(1)).join(" ")}`).join(" ")+" Z").join(" ")).join(" ")}
const membershipById=new Map(dossier.territoryMembership.map(m=>[m.seccion_id,m]));
const profileByGroup=new Map(dossier.clusterProfiles.map(p=>[p.cluster_id,p]));
function groupNumber(group:string){return Math.max(0,Number(group.replace("Group ",""))-1)}
function swatch(group:string){return presentation.palette[groupNumber(group)]}
const analyticalPalettes={structural:["#d8a15f","#70a59f","#9388b5","#bd7d70","#819b68","#6690aa"],electoral:["#c59665","#689d96","#8c83ad","#b87970","#7e9469"],integrated:["#d0a066","#71a29c","#9185b1","#bb7d70"]} as const;
const analyticalViews=[{id:"structural",title:"Estructura",description:"Agrupa territorios por características demográficas, económicas y urbanas."},{id:"electoral",title:"Comportamiento electoral",description:"Agrupa territorios según patrones de participación, competencia y distribución del voto."},{id:"integrated",title:"Lectura integrada",description:"Combina ambas dimensiones para identificar territorios con perfiles multidimensionales similares."}] as const;
function analyticalRows(view:"structural"|"electoral"|"integrated"){return view==="structural"?dossier.structuralGrouping:view==="electoral"?dossier.electoralGrouping:dossier.integratedGrouping}
function analyticalSwatch(view:"structural"|"electoral"|"integrated",group:string){return analyticalPalettes[view][groupNumber(group)]??"#708087"}
function metricValue(value:number,key:string){return key==="income_individual"?`${integer.format(value)} €`:key==="density_per_km2"?`${integer.format(value)} hab./km²`:`${decimal.format(value)} ${featureMeta[key]?.unit??""}`}
function TypologyMap({selectedGroup,onGroup,onSection,view="primary"}:{selectedGroup?:string;onGroup?:(g:string)=>void;onSection?:(id:string)=>void;view?:"primary"|"structural"|"electoral"|"integrated"}){const path=useMemo(()=>projector(geometries.map(g=>g.geometry)),[]),interactive=Boolean(onGroup||onSection);const viewRows=view==="structural"?dossier.structuralGrouping:view==="electoral"?dossier.electoralGrouping:view==="integrated"?dossier.integratedGrouping:null;const viewMap=new Map(viewRows?.map(x=>[x.sectionId,x.clusterId]));return <svg className="typology-map-svg" viewBox="0 0 960 660" preserveAspectRatio="xMidYMid meet" role="img" aria-label={`Mapa de tipologías: ${view}`}>{geometries.map(geo=>{const primary=membershipById.get(geo.sectionId)!;const group=viewMap.get(geo.sectionId)??primary.cluster_id;const faded=selectedGroup&&primary.cluster_id!==selectedGroup;return <path key={geo.sectionId} data-section-id={geo.sectionId} data-group={group} d={path(geo.geometry)} fill={swatch(group)} opacity={faded?.28:1} className={primary.transitional?"transitional":""} role={interactive?"button":undefined} tabIndex={interactive?0:undefined} aria-label={`${geo.displayName}; ${group}${primary.transitional?"; asignación transicional":""}`} onClick={interactive?()=>{onGroup?.(primary.cluster_id);onSection?.(geo.sectionId)}:undefined} onKeyDown={interactive?e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onGroup?.(primary.cluster_id);onSection?.(geo.sectionId)}}:undefined}><title>{geo.displayName} · {group}</title></path>})}</svg>}
function RepresentativeTerritoryLocator({sectionId,label,group}:{sectionId:string;label:string;group:string}){const path=useMemo(()=>projector(geometries.map(g=>g.geometry)),[]);return <svg className="typology-representative-locator" data-representative-section={sectionId} viewBox="0 0 960 660" preserveAspectRatio="xMidYMid meet" role="img" aria-label={`Localización de ${label} dentro de Mijas`}>{geometries.map(geo=>{const representative=geo.sectionId===sectionId;return <path key={geo.sectionId} data-section-id={geo.sectionId} data-representative={representative?"true":"false"} className={representative?"representative":"context"} d={path(geo.geometry)} fill={representative?swatch(group):undefined}><title>{geo.displayName}{representative?" · territorio representativo":""}</title></path>})}</svg>}
function GroupBadge({group}:{group:string}){return <span className="typology-group-badge"><i style={{background:swatch(group)}}/>{group}</span>}
function AnalyticalMap({view}:{view:"structural"|"electoral"|"integrated"}){const path=useMemo(()=>projector(geometries.map(g=>g.geometry)),[]),viewMap=new Map(analyticalRows(view).map(row=>[row.sectionId,row.clusterId]));return <svg className="typology-analytical-map" data-analytical-view={view} viewBox="0 0 960 660" preserveAspectRatio="xMidYMid meet" role="img" aria-label={`Mapa analítico: ${view}`}>{geometries.map(geo=>{const group=viewMap.get(geo.sectionId)!;return <path key={geo.sectionId} data-section-id={geo.sectionId} data-group={group} d={path(geo.geometry)} fill={analyticalSwatch(view,group)} opacity="1"><title>{geo.displayName} · {group}</title></path>})}</svg>}
function EvidenceNote({feature,value}:{feature:string;value:number}){const source=dossier.featureCatalogue.find(f=>f.feature===feature);const universe=index.reduce((sum,item)=>sum+(Number(item.metrics[feature])||0),0)/index.length;return <details className="typology-evidence"><summary>{featureMeta[feature]?.label}: {metricValue(value,feature)}</summary><p>Referencia de las 37 secciones: {metricValue(universe,feature)}. Fuente: {source?.source}, {source?.year}. Modelo reducido D · evidencia verificada.</p></details>}
function familyTraits(profile:Profile){return [...profile.top_above.slice(0,2).map(key=>`Más ${featureMeta[key]?.label.toLocaleLowerCase("es")??key}`),...profile.top_below.slice(0,1).map(key=>`Menos ${featureMeta[key]?.label.toLocaleLowerCase("es")??key}`)]}

export function TerritorialTypologyStory(){
 const [selectedGroup,setSelectedGroup]=useState<string>("Group 1"),[comparison,setComparison]=useState<string[]>(["Group 1","Group 2"]);
 const profile=profileByGroup.get(selectedGroup)!;
 const toggleCompare=(group:string)=>setComparison(current=>current.includes(group)?current.filter(x=>x!==group):current.length<2?[...current,group]:[current[1],group]);
 return <section id={presentation.chapterId} className="territorial-typologies" aria-labelledby="typology-title">
  <header className="typology-opening"><div><span className="typology-kicker">07 · Tipologías territoriales</span><h2 id="typology-title">Mijas no se organiza alrededor de una única diferencia.</h2><p>La población, la forma urbana, la edad, la renta y el comportamiento electoral se combinan de manera diferente en el municipio.</p><aside><Info/> Son similitudes analíticas entre territorios, no identidades fijas de sus residentes.</aside></div></header>
  <section className="typology-scene typology-premise"><span>01 · Más de una división territorial</span><h3>Mijas no puede explicarse solo como costa e interior, joven y mayor, o izquierda y derecha.</h3><div>{["Densidad y forma urbana","Crecimiento de población","Edad","Renta y estudios superiores","Participación y margen municipal","Proporciones PP y PSOE"].map((label,i)=><article key={label}><b>0{i+1}</b><p>{label}</p></article>)}</div></section>
  <section id="five-families-map" className="typology-map-scene typology-map-scene--static" aria-labelledby="typology-map-title"><header><span>02 · Cinco familias territoriales</span><h3 id="typology-map-title">37 secciones.<br/>Cinco lecturas compartidas.</h3><p>Las secciones se agrupan por similitudes verificadas de población, forma urbana, edad, renta, formación y comportamiento electoral.</p><div className="typology-map-metrics"><article><strong>5</strong><small>familias</small></article><article><strong>37</strong><small>secciones</small></article><article><strong>92.211</strong><small>residentes</small></article></div></header><figure className="typology-static-map"><TypologyMap/><figcaption>Distribución territorial de las cinco familias analíticas</figcaption></figure><div className="typology-static-legend" aria-label="Leyenda de familias territoriales">{groups.map(group=><div key={group}><i style={{background:swatch(group)}}/><span><strong>{group}</strong>{presentation.groups[group].title}</span></div>)}</div><div className="typology-family-summaries">{groups.map(group=>{const item=profileByGroup.get(group)!;return <article key={group} style={{borderTopColor:swatch(group)}}><span>{group}</span><h4>{presentation.groups[group].title}</h4><p>{item.section_count} secciones · {integer.format(item.population_represented)} residentes</p><ul>{familyTraits(item).map(trait=><li key={trait}>{trait}</li>)}</ul></article>})}</div></section>
  <section className="typology-scene typology-profile" aria-labelledby="typology-profile-title"><header><span>03 · Explorar cada familia</span><h3 id="typology-profile-title">{presentation.groups[selectedGroup as keyof typeof presentation.groups].title}</h3><p>{presentation.groups[selectedGroup as keyof typeof presentation.groups].subtitle}</p></header><nav className="typology-family-picker" aria-label="Seleccionar tipología territorial">{groups.map(group=><button key={group} type="button" className={selectedGroup===group?"active":""} aria-pressed={selectedGroup===group} onClick={()=>setSelectedGroup(group)}><i style={{background:swatch(group)}}/>{presentation.groups[group].title}</button>)}</nav><div className="typology-profile-grid"><article className="typology-profile-stat"><strong>{profile.section_count}</strong><span>secciones</span><strong>{integer.format(profile.population_represented)}</strong><span>residentes representados</span></article><article><span>Territorio representativo</span><h4>{profile.representative_name}</h4><small>Medoide: sección más próxima al centro analítico del grupo.</small></article><article><span>Familia analítica más próxima</span><h4>{presentation.groups[profile.nearest_cluster as keyof typeof presentation.groups].title}</h4><p>Distancia entre centros: {decimal.format(profile.nearest_cluster_distance)}</p><small>Dispersión interna: {decimal.format(profile.within_cluster_dispersion)}</small></article></div><div className="typology-characteristics"><div><h4>Por encima de la referencia</h4>{profile.top_above.map(key=><EvidenceNote key={key} feature={key} value={profile.original_means[key]}/>)}</div><div><h4>Por debajo de la referencia</h4>{profile.top_below.map(key=><EvidenceNote key={key} feature={key} value={profile.original_means[key]}/>)}</div></div></section>
  <section className="typology-scene typology-comparison"><header><span>04 · Comparar dos familias</span><h3>Diferencias factuales, sin jerarquías.</h3></header><div className="typology-compare-picker">{groups.map(group=><button key={group} onClick={()=>toggleCompare(group)} className={comparison.includes(group)?"active":""} aria-pressed={comparison.includes(group)}><i style={{background:swatch(group)}}/>{group}</button>)}</div>{comparison.length===2?<div className="typology-compare-table"><header><span>Variable</span>{comparison.map(g=><strong key={g}>{g}</strong>)}<span>Referencia</span></header>{Object.entries(featureMeta).map(([key,meta])=>{const reference=index.reduce((s,x)=>s+(Number(x.metrics[key])||0),0)/37;return <article key={key}><span>{meta.label}</span>{comparison.map(g=><strong key={g}>{metricValue(profileByGroup.get(g)!.original_means[key],key)}</strong>)}<small>{metricValue(reference,key)}</small></article>})}</div>:<p>Seleccione exactamente dos familias.</p>}</section>
  <section className="typology-scene typology-views"><header><span>05 · Estructura y voto</span><h3>Territorios socialmente parecidos no siempre votan igual.</h3><p>Y territorios que votan de forma parecida no siempre comparten la misma estructura social.</p></header><div className="typology-analytical-maps">{analyticalViews.map(view=>{const rows=analyticalRows(view.id),viewGroups=[...new Set(rows.map(row=>row.clusterId))].sort((a,b)=>groupNumber(a)-groupNumber(b));return <article key={view.id} className={`typology-analytical-card ${view.id}`} data-view={view.id}><header><h4>{view.title}</h4><p>{view.description}</p></header><figure><AnalyticalMap view={view.id}/><figcaption>{viewGroups.map(group=><span key={group}><i style={{background:analyticalSwatch(view.id,group)}}/>{group}</span>)}</figcaption></figure></article>})}</div><p className="typology-view-conclusion">La coincidencia entre las agrupaciones es limitada: estructura territorial y comportamiento electoral están relacionados, pero no son equivalentes.</p><details className="typology-view-method"><summary>Comparación técnica entre agrupaciones</summary><div className="typology-agreement">{dossier.solutionComparison.map(row=><article key={row.solution_a+row.solution_b}><GitCompareArrows/><span>{row.solution_a.replace("A_structural","Estructura").replace("B_electoral","Voto")} ↔ {row.solution_b.replace("B_electoral","Voto").replace("C_integrated","Integrada")}</span><strong>{decimal.format(row.adjusted_rand_index)}</strong></article>)}</div><p>ARI compara coincidencia de agrupaciones corrigiendo el acuerdo esperado por azar. 0 indica acuerdo equivalente al azar y 1 coincidencia completa.</p></details></section>
  <section className="typology-scene typology-representatives"><header><span>06 · Territorios representativos</span><h3>El centro analítico de cada familia.</h3></header><div>{dossier.clusterProfiles.map(p=><article key={p.cluster_id} data-representative-section={p.representative_section}><figure className="typology-mini-map"><RepresentativeTerritoryLocator sectionId={p.representative_section} label={p.representative_name} group={p.cluster_id}/></figure><span className="typology-representative-family"><i style={{background:swatch(p.cluster_id)}}/>{presentation.groups[p.cluster_id as keyof typeof presentation.groups].title}</span><h4>{p.representative_name}</h4><p>{presentation.groups[p.cluster_id as keyof typeof presentation.groups].subtitle}</p><small>Referencia representativa; no describe un tipo de residente.</small></article>)}</div></section>
  <section className="typology-scene typology-transitional"><header><span>07 · Territorios transicionales</span><h3>Algunos territorios combinan características de más de una familia analítica.</h3></header><div>{dossier.territoryMembership.filter(m=>m.transitional).map(m=><article key={m.seccion_id}><GroupBadge group={m.cluster_id}/><h4>{m.display_name}</h4><p>Segunda familia más próxima: {m.second_nearest_cluster}.</p><span>Estabilidad {decimal.format(m.stability*100)}%</span><details><summary>Detalle de la asignación</summary><p>Margen {decimal.format(m.assignment_margin)} · silueta {decimal.format(m.silhouette)} · distancia {decimal.format(m.distance)}. Se presenta como frontera analítica, no como error.</p></details></article>)}</div></section>
  <section className="typology-scene typology-outliers"><header><span>08 · Territorios singulares</span><h3>Algunos territorios no encajan del todo en su familia.</h3><p>Estas secciones comparten rasgos con su familia territorial, pero presentan algunas características que se alejan más del patrón común. No son territorios anómalos: simplemente quedan peor resumidos por una única tipología.</p><p className="typology-outliers-implication">Esto ayuda a detectar territorios que conviene analizar con más detalle, porque una etiqueta general puede ocultar diferencias importantes.</p></header><p className="typology-outliers-helper">Cuanto mayor es el indicador de singularidad, más se aleja esa sección del perfil medio de su familia.</p><div>{dossier.outliers.slice(0,5).map(o=><article key={o.seccion_id}><strong>{decimal.format(o.outlier_score)}</strong><div><span className="typology-group-badge"><i style={{background:swatch(o.cluster_id)}}/>{presentation.groups[o.cluster_id as keyof typeof presentation.groups].title}</span><h4>{o.display_name}</h4><p>Variables principales: {o.driver_features.split("|").map(x=>featureMeta[x]?.label??x).join(", ")}.</p></div></article>)}</div></section>
  <section className="typology-scene typology-geography"><header><span>09 · Geografía y similitud</span><h3>La similitud nace de la evidencia, no de forzar a secciones vecinas dentro de la misma categoría.</h3><p>Dos territorios pueden parecerse aunque no sean vecinos, y dos secciones contiguas pueden responder a realidades distintas. Esta lectura permite agrupar zonas por características compartidas y no solo por proximidad geográfica.</p><p className="typology-geography-value"><b>¿Qué aporta?</b> Permite detectar patrones territoriales que atraviesan barrios y zonas del municipio y evita asumir que la cercanía física implica necesariamente una realidad social o electoral similar.</p></header><div><strong>{oneDecimal.format(dossier.selectedSolution.spatialDiagnostics.adjacencyConsistency*100)} %</strong><p>de las relaciones de vecindad conectan secciones de la misma familia analítica.</p><ul><li>Grupos 1–4: un componente geográfico cada uno.</li><li>Grupo 5: dos componentes geográficos.</li><li>La continuidad espacial no fue impuesta.</li></ul></div></section>
  <section className="typology-scene typology-choice"><header><span>10 · Por qué cinco grupos</span><h3>Cinco familias preservan diferencias útiles sin crear microgrupos artificiales.</h3></header><div><article><span>Modelo principal</span><strong>10 variables · 5 grupos</strong><p>4 | 7 | 7 | 9 | 10 secciones</p></article><article><span>Alternativa Ward</span><strong>16 variables · 4 grupos</strong><p>6 | 6 | 6 | 19 secciones</p></article></div><details><summary>Metodología y puntuaciones completas</summary><p>Principal: silueta {dossier.selectedSolution.metrics.silhouette.toFixed(4)}, Calinski–Harabasz {dossier.selectedSolution.metrics.calinski_harabasz.toFixed(4)}, Davies–Bouldin {dossier.selectedSolution.metrics.davies_bouldin.toFixed(4)}. Alternativa: silueta {dossier.alternativeSolution.metrics.silhouette.toFixed(4)}, Calinski–Harabasz {dossier.alternativeSolution.metrics.calinski_harabasz.toFixed(4)}, Davies–Bouldin {dossier.alternativeSolution.metrics.davies_bouldin.toFixed(4)}.</p></details></section>
  <footer className="typology-closing"><span>11 · Síntesis consultiva basada en análisis multivariable</span><h3>La estructura territorial y el comportamiento electoral deben leerse juntos, pero nunca confundirse.</h3><p>Las cinco familias ofrecen un mapa más claro de la diversidad municipal, preservando la singularidad de los territorios transicionales.</p></footer>
 </section>
}
