import { useMemo } from "react";
import { ArrowDown, CheckCircle2 } from "lucide-react";
import snapshotJson from "@/features/campaigns/data/generated/mijas-2027-territorial-evolution.json";

type Point=[number,number]; type Geometry={type:"MultiPolygon";coordinates:Point[][][]};
type Annual={year:number;population:number;absoluteChange:number|null;percentageChange:number|null;men:number;women:number;under30:number;over65:number};
type Unit={id:string;label:string;classification:"sustained_growth"|"sustained_decline"|"volatile"|"stable"|"recent_growth"|"recent_decline"|"insufficient";population2021:number;population2025:number;cumulativeChange:number;cumulativePercent:number;growingYears:number;decliningYears:number;volatility:number;growthContributionPercent:number;yearly:Annual[];geometry:Geometry};
type Snapshot={snapshotVersion:string;method:{name:string;unitCount:number;period:string;rule:string;classification:string};summary:{municipalGrowth:number;sustainedGrowthUnits:number;volatileUnits:number;sustainedDeclineUnits:number;topFiveContributionPercent:number};municipalTimeline:{year:number;population:number}[];units:Unit[];sectionUniverse:{year:number;validCount:number;newSections:string[]}[];lineage:{year:number;child:string;parent:string;overlapPercent:number}[];quality:{minimumSpatialAssignmentPercent:number;limitations:string[]}};
const data=snapshotJson as unknown as Snapshot;
const integer=new Intl.NumberFormat("es-ES"); const decimal=new Intl.NumberFormat("es-ES",{maximumFractionDigits:1,minimumFractionDigits:1});

function projection(units:Unit[]){const pts=units.flatMap(u=>u.geometry.coordinates.flatMap(p=>p.flatMap(r=>r)));const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);const a=Math.min(...xs),b=Math.max(...xs),c=Math.min(...ys),d=Math.max(...ys),w=960,h=650,p=25,s=Math.min((w-2*p)/(b-a),(h-2*p)/(d-c)),ox=(w-(b-a)*s)/2,oy=(h-(d-c)*s)/2;const point=([x,y]:Point)=>[ox+(x-a)*s,h-oy-(y-c)*s];return (g:Geometry)=>g.coordinates.map(poly=>poly.map(r=>r.map((q,i)=>`${i?"L":"M"}${point(q).map(v=>v.toFixed(1)).join(" ")}`).join(" ")+" Z").join(" ")).join(" ")}
const labels:Record<Unit["classification"],string>={sustained_growth:"Crecimiento sostenido",sustained_decline:"Descenso sostenido",volatile:"Evolución variable",stable:"Estable",recent_growth:"Crecimiento reciente",recent_decline:"Descenso reciente",insufficient:"Evidencia insuficiente"};
function tag(text:string){return <span className="evolution-tag"><CheckCircle2/> {text}</span>}

function ComparableTerritories(){const path=useMemo(()=>projection(data.units),[]);return <section id="comparable-territories" className="evolution-comparable" aria-labelledby="comparable-territories-title"><header><p>Familias territoriales comparables</p><h3 id="comparable-territories-title">32 territorios comparables a través del tiempo</h3><span>Cuando una sección se divide, sus nuevas partes se reagrupan en el territorio de origen para poder seguir su evolución sin fabricar crecimientos o caídas artificiales.</span></header><figure className="evolution-comparable-map"><svg viewBox="0 0 960 650" preserveAspectRatio="xMidYMid meet" role="img" aria-label="Mapa de las 32 familias territoriales armonizadas de Mijas"><g>{data.units.map((unit,index)=><path key={unit.id} d={path(unit.geometry)} fill={`hsl(${24+index%4*8} 74% ${48+index%3*7}%)`} fillRule="evenodd"><title>{unit.label} · familia comparable anclada en 2021</title></path>)}</g></svg><figcaption><strong>32</strong><span>familias territoriales armonizadas · base territorial 2021</span></figcaption></figure><div className="evolution-section-sequence" aria-label="Evolución del número de secciones oficiales"><div>{data.sectionUniverse.filter(x=>x.year<=2025).map((item,index)=><article key={item.year}><span>{item.year}</span><strong>{item.validCount}</strong><small>secciones</small>{index<4?<b>→</b>:null}</article>)}</div><p>Análisis longitudinal · <strong>32 familias comparables</strong></p></div><div className="evolution-harmonisation"><article><p>2025 · divisiones incorporadas a la serie</p><ul><li><strong>Sección 026</strong><span>incluye la nueva sección 038</span></li><li><strong>Sección 028</strong><span>incluye la nueva sección 039</span></li></ul></article><article><p>2026 · el proceso territorial continúa</p><ul><li><strong>Sección 018</strong><span>nueva sección 040</span></li><li><strong>Sección 024</strong><span>nueva sección 041</span></li></ul><small>040 y 041 ilustran la geografía actual; no forman parte de la serie demográfica 2021–2025.</small></article></div><div className="evolution-harmonisation-flow" aria-label="Esquema metodológico de armonización"><span>Territorio original</span><b>→</b><span>División administrativa</span><b>→</b><span>Familia comparable</span></div><details className="evolution-comparable-method"><summary>Ver metodología →</summary><div><p>Las 32 familias se anclan en la estructura territorial de 2021. Cada sección posterior se asigna al territorio de origen con mayor solapamiento espacial y las secciones hijas se agregan de nuevo para construir la serie longitudinal.</p><ul><li>32 territorios con serie longitudinal completa.</li><li>La asignación espacial mínima entre las secciones anuales y su territorio comparable es del 96,4 %.</li><li>Los totales municipales concilian exactamente.</li><li>No se comparan directamente identificadores de sección 2021–2025.</li></ul></div></details></section>}

export function TerritorialEvolutionStory(){const maxPop=Math.max(...data.municipalTimeline.map(y=>y.population));const top=data.units.slice(0,5);const demographic=[...data.units].map(unit=>{const first=unit.yearly[0],last=unit.yearly[unit.yearly.length-1];return {unit,over65PointChange:100*last.over65/last.population-100*first.over65/first.population}}).sort((a,b)=>Math.abs(b.over65PointChange)-Math.abs(a.over65PointChange))[0];return <section id="territorial-evolution" className="territorial-evolution" aria-labelledby="evolution-title">
  <div className="evolution-opening"><div>{tag("Dato verificado · 2021–2025")}<p>03 · Evolución territorial</p><h2 id="evolution-title">Mijas está cambiando<br/>más rápido en unos territorios<br/>que en otros.</h2><span>La evolución municipal es inequívoca. Para leer su interior, SocTrace reconstruye 32 territorios comparables y evita confundir nuevas secciones con crecimiento real.</span></div></div>
  <div className="evolution-municipal"><div><p>La trayectoria municipal</p><strong>+{integer.format(data.summary.municipalGrowth)}</strong><h3>personas en cuatro años</h3><span>Dato municipal comparable sin ajustes territoriales.</span></div><div className="evolution-timeline">{data.municipalTimeline.map((y,i)=><div key={y.year}><span>{integer.format(y.population)}</span><i style={{height:`${y.population/maxPop*100}%`}}/><small>{y.year}</small>{i<data.municipalTimeline.length-1&&<b/>}</div>)}</div><p className="evolution-timeline-note">La línea municipal es continua. Las secciones no: pasan de 32 a 39 entre 2021 y 2025.</p></div>
  <ComparableTerritories/>
  <div className="evolution-persistence"><header><p>Persistencia frente a movimiento reciente</p><h3>Quince territorios crecen<br/>cada año observado.</h3><span>Los otros 17 alternan crecimiento y descenso. Ningún territorio armonizado registra cuatro descensos consecutivos.</span></header><div className="evolution-classification"><div className="sustained"><strong>{data.summary.sustainedGrowthUnits}</strong><span>Crecimiento sostenido</span><small>4 de 4 años con variación positiva</small></div><div className="volatile"><strong>{data.summary.volatileUnits}</strong><span>Evolución variable</span><small>Al menos un año positivo y uno negativo</small></div><div><strong>{data.summary.sustainedDeclineUnits}</strong><span>Descenso sostenido</span><small>4 de 4 años con variación negativa</small></div></div><div className="evolution-unit-ribbon">{data.units.map(u=><span key={u.id} className={u.classification} title={`${u.label}: ${labels[u.classification]}`}>{u.id.slice(-2)}</span>)}</div></div>
  <div className="evolution-contribution"><header><p>Dónde se crea el crecimiento municipal</p><h3>Casi la mitad del crecimiento se concentra en cinco territorios.</h3><span>{decimal.format(data.summary.topFiveContributionPercent)} % del aumento neto municipal entre 2021 y 2025.</span></header><div>{top.map((u,i)=><article key={u.id}><span>0{i+1}</span><div><h4>{u.label.replace(/^Sección \d+ · /,"")}</h4><i style={{width:`${u.growthContributionPercent/top[0].growthContributionPercent*100}%`}}/></div><strong>+{integer.format(u.cumulativeChange)}</strong><small>{decimal.format(u.growthContributionPercent)} % del crecimiento</small></article>)}</div></div>
  <div className="evolution-findings"><header><p>Transformaciones verificadas</p><h3>Qué cambia y con qué certeza.</h3></header><article><span>01</span><h4>Parque Los Olivos / La Noria lidera el aumento armonizado</h4><strong>+{integer.format(top[0].cumulativeChange)}</strong><p>personas · 2021–2025 · {labels[top[0].classification].toLowerCase()}.</p><small>Fuente: marts.v_poblacion_seccion_anio · Tendencia verificada</small></article><article><span>02</span><h4>El crecimiento persistente no es universal</h4><strong>{data.summary.sustainedGrowthUnits} / {data.method.unitCount}</strong><p>territorios crecen en los cuatro intervalos anuales.</p><small>Familias territoriales 2021 · Tendencia verificada</small></article><article><span>03</span><h4>Las nuevas secciones cambian el mapa operativo</h4><strong>32 → 39</strong><p>secciones oficiales entre 2021 y 2025; no equivalen a siete territorios nuevos.</p><small>core.seccion_historica · Dato verificado</small></article><article><span>04</span><h4>El mayor cambio en el peso de mayores de 65 aparece en {demographic.unit.label.replace(/^Sección \d+ · /,"")}</h4><strong>{demographic.over65PointChange>0?"+":""}{decimal.format(demographic.over65PointChange)} pp</strong><p>variación de su proporción sobre la población del territorio · 2021–2025.</p><small>Bandas de edad armonizadas · Cambio demográfico verificado · No implica comportamiento político</small></article></div>
  <div className="evolution-method"><div><p>Por qué armonizamos</p><h3>Una sección nueva no es población nueva.</h3><span>Cuando un área se divide, el identificador anterior conserva una parte y nace otro identificador. Compararlos como unidades intactas produciría saltos falsos.</span></div><div className="evolution-method-visual"><div><span>2021</span><i>Territorio padre</i></div><b>→</b><div><span>2025</span><i>Sección original</i><i>Sección hija</i></div><b>→</b><div><span>Comparación</span><i>Familia reunificada</i></div></div><footer>{tag("Metodología verificada")}<p>32 familias ancladas en 2021 · asignación por máximo solapamiento PostGIS · confianza espacial mínima {decimal.format(data.quality.minimumSpatialAssignmentPercent)} %.</p><small>Para decisiones operativas de 2027 se usa la geografía oficial 2026 de 41 secciones hasta que exista una delimitación oficial 2027. Para tendencias, se usan las 32 familias armonizadas.</small></footer></div>
  <div className="evolution-implication"><div><p>Interpretación estratégica</p><h3>La campaña de 2027 no se desarrollará sobre el mismo mapa territorial que votó en 2023.</h3><span>La población ha cambiado de peso y la geografía operativa pasó de 37 secciones en 2023 a 41 en 2026. Esto exige actualizar las bases territoriales de trabajo; no implica por sí solo un cambio electoral.</span><a href="#population">Continuar a Población <ArrowDown/></a></div></div>
  <div className="evolution-source-note"><p>Snapshot {data.snapshotVersion} · Fuentes: core.seccion_historica y marts.v_poblacion_seccion_anio.</p><span>Comparabilidad: armonización espacial verificada. Sin causalidad, ideología ni comportamiento inferido. Origen/lugar de nacimiento omitido por cobertura comparable no verificada.</span></div>
</section>}
