import { expect, test } from "@playwright/test";

const member="?auditSession=member&auditAccess=member";
const viewports=[{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1280,height:800},{width:1440,height:900},{width:1600,height:900},{width:1920,height:1080}];

test("executive journey is complete, concise and truthful",async({page})=>{
 await page.goto(`/campaigns/mijas-2027${member}`);
 for(const title of ["Mijas 2027","Mijas no es un único municipio.","Mijas crece con fuerza.","Cinco Mijas diferentes.","Mijas tampoco vota igual.","Entre 2019 y 2023, siete territorios cambiaron de ganador.","En unas zonas vota casi 7 de cada 10 electores. En otras, menos de 4.","Lo intuitivo no siempre es cierto.","37 territorios. 37 historias diferentes.","Ahora diseñemos tu estrategia."]) await expect(page.getByRole("heading",{name:title,exact:true})).toBeAttached();
 await expect(page.locator("#change .exec-changed li")).toHaveCount(7);
 await expect(page.locator("#typologies .exec-type-list article")).toHaveCount(5);
 await expect(page.locator("#territories path[role=button]")).toHaveCount(37);
 const text=await page.locator("main").innerText();
 expect(text.match(/\+7\.764 residentes · \+8,97 %/g)).toHaveLength(1);
 expect(text).not.toMatch(/marts\.|core\.|snapshot 2026|precio de vivienda no cartografiado|coming soon|borrador/i);
 expect(text).toContain("INE · Ministerio del Interior · Catastro · Investigaciones propias de soctrace");
 await expect(page.locator("#structure-vote svg")).toHaveCount(3);
 await expect(page.locator("#representative-territories .exec-locator")).toHaveCount(5);
 await expect(page.locator("#election-chronology article")).toHaveCount(12);
 await expect(page.locator("#change .exec-family-map")).toHaveCount(2);
 await expect(page.getByRole("link",{name:"Diseñar mi campaña con soctrace"})).toHaveAttribute("href","/request-demo?context=Mijas%202027%20Campaign%20Intelligence");
});

test("all priority viewports have no overflow and every critical map has area",async({page})=>{
 for(const viewport of viewports){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}`);const result=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,maps:[...document.querySelectorAll<SVGElement>("#snapshot svg,#typologies svg,#electoral svg,#change svg,#territories svg")].map(x=>{const r=x.getBoundingClientRect();return r.width>0&&r.height>0})}));expect(result.overflow,`${viewport.width}x${viewport.height}`).toBe(false);expect(result.maps.every(Boolean),`${viewport.width}x${viewport.height} map area`).toBe(true)}
});

test("mobile navigation, map selection and progressive disclosure work",async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}`);
 await page.getByRole("button",{name:"Explorar",exact:true}).click();await expect(page.getByRole("dialog",{name:"Explorar el informe"})).toBeVisible();
 await page.getByRole("link",{name:"Perfiles"}).click();await expect(page).toHaveURL(/#territories$/);
 const paths=page.locator("#territories path[role=button]");await paths.nth(1).click();await expect(page.locator("#territories aside h3")).toHaveText("Mijas Este");
 await page.locator("#relationships .exec-explore>button").click();await expect(page.locator(".territorial-relationships")).toBeAttached({timeout:20_000});
});

test("direct URL protection preserves the full location",async({page})=>{await page.goto("/campaigns/mijas-2027?edition=client#territories");await expect(page).toHaveURL(/\/login$/);expect(await page.evaluate(()=>history.state?.usr?.from)).toMatchObject({pathname:"/campaigns/mijas-2027",search:"?edition=client",hash:"#territories"})});

test("print mode hides interaction chrome",async({page})=>{await page.goto(`/campaigns/mijas-2027${member}`);await page.emulateMedia({media:"print"});await expect(page.locator(".exec-header")).toBeHidden();await expect(page.locator(".exec-explore").first()).toBeHidden();await expect(page.getByRole("heading",{name:"Mijas no es un único municipio."})).toBeAttached()});

test("capture executive review set",async({page})=>{test.setTimeout(120_000);const root="docs/review/campaign-intelligence/executive-mobile-mvp";await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}`);const shots:[[string,string],...Array<[string,string]>]=[["#cover","01-mobile-cover"],["#snapshot","02-mobile-snapshot"],["#growth","03-mobile-growth"],["#typologies","04-mobile-typologies"],["#electoral","05-mobile-municipal-2023"],["#change","06-mobile-electoral-change"],["#participation","07-mobile-participation"],["#relationships","08-mobile-relationships"],["#territories","09-mobile-territory-explorer"],["#your-campaign","11-mobile-your-campaign"],[".exec-preview","12-mobile-personalized-preview"],["#final-cta","13-mobile-cta"]];for(const [selector,name] of shots)await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.locator("#territories path[role=button]").nth(1).click();await page.locator("#territories aside").screenshot({path:`${root}/10-mobile-territory-sheet.png`});await page.getByRole("button",{name:"Explorar",exact:true}).click();await page.locator(".exec-drawer").screenshot({path:`${root}/14-mobile-explore-menu.png`});await page.getByRole("button",{name:/Cerrar/}).click();await page.setViewportSize({width:1440,height:900});for(const [selector,name] of [["#cover","15-desktop-cover"],["#snapshot","16-desktop-snapshot"],["#growth","17-desktop-map-spacing"],["#typologies","18-desktop-typology"],["#electoral","19-desktop-electoral"],["#your-campaign","20-desktop-your-campaign"],["#final-cta","21-desktop-cta"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.emulateMedia({media:"print"});await page.locator("#snapshot").screenshot({path:`${root}/22-print-sample.png`})});

test("capture reliability review set",async({page})=>{test.setTimeout(120_000);const root="docs/review/campaign-intelligence/reliability-refactor";await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}`);for(const [selector,name] of [["#growth","01-mobile-growth"],["#snapshot","02-mobile-population-map"],["#typologies>.exec-report-map","03-mobile-five-typologies"],["#structure-vote","04-mobile-structure-vote"],["#election-chronology","05-mobile-election-timeline"],["#electoral .exec-municipal-map","06-mobile-municipal-2023"],["#change","07-mobile-electoral-change"],["#territories","08-mobile-territory-explorer"],["#your-campaign","09-mobile-your-campaign"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1440,height:900});for(const [selector,name] of [["#growth","10-desktop-growth"],["#snapshot","11-desktop-population-map"],["#growth .exec-bars","12-desktop-growth-chart"],["#typologies","13-desktop-five-typologies"],["#structure-vote","14-desktop-structure-vote"],["#representative-territories","15-desktop-representatives"],["#election-chronology","16-desktop-election-chronology"],["#electoral","17-desktop-municipal-2023"],["#change","18-desktop-electoral-change"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1920,height:1080});for(const [selector,name] of [["#snapshot","19-large-population-map"],["#typologies>.exec-report-map","20-large-typology-map"],["#change .exec-family-pair","21-large-electoral-change-maps"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`})});

test("all commercial maps expose fitted visible verified geometry",async({page})=>{for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}`);for(const [selector,count] of [[".exec-map--population",37],[".exec-map--variation",37],["#typologies>.exec-report-map svg",37],["#structure-vote figure:nth-child(1) svg",37],["#structure-vote figure:nth-child(2) svg",37],["#structure-vote figure:nth-child(3) svg",37],[".exec-map--municipal-2023",37],[".exec-family-map--4 svg",28],[".exec-family-map--1 svg",28]] as [string,number][]) {const map=page.locator(selector);await map.scrollIntoViewIfNeeded();await expect(map.locator("path")).toHaveCount(count);const result=await map.evaluate((node:SVGSVGElement)=>{const r=node.getBoundingClientRect(),style=getComputedStyle(node),box=node.getBBox(),view=node.viewBox.baseVal,path=node.querySelector("path");return{width:r.width,height:r.height,left:r.left,right:r.right,display:style.display,opacity:Number(style.opacity),pathD:path?.getAttribute("d")||"",viewport:innerWidth,xRatio:box.width/view.width,yRatio:box.height/view.height}});expect(result.width).toBeGreaterThan(viewport.width>=1024?400:viewport.width*.82);expect(result.height).toBeGreaterThan(220);expect(result.left).toBeGreaterThanOrEqual(0);expect(result.right).toBeLessThanOrEqual(result.viewport+.5);expect(result.display).not.toBe("none");expect(result.opacity).toBeGreaterThan(0);expect(result.pathD.length).toBeGreaterThan(10);expect(Math.max(result.xRatio,result.yRatio)).toBeGreaterThan(.85);expect(Math.min(result.xRatio,result.yRatio)).toBeGreaterThan(.55)}for(const locator of await page.locator("#representative-territories .exec-locator").all()){await expect(locator.locator("path")).toHaveCount(37);const result=await locator.evaluate((node:SVGSVGElement)=>{const r=node.getBoundingClientRect(),b=node.getBBox(),v=node.viewBox.baseVal;return{width:r.width,height:r.height,x:b.width/v.width,y:b.height/v.height,active:node.querySelectorAll("path.active").length}});expect(result.width).toBeGreaterThan(viewport.width>=1024?250:300);expect(result.height).toBeGreaterThan(180);expect(result.active).toBe(1);expect(Math.max(result.x,result.y)).toBeGreaterThan(.85)}expect(await page.locator("#change .exec-changed li").count()).toBe(7)}});

test("capture final map reliability proof",async({page})=>{test.setTimeout(120_000);const root="docs/review/campaign-intelligence/map-reliability-final";await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}`);for(const [selector,name] of [["#growth .exec-bars","01-mobile-municipal-chart"],["#growth .exec-population-map:first-child","02-mobile-population-map"],["#electoral .exec-municipal-summary>h3","03-mobile-municipal-summary"],["#electoral .exec-municipal-map","04-mobile-municipal-map"],[".exec-family-map--4","05-mobile-2019-map"],[".exec-family-map--1","06-mobile-2023-map"],["#change .exec-changed","07-mobile-changed-list"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1440,height:900});for(const [selector,name] of [["#growth","08-desktop-scale-chart-map"],["#electoral","09-desktop-municipal-slide"],["#electoral .exec-municipal-map","10-desktop-municipal-map"],["#change .exec-family-pair","11-desktop-election-comparison"],["#change .exec-changed","12-desktop-changed-list"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1920,height:1080});for(const [selector,name] of [["#growth .exec-population-map:first-child","13-large-population-map"],["#electoral","14-large-municipal"],["#change .exec-family-pair","15-large-election-comparison"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`})});

test("capture final map fix acceptance set",async({page})=>{test.setTimeout(120_000);const root="docs/review/campaign-intelligence/final-map-fix";await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}`);for(const [selector,name] of [[".exec-map--population","01-mobile-population"],[".exec-map--variation","02-mobile-variation"],["#typologies>.exec-report-map","03-mobile-five-families"],["#structure-vote figure:nth-child(1)","04-mobile-structure"],["#structure-vote figure:nth-child(2)","05-mobile-electoral"],["#structure-vote figure:nth-child(3)","06-mobile-integrated"],["#representative-territories article:first-child","07-mobile-representative-group-1"],["#electoral .exec-municipal-summary>h3","08-mobile-municipal-summary"],["#electoral .exec-municipal-map","09-mobile-municipal-map"],[".exec-family-map--4","10-mobile-2019"],[".exec-family-map--1","11-mobile-2023"],["#growth .exec-population-map:first-child","12-mobile-municipal-population"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1440,height:900});for(const [selector,name] of [[".exec-map--population","13-desktop-population"],[".exec-map--variation","14-desktop-variation"],["#typologies>.exec-report-map","15-desktop-five-families"],["#structure-vote","16-desktop-structure-vote"],["#representative-territories","17-desktop-representatives"],["#electoral","18-desktop-municipal-scene"],["#electoral .exec-municipal-map","19-desktop-municipal-map"],["#change .exec-family-pair","20-desktop-comparison"],["#growth .exec-population-map:first-child","21-desktop-municipal-population"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1920,height:1080});for(const [selector,name] of [[".exec-map--population","22-large-population"],["#typologies>.exec-report-map","23-large-five-families"],["#electoral","24-large-municipal"],["#change .exec-family-pair","25-large-comparison"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`})});

test("Municipales 2023 is a flat complete non-interactive report slide",async({page})=>{for(const viewport of viewports){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#municipal-2023-summary`);const section=page.locator("#municipal-2023-summary");await expect(section.getByRole("heading",{name:"PSOE-A y PP quedaron separados por solo 2,03 puntos en el conjunto de Mijas."})).toBeVisible();for(const text of ["33,98 %","PP","2,03 puntos","51,82 %","Las Cañadas","Riviera Norte"])await expect(section.getByText(text,{exact:true}).first()).toBeVisible();await expect(section.locator("button")).toHaveCount(0);await expect(section.locator(".exec-map--municipal-2023 path")).toHaveCount(37);const layout=await section.evaluate(node=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,width:node.getBoundingClientRect().width,mapWidth:node.querySelector("svg")!.getBoundingClientRect().width}));expect(layout.overflow).toBe(false);expect(layout.mapWidth).toBeGreaterThan(Math.min(320,layout.width*.8))}await expect(page.getByText("Una diferencia municipal de 2,0257 puntos.")).toHaveCount(0)});

test("capture flat Municipal 2023 section",async({page})=>{const root="docs/review/campaign-intelligence/municipal-2023-flat";for(const viewport of [{width:390,height:844,name:"mobile-390"},{width:1440,height:900,name:"desktop-1440"},{width:1920,height:1080,name:"desktop-1920"}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#municipal-2023-summary`);await page.locator("#municipal-2023-summary").screenshot({path:`${root}/${viewport.name}.png`})}});

test("municipal map change is a deterministic 28-territory comparison",async({page})=>{for(const viewport of viewports){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#municipal-map-change`);const section=page.locator("#municipal-map-change"),maps=section.locator(".exec-family-map svg");await expect(maps).toHaveCount(2);await expect(section.locator(".exec-changed li")).toHaveCount(7);await expect(section.getByText("Para comparar ambas elecciones, soctrace agrupa las secciones en 28 territorios equivalentes y evita comparar directamente límites censales que cambiaron entre convocatorias.",{exact:true})).toBeVisible();await expect(section.getByText("7 de 28 territorios cambiaron de ganador.",{exact:true})).toBeVisible();await expect(section.getByText("El 25 % de los territorios comparables cambió de fuerza ganadora.",{exact:true})).toBeVisible();const geometry:string[][]=[];for(const map of await maps.all()){await expect(map.locator("path")).toHaveCount(28);await expect(map.locator("path.changed")).toHaveCount(7);const result=await map.evaluate((node:SVGSVGElement)=>{const r=node.getBoundingClientRect(),b=node.getBBox(),v=node.viewBox.baseVal;return{width:r.width,height:r.height,x:b.width/v.width,y:b.height/v.height,d:[...node.querySelectorAll("path")].map(path=>path.getAttribute("d")||"")}});expect(result.width).toBeGreaterThan(viewport.width>=1024?400:viewport.width*.8);expect(result.height).toBeGreaterThan(220);expect(Math.max(result.x,result.y)).toBeGreaterThan(.85);expect(Math.min(result.x,result.y)).toBeGreaterThan(.55);expect(result.d.every(d=>d.length>10)).toBe(true);geometry.push(result.d)}expect(geometry[0]).toEqual(geometry[1]);expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)}});

test("capture municipal map change review set",async({page})=>{test.setTimeout(120_000);const root="docs/review/campaign-intelligence/municipal-map-change-fix";await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}#municipal-map-change`);await page.locator(".exec-header,.campaign-progress").evaluateAll(nodes=>nodes.forEach(node=>(node as HTMLElement).style.visibility="hidden"));for(const [selector,name] of [["#municipal-map-change","01-mobile-complete"],[".exec-family-map--4","02-mobile-2019"],[".exec-family-map--1","03-mobile-2023"],["#municipal-map-change .exec-changed","04-mobile-changed-territories"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1440,height:900});for(const [selector,name] of [["#municipal-map-change","05-desktop-complete"],["#municipal-map-change .exec-family-pair","06-desktop-map-comparison"],["#municipal-map-change .exec-changed","07-desktop-changed-territories"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1920,height:1080});await page.locator("#municipal-map-change").screenshot({path:`${root}/08-large-complete.png`})});

test("comparable territories renders 32 real harmonised geometries",async({page})=>{test.setTimeout(120_000);for(const viewport of viewports){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#growth`);await page.reload();await page.getByRole("button",{name:"Explorar la evolución territorial →",exact:true}).click();const section=page.locator("#comparable-territories"),map=section.locator(".evolution-comparable-map svg");await expect(section.getByRole("heading",{name:"32 territorios comparables a través del tiempo"})).toBeVisible();await expect(map.locator("path")).toHaveCount(32);const result=await map.evaluate((node:SVGSVGElement)=>{const r=node.getBoundingClientRect(),b=node.getBBox(),v=node.viewBox.baseVal,paths=[...node.querySelectorAll("path")];return{width:r.width,height:r.height,x:b.width/v.width,y:b.height/v.height,paths:paths.map(path=>({d:path.getAttribute("d")||"",fill:getComputedStyle(path).fill,stroke:getComputedStyle(path).stroke,opacity:getComputedStyle(path).opacity}))}});expect(result.width).toBeGreaterThan(viewport.width>=1024?500:viewport.width*.8);expect(result.height).toBeGreaterThanOrEqual(viewport.width>=1024?300:220);expect(Math.max(result.x,result.y)).toBeGreaterThan(.85);expect(Math.min(result.x,result.y)).toBeGreaterThan(.55);expect(result.paths.every(path=>path.d.length>10&&path.fill!=="none"&&path.stroke!=="none"&&Number(path.opacity)>0)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);for(const text of ["2021","2022","2023","2024","2025","Sección 026","Sección 028","Sección 018","Sección 024","La asignación espacial mínima entre las secciones anuales y su territorio comparable es del 96,4 %."])await expect(section.getByText(text,{exact:true}).first()).toBeAttached()}});

test("capture comparable territories review set",async({page})=>{test.setTimeout(240_000);const root="docs/review/campaign-intelligence/comparable-territories-fix",open=async(width:number,height:number)=>{await page.setViewportSize({width,height});await page.goto(`/campaigns/mijas-2027${member}#growth`);await page.reload();await page.getByRole("button",{name:"Explorar la evolución territorial →",exact:true}).click();await page.locator("#comparable-territories").scrollIntoViewIfNeeded();await page.locator(".exec-header,.campaign-progress").evaluateAll(nodes=>nodes.forEach(node=>(node as HTMLElement).style.visibility="hidden"))};await open(390,844);for(const [selector,name] of [["#comparable-territories","01-mobile-complete"],["#comparable-territories .evolution-comparable-map","02-mobile-map"],["#comparable-territories .evolution-harmonisation","03-mobile-harmonisation"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await open(1440,900);for(const [selector,name] of [["#comparable-territories","04-desktop-complete"],["#comparable-territories .evolution-comparable-map","05-desktop-map"],["#comparable-territories .evolution-harmonisation","06-desktop-split-method"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await open(1920,1080);await page.locator("#comparable-territories").screenshot({path:`${root}/07-large-complete.png`})});

test("five territorial families renders all 37 verified sections initially",async({page})=>{test.setTimeout(180_000);for(const viewport of viewports){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#typologies`);await page.reload();await page.locator("#typologies .exec-explore>button").click();const section=page.locator("#five-families-map"),map=section.locator(".typology-static-map svg"),paths=map.locator("path");await expect(section.getByRole("heading",{name:/37 secciones\.\s*Cinco lecturas compartidas\./})).toBeVisible();await expect(paths).toHaveCount(37);await expect(section.locator(".typology-static-legend>div")).toHaveCount(5);await expect(section.locator(".typology-family-summaries>article")).toHaveCount(5);await expect(section.locator("button")).toHaveCount(0);const result=await map.evaluate((node:SVGSVGElement)=>{const r=node.getBoundingClientRect(),b=node.getBBox(),v=node.viewBox.baseVal,paths=[...node.querySelectorAll<SVGPathElement>("path")],groups=new Set(paths.map(path=>path.dataset.group)),ids=paths.map(path=>path.dataset.sectionId);return{width:r.width,height:r.height,x:b.width/v.width,y:b.height/v.height,groups:[...groups],ids,paths:paths.map(path=>({d:path.getAttribute("d")||"",fill:getComputedStyle(path).fill,opacity:Number(getComputedStyle(path).opacity)}))}});expect(result.width).toBeGreaterThan(viewport.width>=1024?500:viewport.width*.8);expect(result.height).toBeGreaterThanOrEqual(viewport.width>=1024?300:240);expect(Math.max(result.x,result.y)).toBeGreaterThan(.7);expect(Math.min(result.x,result.y)).toBeGreaterThan(.5);expect(result.ids.filter(Boolean)).toHaveLength(37);expect(new Set(result.ids).size).toBe(37);expect(result.groups.sort()).toEqual(["Group 1","Group 2","Group 3","Group 4","Group 5"]);expect(result.paths.every(path=>path.d.length>10&&path.fill!=="none"&&path.opacity===1)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)}});

test("capture five families map review set",async({page})=>{test.setTimeout(240_000);const root="docs/review/campaign-intelligence/five-families-map-fix",open=async(width:number,height:number)=>{await page.setViewportSize({width,height});await page.goto(`/campaigns/mijas-2027${member}#typologies`);await page.reload();await page.locator("#typologies .exec-explore>button").click();await page.locator("#five-families-map").scrollIntoViewIfNeeded();await page.locator(".exec-header,.campaign-progress").evaluateAll(nodes=>nodes.forEach(node=>(node as HTMLElement).style.visibility="hidden"))};await open(390,844);for(const [selector,name] of [["#five-families-map","01-mobile-complete"],["#five-families-map .typology-static-map","02-mobile-map"],["#five-families-map","03-mobile-map-legend"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await open(1440,900);for(const [selector,name] of [["#five-families-map","04-desktop-complete"],["#five-families-map .typology-static-map","05-desktop-map"],["#five-families-map .typology-family-summaries","06-desktop-family-summaries"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await open(1920,1080);await page.locator("#five-families-map").screenshot({path:`${root}/07-large-complete.png`})});
