import { expect, test } from "@playwright/test";

const member="?auditSession=member&auditAccess=member";
const viewports=[{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1280,height:800},{width:1440,height:900},{width:1600,height:900},{width:1920,height:1080}];

test("executive journey is complete, concise and truthful",async({page})=>{
 await page.goto(`/campaigns/mijas-2027${member}`);
 for(const title of ["Mijas 2027","Mijas no es un único municipio.","Mijas crece con fuerza.","Cinco Mijas diferentes.","Mijas tampoco vota igual.","Entre 2019 y 2023, siete territorios cambiaron de ganador.","Lo intuitivo no siempre es cierto.","Todo el territorio, todas las métricas, en un único Dashboard."]) await expect(page.getByRole("heading",{name:title,exact:true})).toBeAttached();
 await expect(page.locator("#change .exec-changed li")).toHaveCount(7);
 await expect(page.locator("#typologies .exec-type-list article")).toHaveCount(5);
 const text=await page.locator("main").innerText();
 expect(text.match(/\+7\.764 residentes · \+8,97 %/g)).toHaveLength(1);
 expect(text).not.toMatch(/marts\.|core\.|snapshot 2026|precio de vivienda no cartografiado|coming soon|borrador/i);
 expect(text).toContain("INE · Ministerio del Interior · Catastro · Investigaciones propias de soctrace");
 await expect(page.locator("#structure-vote svg")).toHaveCount(3);
 await expect(page.locator("#representative-territories .exec-locator")).toHaveCount(5);
 await expect(page.locator("#election-chronology [role=tab]")).toHaveCount(12);
 await expect(page.locator("#change .exec-family-map")).toHaveCount(2);
 await expect(page.getByRole("link",{name:"Solicitar acceso al Dashboard"})).toHaveAttribute("href","https://soctrace.ai/request-demo");
});

test("campaign cover leads with three strategic questions and the report CTA",async({page})=>{
 test.setTimeout(120_000);
 const questions=["¿Dónde se decidió realmente la victoria del PSOE en 2023?","¿Qué territorios pueden cambiar el equilibrio político de Mijas en 2027?","¿Dónde existe más espacio para una candidatura alternativa a PP y PSOE?"];
 for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1440,height:900},{width:1920,height:1080}]){
  await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}`);const cover=page.locator("#cover"),cta=cover.getByRole("link",{name:"Accede al informe pre-electoral",exact:true});
  await expect(cover.getByRole("heading",{name:"Mijas 2027",exact:true})).toBeVisible();await expect(cover.locator(".exec-cover-questions li")).toHaveCount(3);for(const question of questions)await expect(cover.getByText(question,{exact:true})).toBeVisible();await expect(cta).toHaveAttribute("href","#snapshot");
  for(const removed of ["Campaign Intelligence","Inteligencia territorial y electoral para comprender cómo cambia el municipio, cómo se comporta electoralmente y qué diferencias existen entre sus territorios.","94.320 residentes · 41 secciones electorales actuales · 12 procesos electorales analizados","Descubrir Mijas"])await expect(cover.getByText(removed,{exact:true})).toHaveCount(0);
  const layout=await cover.evaluate((node,viewportHeight)=>{const coverBox=node.getBoundingClientRect(),cta=node.querySelector<HTMLAnchorElement>(".exec-cover-content>a")!.getBoundingClientRect(),items=[...node.querySelectorAll<HTMLElement>(".exec-cover-questions li")].map(item=>item.getBoundingClientRect());return{overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,coverLeft:coverBox.left,coverRight:coverBox.right,ctaBottom:cta.bottom,ctaHeight:cta.height,clipped:items.some(item=>item.left<0||item.right>innerWidth||item.top<0||item.bottom>viewportHeight)}} ,viewport.height);expect(layout.overflow).toBe(false);expect(layout.coverLeft).toBeGreaterThanOrEqual(0);expect(layout.coverRight).toBeLessThanOrEqual(viewport.width+.5);expect(layout.ctaBottom).toBeLessThanOrEqual(viewport.height+.5);expect(layout.ctaHeight).toBeGreaterThanOrEqual(48);expect(layout.clipped).toBe(false);
 }
});

test("final commercial module presents the analytical Dashboard and access request",async({page})=>{
 test.setTimeout(120_000);
 const capabilities=["Proyección de voto","Renta","Inteligencia inmobiliaria","Población y crecimiento","Edad y estructura demográfica","Participación y comportamiento electoral"];
 for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1440,height:900},{width:1920,height:1080}]){
  await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#final-cta`);const section=page.locator("#final-cta"),image=section.getByRole("img",{name:"Dashboard analítico de soctrace con métricas territoriales, socioeconómicas y electorales de Mijas"}),primary=section.getByRole("link",{name:"Solicitar acceso al Dashboard"}),email=section.getByRole("link",{name:"soctrace@gmail.com"});
  await expect(section.getByRole("heading",{name:"Todo el territorio, todas las métricas, en un único Dashboard.",exact:true})).toBeVisible();await expect(image).toBeVisible();for(const capability of capabilities)await expect(section.getByText(capability,{exact:true})).toBeVisible();await expect(primary).toHaveAttribute("href","https://soctrace.ai/request-demo");await expect(email).toHaveAttribute("href","mailto:soctrace@gmail.com");
  for(const removed of ["Ahora diseñemos tu estrategia.","Diseñar mi campaña con soctrace","Solicitar una sesión estratégica"])await expect(section.getByText(removed,{exact:true})).toHaveCount(0);await expect(section.locator('a[href*="dashboard" i],a[href*="//request-demo"]')).toHaveCount(0);
  const layout=await section.evaluate((node,width)=>{const sectionBox=node.getBoundingClientRect(),imageBox=node.querySelector("img")!.getBoundingClientRect(),image=node.querySelector<HTMLImageElement>("img")!;return{overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,sectionLeft:sectionBox.left,sectionRight:sectionBox.right,imageWidth:imageBox.width,naturalWidth:image.naturalWidth,naturalHeight:image.naturalHeight,source:image.currentSrc,width}} ,viewport.width);expect(layout.overflow).toBe(false);expect(layout.sectionLeft).toBeGreaterThanOrEqual(0);expect(layout.sectionRight).toBeLessThanOrEqual(viewport.width+.5);expect(layout.imageWidth).toBeGreaterThanOrEqual(viewport.width<1024?viewport.width-38:viewport.width*.44);expect(layout.naturalWidth).toBe(1829);expect(layout.naturalHeight).toBe(909);expect(layout.source).not.toContain("/Users/");
 }
});

test("all priority viewports have no overflow and every critical map has area",async({page})=>{
 for(const viewport of viewports){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}`);const result=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,maps:[...document.querySelectorAll<SVGElement>("#snapshot svg,#typologies svg,#electoral svg,#change svg")].map(x=>{const r=x.getBoundingClientRect();return r.width>0&&r.height>0})}));expect(result.overflow,`${viewport.width}x${viewport.height}`).toBe(false);expect(result.maps.every(Boolean),`${viewport.width}x${viewport.height} map area`).toBe(true)}
});

test("mobile navigation and progressive disclosure work",async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}`);
 await page.getByRole("button",{name:"Explorar",exact:true}).click();await expect(page.getByRole("dialog",{name:"Explorar el informe"})).toBeVisible();
 await expect(page.getByRole("link",{name:"Perfiles"})).toHaveCount(0);await page.getByRole("link",{name:"Tipologías"}).click();await expect(page).toHaveURL(/#typologies$/);
 await page.locator("#relationships .exec-explore>button").click();await expect(page.locator(".territorial-relationships")).toBeAttached({timeout:20_000});
});

test("client cleanup removes redundant relationship evidence and municipal evolution",async({page})=>{
 test.setTimeout(180_000);await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}`);
 await page.locator("#relationships .exec-explore>button").click();const relationships=page.locator(".territorial-relationships");await expect(relationships).toBeAttached({timeout:20_000});await expect(relationships.locator(".relations-education").getByText("Abrir perfil territorial",{exact:true})).toHaveCount(0);
 await page.locator("#growth .exec-explore>button").click();const evolution=page.locator(".territorial-evolution");await expect(evolution).toBeAttached({timeout:20_000});await expect(evolution.locator(".evolution-municipal,.evolution-timeline,.evolution-timeline-note")).toHaveCount(0);await expect(evolution.getByText("Familias territoriales comparables",{exact:true})).toBeVisible();await expect(evolution.getByRole("heading",{name:"32 territorios comparables a través del tiempo",exact:true})).toBeVisible();expect(await evolution.locator(":scope > .evolution-opening + .evolution-comparable").count()).toBe(1);await expect(evolution.getByText("+7.764",{exact:true})).toHaveCount(0);
 for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);const layout=await evolution.evaluate(node=>{const opening=node.querySelector<HTMLElement>(".evolution-opening")!.getBoundingClientRect(),comparable=node.querySelector<HTMLElement>(".evolution-comparable")!.getBoundingClientRect();return{overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,siblingGap:comparable.top-opening.bottom}});expect(layout.overflow).toBe(false);expect(Math.abs(layout.siblingGap)).toBeLessThan(2)}
});

test("relationship exploration opens directly on the first analytical module",async({page})=>{test.setTimeout(180_000);for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}`,{waitUntil:"networkidle"});const opener=page.locator("#relationships .exec-explore>button");await opener.scrollIntoViewIfNeeded();await opener.press("Enter");const story=page.locator(".territorial-relationships"),education=story.locator(".relations-education"),tabs=education.locator(".relations-party-tabs");await expect(story).toBeAttached({timeout:20_000});await expect(story.locator(".relations-opening,.relations-causality")).toHaveCount(0);for(const removed of ["08 · Relaciones territoriales","Coincidir no significa explicar.","01 · Asociación y explicación","Dos variables pueden moverse juntas sin que una cause la otra.","Asociación observada","Relación ajustada","Explicación causal"])await expect(story.getByText(removed,{exact:true})).toHaveCount(0);await expect(education.locator("header span").first()).toHaveText("La relación más consistente");await expect(story.getByText("02 · La relación más consistente",{exact:true})).toHaveCount(0);await expect(education.getByRole("heading",{name:"Estudios superiores y distribución territorial del voto.",exact:true})).toBeVisible();await expect(education.locator(".relations-scatter circle")).toHaveCount(37);await expect(tabs.getByRole("button",{name:"PP",exact:true})).toHaveClass(/active/);await tabs.getByRole("button",{name:"PSOE",exact:true}).click();await expect(tabs.getByRole("button",{name:"PSOE",exact:true})).toHaveClass(/active/);const layout=await story.evaluate(node=>{const first=node.firstElementChild as HTMLElement,box=first.getBoundingClientRect(),style=getComputedStyle(first);return{firstClass:first.classList.contains("relations-education"),minHeight:style.minHeight,topPadding:parseFloat(style.paddingTop),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,width:box.width}});expect(layout.firstClass).toBe(true);expect(layout.minHeight).toBe("0px");expect(layout.topPadding).toBeLessThanOrEqual(80);expect(layout.overflow).toBe(false);expect(layout.width).toBeLessThanOrEqual(viewport.width+.5)}});

test("obsolete profile journeys and housing summary are absent without breaking retained flow",async({page})=>{test.setTimeout(180_000);for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}&territory=2907001002#target-profiles`);await expect(page.getByRole("heading",{name:"Mijas 2027",exact:true})).toBeAttached();await expect(page.locator("#territories,#target-profiles,.territorial-profiles,.territory-explorer,.territory-profile-header,#built,#population,.municipal-profile")).toHaveCount(0);for(const copy of ["Explora cualquier territorio","37 territorios. 37 historias diferentes.","Toca cualquier sección para conocerla.","Ver perfil completo →","Abrir perfil completo","Vivienda y territorio","La forma de vivir también dibuja Mijas.","Radiografía municipal","Un municipio, múltiples realidades territoriales.","Continuar al diagnóstico electoral"])await expect(page.getByText(copy,{exact:true})).toHaveCount(0);await expect(page.locator('a[href*="territory="],a[href="#territories"],a[href="#target-profiles"],a[href="#built"],a[href="#population"]')).toHaveCount(0);await expect(page.getByRole("heading",{name:"Cinco Mijas diferentes.",exact:true})).toBeAttached();await expect(page.getByRole("heading",{name:"Lo intuitivo no siempre es cierto.",exact:true})).toBeAttached();await expect(page.getByRole("heading",{name:"Todo el territorio, todas las métricas, en un único Dashboard.",exact:true})).toBeAttached();const flow=await page.evaluate(()=>({relationshipsNext:document.querySelector("#relationships")?.nextElementSibling?.id,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth}));expect(flow).toEqual({relationshipsNext:"your-campaign",overflow:false})}});

test("territorial evolution implication ends without a population continuation control",async({page})=>{
 test.setTimeout(180_000);
 for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900}]){
  await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#growth`);await page.reload();await page.getByRole("button",{name:"Explorar la evolución territorial",exact:true}).click();
  const implication=page.locator(".evolution-implication");await expect(implication.getByRole("heading",{name:"La campaña de 2027 no se desarrollará sobre el mismo mapa territorial que votó en 2023.",exact:true})).toBeAttached();await expect(implication.getByText("Continuar a Población",{exact:true})).toHaveCount(0);await expect(implication.locator("a,svg")).toHaveCount(0);
  const layout=await implication.evaluate(node=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,actions:node.querySelectorAll("a,button").length,childCount:node.firstElementChild?.childElementCount}));expect(layout).toEqual({overflow:false,actions:0,childCount:3});
 }
});

test("territory exploration flows directly from municipality introduction to population maps",async({page})=>{
 test.setTimeout(180_000);
 for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1440,height:900},{width:1920,height:1080}]){
  await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#snapshot`);await page.reload();await page.getByRole("button",{name:/Explorar el territorio/}).click();
  const story=page.locator(".municipality-story"),premise=story.locator(".municipality-premise"),maps=story.locator(".municipality-map-story");await expect(story).toBeAttached({timeout:15_000});
  await expect(premise.getByText("02 · El municipio",{exact:true})).toBeVisible();await expect(premise.getByRole("heading",{name:/Mijas crece, pero no crece igual en todo su territorio\./})).toBeVisible();await expect(premise).toContainText("El crecimiento municipal está verificado. Las diferencias territoriales se muestran en el último periodo con secciones comparables.");
  await expect(story.getByText("Evolución municipal",{exact:true})).toHaveCount(0);await expect(story.getByText("personas entre 2021 y 2025",{exact:true})).toHaveCount(0);await expect(story.locator(".municipality-evolution,.municipality-evolution-line")).toHaveCount(0);
  for(const removed of ["Interpretación estratégica","Un único mensaje municipal no será suficiente.","Esta es una interpretación derivada de contrastes territoriales verificados. No es todavía una recomendación electoral.","Continuar a la evolución territorial"])await expect(story.getByText(removed,{exact:true})).toHaveCount(0);await expect(story.locator(".municipality-implication")).toHaveCount(0);expect(await story.evaluate(node=>node.lastElementChild?.classList.contains("municipality-realities"))).toBe(true);
  expect(await premise.evaluate(node=>node.nextElementSibling?.classList.contains("municipality-map-story"))).toBe(true);await expect(maps.getByText("Población por sección",{exact:true})).toBeAttached();await expect(maps.locator(".municipality-map-svg path")).toHaveCount(37);
  const layout=await story.evaluate(node=>{const premise=node.querySelector<HTMLElement>(".municipality-premise")!.getBoundingClientRect(),maps=node.querySelector<HTMLElement>(".municipality-map-story")!.getBoundingClientRect();return{overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,gap:maps.top-premise.bottom}});expect(layout.overflow).toBe(false);expect(Math.abs(layout.gap)).toBeLessThan(2);
 }
});

test("Scene 10 residual locator is visible, selectable and has no profile link",async({page})=>{
 test.setTimeout(120_000);
 for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1440,height:900},{width:1920,height:1080}]){
  await page.setViewportSize(viewport);await page.goto("/campaigns/mijas-2027",{waitUntil:"networkidle"});
  const opener=page.locator("#relationships .exec-explore>button");await opener.scrollIntoViewIfNeeded();await opener.press("Enter");
  const scene=page.locator(".relations-residuals");await expect(scene).toBeAttached({timeout:20_000});await scene.scrollIntoViewIfNeeded();
  const frame=scene.locator(".relations-residual-map-frame"),map=frame.locator("svg");await expect(map.locator("path")).toHaveCount(37);
  const initial=await frame.getAttribute("data-selected-section");expect(initial).toBeTruthy();await expect(scene.locator('aside button[aria-pressed="true"]')).toHaveCount(1);
  const dimensions=await frame.evaluate(node=>{const frame=node.getBoundingClientRect(),svg=node.querySelector("svg")!.getBoundingClientRect(),paths=[...node.querySelectorAll<SVGPathElement>("path")];return{frameWidth:frame.width,frameHeight:frame.height,svgWidth:svg.width,svgHeight:svg.height,pathData:paths.every(path=>(path.getAttribute("d")||"").length>10),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth}});
  expect(dimensions.frameWidth).toBeGreaterThanOrEqual(viewport.width>=1024?550:viewport.width*.8);expect(dimensions.frameHeight).toBeGreaterThanOrEqual(viewport.width>=1024?320:260);expect(dimensions.svgWidth).toBeGreaterThan(0);expect(dimensions.svgHeight).toBeGreaterThan(0);expect(dimensions.pathData).toBe(true);expect(dimensions.overflow).toBe(false);
  const next=scene.locator("aside nav>button").nth(1),nextId=await next.getAttribute("data-section-id");await next.click();await expect(frame).not.toHaveAttribute("data-selected-section",initial!);await expect(scene.locator('aside button[aria-pressed="true"]')).toHaveCount(1);expect(await frame.getAttribute("data-selected-section")).not.toBe(initial);if(nextId)await expect(frame).toHaveAttribute("data-selected-section",nextId);
  await expect(scene.getByRole("link",{name:"Abrir perfil completo"})).toHaveCount(0);
 }
});

test("structure, electoral and integrated classifications render as three fitted maps",async({page})=>{
 test.setTimeout(240_000);const review="docs/review/campaign-intelligence/structure-vote-map-fix";
 for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1280,height:800},{width:1440,height:900},{width:1600,height:900},{width:1920,height:1080}]){
  await page.setViewportSize(viewport);await page.goto("/campaigns/mijas-2027",{waitUntil:"networkidle"});const opener=page.locator("#typologies .exec-explore>button");await opener.scrollIntoViewIfNeeded();await opener.press("Enter");
  const scene=page.locator(".typology-views");await expect(scene).toBeAttached({timeout:20_000});await scene.scrollIntoViewIfNeeded();const maps=scene.locator(".typology-analytical-map");await expect(maps).toHaveCount(3);const boxes:string[]=[];
  for(const view of ["structural","electoral","integrated"]){const map=scene.locator(`[data-analytical-view="${view}"]`);await expect(map.locator("path")).toHaveCount(37);const result=await map.evaluate((node:SVGSVGElement)=>{const rect=node.getBoundingClientRect(),box=node.getBBox(),frame=node.viewBox.baseVal,paths=[...node.querySelectorAll<SVGPathElement>("path")];return{width:rect.width,height:rect.height,box:[box.x,box.y,box.width,box.height].map(x=>x.toFixed(2)).join("|"),xRatio:box.width/frame.width,yRatio:box.height/frame.height,ids:paths.map(path=>path.dataset.sectionId),valid:paths.every(path=>(path.getAttribute("d")||"").length>10&&path.dataset.group&&getComputedStyle(path).fill!=="none"&&Number(getComputedStyle(path).opacity)>0),clipped:rect.left<0||rect.right>innerWidth+.5}});expect(result.width).toBeGreaterThan(viewport.width<540?viewport.width*.78:viewport.width>=1200?500:viewport.width*.7);expect(result.height).toBeGreaterThanOrEqual(260);expect(result.xRatio).toBeGreaterThan(.7);expect(result.yRatio).toBeGreaterThan(.8);expect(result.valid).toBe(true);expect(result.clipped).toBe(false);expect(new Set(result.ids).size).toBe(37);boxes.push(result.box)}
  expect(new Set(boxes).size).toBe(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);
  if(viewport.width===390){await scene.locator('[data-view="integrated"]').screenshot({path:`${review}/01-mobile-integrated.png`});await scene.locator('[data-view="structural"]').screenshot({path:`${review}/02-mobile-structural.png`});await scene.locator('[data-view="electoral"]').screenshot({path:`${review}/03-mobile-electoral.png`})}
  if(viewport.width===1440){await scene.screenshot({path:`${review}/04-desktop-complete.png`});await scene.locator('[data-view="structural"]').screenshot({path:`${review}/05-desktop-structural.png`});await scene.locator('[data-view="electoral"]').screenshot({path:`${review}/06-desktop-electoral.png`});await scene.locator('[data-view="integrated"]').screenshot({path:`${review}/07-desktop-integrated.png`})}
  if(viewport.width===1920)await scene.screenshot({path:`${review}/08-large-complete.png`});
 }
});

test("logged-out direct URL and refresh render the public Mijas report",async({browser})=>{const context=await browser.newContext();const page=await context.newPage();await page.goto("/campaigns/mijas-2027");await expect(page.getByRole("heading",{name:"Mijas 2027",exact:true})).toBeVisible();await expect(page).toHaveURL(/\/campaigns\/mijas-2027$/);await expect(page.locator('meta[name="robots"]')).toHaveAttribute("content","noindex, nofollow");await page.reload();await expect(page.getByRole("heading",{name:"Mijas 2027",exact:true})).toBeVisible();await expect(page).toHaveURL(/\/campaigns\/mijas-2027$/);await context.close()});

test("an arbitrary campaign does not inherit public access",async({page})=>{await page.goto("/campaigns/non-public-campaign");await expect(page).toHaveURL(/\/login$/)});

test("public marketing navigation does not link the Mijas report",async({page})=>{await page.goto("/");await expect(page.locator('a[href="/campaigns/mijas-2027"]')).toHaveCount(0)});

test("print mode hides interaction chrome",async({page})=>{await page.goto(`/campaigns/mijas-2027${member}`);await page.emulateMedia({media:"print"});await expect(page.locator(".exec-header")).toBeHidden();await expect(page.locator(".exec-explore").first()).toBeHidden();await expect(page.getByRole("heading",{name:"Mijas no es un único municipio."})).toBeAttached()});

test("capture executive review set",async({page})=>{test.setTimeout(120_000);const root="docs/review/campaign-intelligence/executive-mobile-mvp";await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}`);const shots:[[string,string],...Array<[string,string]>]=[["#cover","01-mobile-cover"],["#snapshot","02-mobile-snapshot"],["#growth","03-mobile-growth"],["#typologies","04-mobile-typologies"],["#electoral","05-mobile-municipal-2023"],["#change","06-mobile-electoral-change"],["#relationships","08-mobile-relationships"],["#your-campaign","11-mobile-your-campaign"],[".exec-preview","12-mobile-personalized-preview"],["#final-cta","13-mobile-cta"]];for(const [selector,name] of shots)await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.getByRole("button",{name:"Explorar",exact:true}).click();await page.locator(".exec-drawer").screenshot({path:`${root}/14-mobile-explore-menu.png`});await page.getByRole("button",{name:/Cerrar/}).click();await page.setViewportSize({width:1440,height:900});for(const [selector,name] of [["#cover","15-desktop-cover"],["#snapshot","16-desktop-snapshot"],["#growth","17-desktop-map-spacing"],["#typologies","18-desktop-typology"],["#electoral","19-desktop-electoral"],["#your-campaign","20-desktop-your-campaign"],["#final-cta","21-desktop-cta"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.emulateMedia({media:"print"});await page.locator("#snapshot").screenshot({path:`${root}/22-print-sample.png`})});

test("capture reliability review set",async({page})=>{test.setTimeout(120_000);const root="docs/review/campaign-intelligence/reliability-refactor";await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}`);for(const [selector,name] of [["#growth","01-mobile-growth"],["#snapshot","02-mobile-population-map"],["#typologies>.exec-report-map","03-mobile-five-typologies"],["#structure-vote","04-mobile-structure-vote"],["#election-chronology","05-mobile-election-timeline"],["#electoral .exec-municipal-map","06-mobile-municipal-2023"],["#change","07-mobile-electoral-change"],["#your-campaign","09-mobile-your-campaign"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1440,height:900});for(const [selector,name] of [["#growth","10-desktop-growth"],["#snapshot","11-desktop-population-map"],["#growth .exec-bars","12-desktop-growth-chart"],["#typologies","13-desktop-five-typologies"],["#structure-vote","14-desktop-structure-vote"],["#representative-territories","15-desktop-representatives"],["#election-chronology","16-desktop-election-chronology"],["#electoral","17-desktop-municipal-2023"],["#change","18-desktop-electoral-change"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1920,height:1080});for(const [selector,name] of [["#snapshot","19-large-population-map"],["#typologies>.exec-report-map","20-large-typology-map"],["#change .exec-family-pair","21-large-electoral-change-maps"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`})});

test("all commercial maps expose fitted visible verified geometry",async({page})=>{for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}`);for(const [selector,count] of [[".exec-map--population",37],[".exec-map--variation",37],["#typologies>.exec-report-map svg",37],["#structure-vote figure:nth-child(1) svg",37],["#structure-vote figure:nth-child(2) svg",37],["#structure-vote figure:nth-child(3) svg",37],[".exec-map--municipal-2023",37],[".exec-family-map--4 svg",28],[".exec-family-map--1 svg",28]] as [string,number][]) {const map=page.locator(selector);await map.scrollIntoViewIfNeeded();await expect(map.locator("path")).toHaveCount(count);const result=await map.evaluate((node:SVGSVGElement)=>{const r=node.getBoundingClientRect(),style=getComputedStyle(node),box=node.getBBox(),view=node.viewBox.baseVal,path=node.querySelector("path");return{width:r.width,height:r.height,left:r.left,right:r.right,display:style.display,opacity:Number(style.opacity),pathD:path?.getAttribute("d")||"",viewport:innerWidth,xRatio:box.width/view.width,yRatio:box.height/view.height}});expect(result.width).toBeGreaterThan(viewport.width>=1024?400:viewport.width*.82);expect(result.height).toBeGreaterThan(220);expect(result.left).toBeGreaterThanOrEqual(0);expect(result.right).toBeLessThanOrEqual(result.viewport+.5);expect(result.display).not.toBe("none");expect(result.opacity).toBeGreaterThan(0);expect(result.pathD.length).toBeGreaterThan(10);expect(Math.max(result.xRatio,result.yRatio)).toBeGreaterThan(.85);expect(Math.min(result.xRatio,result.yRatio)).toBeGreaterThan(.55)}for(const locator of await page.locator("#representative-territories .exec-locator").all()){await expect(locator.locator("path")).toHaveCount(37);const result=await locator.evaluate((node:SVGSVGElement)=>{const r=node.getBoundingClientRect(),b=node.getBBox(),v=node.viewBox.baseVal;return{width:r.width,height:r.height,x:b.width/v.width,y:b.height/v.height,active:node.querySelectorAll("path.active").length}});expect(result.width).toBeGreaterThan(viewport.width>=1024?250:300);expect(result.height).toBeGreaterThan(180);expect(result.active).toBe(1);expect(Math.max(result.x,result.y)).toBeGreaterThan(.85)}expect(await page.locator("#change .exec-changed li").count()).toBe(7)}});

test("capture final map reliability proof",async({page})=>{test.setTimeout(120_000);const root="docs/review/campaign-intelligence/map-reliability-final";await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}`);for(const [selector,name] of [["#growth .exec-bars","01-mobile-municipal-chart"],["#growth .exec-population-map:first-child","02-mobile-population-map"],["#electoral .exec-municipal-summary>h3","03-mobile-municipal-summary"],["#electoral .exec-municipal-map","04-mobile-municipal-map"],[".exec-family-map--4","05-mobile-2019-map"],[".exec-family-map--1","06-mobile-2023-map"],["#change .exec-changed","07-mobile-changed-list"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1440,height:900});for(const [selector,name] of [["#growth","08-desktop-scale-chart-map"],["#electoral","09-desktop-municipal-slide"],["#electoral .exec-municipal-map","10-desktop-municipal-map"],["#change .exec-family-pair","11-desktop-election-comparison"],["#change .exec-changed","12-desktop-changed-list"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1920,height:1080});for(const [selector,name] of [["#growth .exec-population-map:first-child","13-large-population-map"],["#electoral","14-large-municipal"],["#change .exec-family-pair","15-large-election-comparison"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`})});

test("capture final map fix acceptance set",async({page})=>{test.setTimeout(120_000);const root="docs/review/campaign-intelligence/final-map-fix";await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}`);for(const [selector,name] of [[".exec-map--population","01-mobile-population"],[".exec-map--variation","02-mobile-variation"],["#typologies>.exec-report-map","03-mobile-five-families"],["#structure-vote figure:nth-child(1)","04-mobile-structure"],["#structure-vote figure:nth-child(2)","05-mobile-electoral"],["#structure-vote figure:nth-child(3)","06-mobile-integrated"],["#representative-territories article:first-child","07-mobile-representative-group-1"],["#electoral .exec-municipal-summary>h3","08-mobile-municipal-summary"],["#electoral .exec-municipal-map","09-mobile-municipal-map"],[".exec-family-map--4","10-mobile-2019"],[".exec-family-map--1","11-mobile-2023"],["#growth .exec-population-map:first-child","12-mobile-municipal-population"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1440,height:900});for(const [selector,name] of [[".exec-map--population","13-desktop-population"],[".exec-map--variation","14-desktop-variation"],["#typologies>.exec-report-map","15-desktop-five-families"],["#structure-vote","16-desktop-structure-vote"],["#representative-territories","17-desktop-representatives"],["#electoral","18-desktop-municipal-scene"],["#electoral .exec-municipal-map","19-desktop-municipal-map"],["#change .exec-family-pair","20-desktop-comparison"],["#growth .exec-population-map:first-child","21-desktop-municipal-population"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1920,height:1080});for(const [selector,name] of [[".exec-map--population","22-large-population"],["#typologies>.exec-report-map","23-large-five-families"],["#electoral","24-large-municipal"],["#change .exec-family-pair","25-large-comparison"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`})});

test("population map section selection exposes mapped population and variation details",async({page})=>{
 await page.setViewportSize({width:1440,height:900});await page.goto(`/campaigns/mijas-2027${member}`);await page.getByRole("button",{name:/Explorar el territorio/}).click();
 const firstPanel=page.locator(".municipality-map-panel").first();await firstPanel.scrollIntoViewIfNeeded();await expect(page.locator(".municipality-real-map--population")).toBeVisible();
 const paths=page.locator(".municipality-map-svg path[role=button]");await expect(paths).toHaveCount(37);expect(await paths.evaluateAll(nodes=>nodes.every(node=>(node.getAttribute("aria-label")||"").includes(":")))).toBe(true);
 await paths.nth(1).click({force:true});const populationSelection=page.locator(".municipality-selection");await expect(populationSelection).toHaveAttribute("data-selected-section",/\d+/);await expect(populationSelection.locator("strong")).not.toHaveText("Dato no disponible");await expect(populationSelection.locator("span")).toContainText(/% del total · puesto \d+ de 37/);await expect(paths.filter({has:page.locator("title")})).toHaveCount(37);await expect(page.locator(".municipality-map-svg path.selected")).toHaveCount(1);
 const secondPanel=page.locator(".municipality-map-panel").nth(1);await secondPanel.scrollIntoViewIfNeeded();await expect(page.locator(".municipality-real-map--growth")).toBeVisible();await paths.nth(2).click({force:true});const variationSelection=page.locator(".municipality-selection");await expect(variationSelection.locator("strong")).toContainText("%");await expect(variationSelection.locator("span")).toContainText(/(Crecimiento|Descenso|Sin cambio) · [+-]?\d+[.]?\d* personas · 2023–2024/);await expect(page.locator(".municipality-map-svg path.selected")).toHaveCount(1);
});

test("Municipales 2023 is a flat complete non-interactive report slide",async({page})=>{for(const viewport of viewports){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#municipal-2023-summary`);const section=page.locator("#municipal-2023-summary");await expect(section.getByRole("heading",{name:"PSOE y PP quedaron separados por solo 2,03 puntos en el conjunto de Mijas."})).toBeVisible();await expect(section.getByRole("heading",{name:"PSOE-A y PP quedaron separados por solo 2,03 puntos en el conjunto de Mijas."})).toHaveCount(0);for(const text of ["33,98 %","PP","2,03 puntos","51,82 %","Las Cañadas","Riviera Norte"])await expect(section.getByText(text,{exact:true}).first()).toBeVisible();await expect(section.locator("button")).toHaveCount(0);await expect(section.locator(".exec-map--municipal-2023 path")).toHaveCount(37);const layout=await section.evaluate(node=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,width:node.getBoundingClientRect().width,mapWidth:node.querySelector("svg")!.getBoundingClientRect().width}));expect(layout.overflow).toBe(false);expect(layout.mapWidth).toBeGreaterThan(Math.min(320,layout.width*.8))}await expect(page.getByText("Una diferencia municipal de 2,0257 puntos.")).toHaveCount(0)});

test("capture flat Municipal 2023 section",async({page})=>{const root="docs/review/campaign-intelligence/municipal-2023-flat";for(const viewport of [{width:390,height:844,name:"mobile-390"},{width:1440,height:900,name:"desktop-1440"},{width:1920,height:1080,name:"desktop-1920"}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#municipal-2023-summary`);await page.locator("#municipal-2023-summary").screenshot({path:`${root}/${viewport.name}.png`})}});

test("electoral trajectory and Municipal 2023 use the revised client-facing hierarchy",async({page})=>{for(const viewport of [{width:390,height:844},{width:1440,height:900}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#electoral`);const scene=page.locator("#electoral"),section=page.locator("#municipal-2023-summary");await expect(scene.locator(":scope > header > p")).toHaveText("Trayectoria electoral");await expect(section.locator(":scope > p:first-child")).toHaveText("Municipales 2023");await expect(section.getByText("02 · Municipales 2023",{exact:true})).toHaveCount(0);await expect(section.getByText("Explorar el mapa electoral",{exact:false})).toHaveCount(0);await expect(section.locator(".exec-map--municipal-2023 path")).toHaveCount(37);expect(await section.evaluate(node=>node.lastElementChild?.classList.contains("exec-municipal-map"))).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)}});

test("descriptive structure leads with strategic KPIs and retains technical evidence",async({page})=>{test.setTimeout(180_000);for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#relationships`);if(!await page.locator(".territorial-relationships").count())await page.locator("#relationships .exec-explore>button").click();const section=page.locator(".relations-models"),cards=section.locator(".relations-model-card");await section.scrollIntoViewIfNeeded();await expect(cards).toHaveCount(3);for(const [index,percentage,status,technical,exact] of [[0,"≈ 62 %","Estructura territorial alta","R² ajustado: 0,6159 · error de validación: 3,9 pp","0.6159; error de validación 3.9029 pp"],[1,"≈ 54 %","Estructura territorial relevante","R² ajustado: 0,5442 · error de validación: 4,7 pp","0.5442; error de validación 4.6570 pp"],[2,"≈ 2 %","Estructura territorial débil","R² ajustado: 0,0156 · error de validación: 7,6 pp","0.0156; error de validación 7.6012 pp"]] as const){await expect(cards.nth(index).getByText(percentage,{exact:true})).toBeVisible();await expect(cards.nth(index).getByText(status,{exact:true})).toBeVisible();const evidence=cards.nth(index).getByText(technical,{exact:true});await expect(evidence).toBeVisible();await expect(evidence).toHaveAttribute("title",new RegExp(exact.replace(".","\\.")))}await expect(section.getByText("El voto tiene una geografía más estructurada que la participación.",{exact:true})).toBeVisible();await expect(section.getByText("Lectura estratégica",{exact:true})).toBeVisible();await expect(section.getByText(/diferencia media aproximada entre el valor observado/)).toBeVisible();const layout=await section.evaluate(node=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,width:node.getBoundingClientRect().width,cardWidths:[...node.querySelectorAll<HTMLElement>(".relations-model-card")].map(card=>card.getBoundingClientRect().width)}));expect(layout.overflow).toBe(false);expect(layout.cardWidths.every(width=>width>280&&width<=layout.width)).toBe(true)}});

test("participation result KPIs use exactly two Spanish decimals",async({page})=>{test.setTimeout(120_000);for(const viewport of [{width:390,height:844},{width:1440,height:900}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#relationships`);if(!await page.locator(".territorial-relationships").count())await page.locator("#relationships .exec-explore>button").click();const section=page.locator(".relations-participation"),values=section.locator(".relations-model-hero strong,.relations-weak-list strong");await section.scrollIntoViewIfNeeded();await expect(section.getByRole("heading",{name:"La participación no tiene una explicación territorial simple.",exact:true})).toBeVisible();await expect(values).toHaveText(["0,02","7,60 pp","0,07","0,22","0,11","-0,04","-0,09"]);for(const raw of ["0.0156","7.6012 pp","0.0680","0.2242","0.1068","-0.0417","-0.0857"])await expect(section.getByText(raw,{exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)}});

test("relationships journey ends at module 10 without obsolete terminal scenes",async({page})=>{test.setTimeout(180_000);for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#relationships`);if(!await page.locator(".territorial-relationships").count())await page.locator("#relationships .exec-explore>button").click();const story=page.locator(".territorial-relationships"),last=story.locator(".relations-residuals");await expect(story).toBeAttached({timeout:20_000});for(const removed of ["11 · Jerarquía de evidencia","La solidez se clasifica; nunca se supone.","12 · Red reducida","Dieciocho conexiones para leer relaciones, no causas.","13 · Lo que la evidencia no sostiene","Descartar explicaciones no sustentadas también mejora la inteligencia analítica.","14 · Síntesis consultiva basada en análisis territorial multivariable"])await expect(story.getByText(removed,{exact:true})).toHaveCount(0);await expect(story.locator(".relations-hierarchy,.relations-network,.relations-myths,.relations-closing")).toHaveCount(0);await expect(last.getByText("10 · Fuera del patrón general",{exact:true})).toBeVisible();expect(await story.evaluate(node=>node.lastElementChild?.classList.contains("relations-residuals"))).toBe(true);await last.scrollIntoViewIfNeeded();const layout=await story.evaluate(node=>{const final=node.lastElementChild!.getBoundingClientRect(),story=node.getBoundingClientRect();return{overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,endGap:story.bottom-final.bottom}});expect(layout.overflow).toBe(false);expect(Math.abs(layout.endGap)).toBeLessThan(2)}});

test("municipal map change is a deterministic 28-territory comparison",async({page})=>{for(const viewport of viewports){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#municipal-map-change`);const section=page.locator("#municipal-map-change"),maps=section.locator(".exec-family-map svg");await expect(maps).toHaveCount(2);await expect(section.locator(".exec-changed li")).toHaveCount(7);await expect(section.getByText("Para comparar ambas elecciones, soctrace agrupa las secciones en 28 territorios equivalentes y evita comparar directamente límites censales que cambiaron entre convocatorias.",{exact:true})).toBeVisible();await expect(section.getByText("7 de 28 territorios cambiaron de ganador.",{exact:true})).toBeVisible();await expect(section.getByText("El 25 % de los territorios comparables cambió de fuerza ganadora.",{exact:true})).toBeVisible();const geometry:string[][]=[];for(const map of await maps.all()){await expect(map.locator("path")).toHaveCount(28);await expect(map.locator("path.changed")).toHaveCount(7);const result=await map.evaluate((node:SVGSVGElement)=>{const r=node.getBoundingClientRect(),b=node.getBBox(),v=node.viewBox.baseVal;return{width:r.width,height:r.height,x:b.width/v.width,y:b.height/v.height,d:[...node.querySelectorAll("path")].map(path=>path.getAttribute("d")||"")}});expect(result.width).toBeGreaterThan(viewport.width>=1024?400:viewport.width*.8);expect(result.height).toBeGreaterThan(220);expect(Math.max(result.x,result.y)).toBeGreaterThan(.85);expect(Math.min(result.x,result.y)).toBeGreaterThan(.55);expect(result.d.every(d=>d.length>10)).toBe(true);geometry.push(result.d)}expect(geometry[0]).toEqual(geometry[1]);expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)}});

test("harmonized comparison labels the party winner totals",async({page})=>{test.setTimeout(120_000);for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#municipal-map-change`);const section=page.locator("#municipal-map-change"),legend=section.locator(".exec-election-shift-legend"),summaries=section.locator(".exec-election-shift");await expect(legend).toHaveText("Total de secciones en las que cada partido fue fuerza más votada");await expect(summaries).toContainText("PP 16 · PSOE 11 · Cs 1");await expect(summaries).toContainText("PP 10 · PSOE 18 · Cs 0");expect(await legend.evaluate(node=>node.nextElementSibling?.classList.contains("exec-election-shift"))).toBe(true);const layout=await section.evaluate(node=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,legendWidth:node.querySelector<HTMLElement>(".exec-election-shift-legend")!.getBoundingClientRect().width,sectionWidth:node.getBoundingClientRect().width}));expect(layout.overflow).toBe(false);expect(layout.legendWidth).toBeLessThanOrEqual(layout.sectionWidth)}});

test("the single interactive election sequence replaces the static electoral table",async({page})=>{test.setTimeout(180_000);for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#electoral`);const scene=page.locator("#electoral"),sequence=scene.locator("#election-chronology"),timeline=sequence.locator(".electoral-timeline"),tabs=timeline.getByRole("tab"),detail=timeline.locator(".electoral-timeline-detail");await expect(scene.getByRole("heading",{name:"Mijas tampoco vota igual.",exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Doce elecciones. Distintas fotografías.",exact:true})).toHaveCount(1);await expect(page.locator(".electoral-timeline")).toHaveCount(1);await expect(tabs).toHaveCount(12);await expect(page.locator(".exec-chronology,.electoral-elections")).toHaveCount(0);expect(await scene.locator(":scope > header").evaluate(node=>node.nextElementSibling?.id)).toBe("election-chronology");for(const [tab,winner,participation,margin] of [[/UE\s*2014/,"29,9 %","37,3 %","8,0 pp"],[/MUN\s*2023/,"34,0 %","51,8 %","2,0 pp"],[/AND\s*2026/,"39,4 %","58,6 %","20,3 pp"]] as const){await tabs.filter({hasText:tab}).click();await expect(detail).toContainText(winner);await expect(detail).toContainText(participation);await expect(detail).toContainText(margin);expect(await detail.innerText()).not.toMatch(/\d+,\d{2,}\s(?:%|pp)/)}expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)}});

test("all election timeline detail percentages use one decimal",async({page})=>{test.setTimeout(180_000);await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}#election-chronology`);const timeline=page.locator("#election-chronology .electoral-timeline"),tabs=timeline.getByRole("tab"),detail=timeline.locator(".electoral-timeline-detail");await expect(tabs).toHaveCount(12);for(let i=0;i<12;i++){await tabs.nth(i).click();expect(await detail.innerText()).not.toMatch(/\d+,\d{2,}\s(?:%|pp)/)}await tabs.filter({hasText:/AND\s*2026/}).click();await expect(detail).not.toContainText("58,5972 %");await expect(detail).not.toContainText("20,2723 pp")});

test("all election points show normalized verified winners and Municipal 2015 uses PP styling",async({page})=>{test.setTimeout(180_000);for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#election-chronology`);const timeline=page.locator("#election-chronology .electoral-timeline"),tabs=timeline.getByRole("tab"),labels=timeline.locator(".electoral-timeline-winner"),detailWinner=timeline.locator(".electoral-timeline-detail>div").first().locator("strong");await expect(tabs).toHaveCount(12);await expect(labels).toHaveCount(12);expect(await labels.allTextContents()).toEqual(["PSOE","PP","PP","PSOE","PSOE","PP","PSOE","PP","PSOE","PP","PP","PP"]);await expect(labels.filter({hasText:"PP"}).first()).toHaveClass(/electoral-party--pp/);await expect(labels.filter({hasText:"PSOE"}).first()).toHaveClass(/electoral-party--psoe/);const municipal2015=tabs.filter({hasText:/MUN\s*2015/});await expect(municipal2015.locator(".electoral-timeline-winner")).toHaveText("PP");await expect(municipal2015.locator(".electoral-timeline-winner")).toHaveClass(/electoral-party--pp/);await municipal2015.click();await expect(detailWinner).toHaveText("PP");await expect(detailWinner).not.toHaveText("P.P.");await expect(detailWinner).toHaveClass(/electoral-party--pp/);const layout=await timeline.evaluate(node=>{const labels=[...node.querySelectorAll<HTMLElement>(".electoral-timeline-winner")].map(label=>{const box=label.getBoundingClientRect(),button=label.parentElement!.getBoundingClientRect();return{left:box.left,right:box.right,center:(box.left+box.right)/2,buttonCenter:(button.left+button.right)/2}});return{overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,aligned:labels.every(label=>Math.abs(label.center-label.buttonCenter)<25),overlap:labels.some((label,index)=>index>0&&label.left<labels[index-1].right)}});expect(layout.overflow).toBe(false);expect(layout.aligned).toBe(true);expect(layout.overlap).toBe(false)}});

test("obsolete participation branch is absent while the retained election timeline remains intact",async({page})=>{test.setTimeout(180_000);for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}`);const story=page.locator(".psoe-victory-story"),timeline=page.locator("#election-chronology .electoral-timeline");await expect(story.getByText("08 · Qué sabemos — y qué no",{exact:true})).toHaveCount(1);await expect(page.locator("#participation,#electoral-landscape,.electoral-diagnosis")).toHaveCount(0);for(const obsolete of ["Participación y movilización","Explorar participación","12 elecciones verificadas","Diagnóstico electoral","Cambiar de elección cambia el mapa.","Geografía comparable"])await expect(page.getByText(obsolete,{exact:true})).toHaveCount(0);await expect(page.locator('a[href="#participation"]')).toHaveCount(0);await expect(timeline.getByRole("tab")).toHaveCount(12);await expect(timeline.locator(".electoral-timeline-detail")).toBeVisible();await expect(timeline.getByText("Última elección cargada",{exact:true})).toHaveCount(1);expect(await story.evaluate(node=>node.nextElementSibling?.id)).toBe("relationships");expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)}});

test("PSOE 2023 victory story renders eight verified mobile-first modules",async({page})=>{
 test.setTimeout(180_000);
 const requested=[{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1440,height:900},{width:1920,height:1080}];
 for(const viewport of requested){
  await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#electoral`);await page.reload();
  const story=page.locator(".psoe-victory-story"),modules=story.locator("[data-victory-module]");await expect(story).toBeAttached({timeout:15_000});await expect(modules).toHaveCount(8);
  await expect(page.getByRole("heading",{name:"Claves territoriales de la victoria del PSOE.",exact:true})).toHaveCount(1);await expect(story.getByText("08 · Qué sabemos — y qué no",{exact:true})).toHaveCount(1);const order=await page.evaluate(()=>{const municipal=document.querySelector("#municipal-2023-summary")!,story=document.querySelector(".psoe-victory-story")!,module03=story.querySelector<HTMLElement>('[data-victory-module="03"]')!,last=story.querySelector('[data-victory-module="08"]')!,change=document.querySelector("#change")!;return{municipalBeforeStory:Boolean(municipal.compareDocumentPosition(story)&Node.DOCUMENT_POSITION_FOLLOWING),changeIsModule03:change===module03,module03ContainsComparison:Boolean(module03.querySelector("#municipal-map-change")),changeBeforeLast:Boolean(change.compareDocumentPosition(last)&Node.DOCUMENT_POSITION_FOLLOWING),storyNextIsRelationships:story.nextElementSibling?.id==="relationships"}});expect(order).toEqual({municipalBeforeStory:true,changeIsModule03:true,module03ContainsComparison:true,changeBeforeLast:true,storyNextIsRelationships:true});

  expect(await modules.evaluateAll(nodes=>nodes.map(node=>node.getAttribute("data-victory-module")))).toEqual(["01","02","03","04","05","06","07","08"]);
  await expect(story.locator(".victory-geo-map path")).toHaveCount(37);await expect(story.locator('[data-victory-module="03"] .exec-family-pair svg')).toHaveCount(2);for(const map of await story.locator('[data-victory-module="03"] .exec-family-pair svg').all())await expect(map.locator("path")).toHaveCount(28);await expect(story.locator('[data-victory-module="03"] .exec-changed li')).toHaveCount(7);await expect(page.locator("#municipal-map-change,.exec-map-change")).toHaveCount(1);await expect(page.locator("#municipal-map-change")).toHaveCount(1);expect(await story.locator('[data-victory-module="03"]').evaluate(node=>node.nextElementSibling?.getAttribute("data-victory-module"))).toBe("04");
  for(const territory of ["Las Cañadas","Avda Los Lirios / Ferrán Caballero","Osunillas","Camino Campanales","Barrio de las Flores Oeste","Parque Andalucía","Doña Ermita / Pol. San Rafael"])await expect(story.locator('[data-victory-module="03"] .exec-changed').getByText(territory,{exact:true})).toBeVisible();
  for(const text of ["El PSOE ganó Mijas por solo 512 votos.","24 de 37","13 de 37","Ciudadanos cayó 14,8 pp.","Relación prácticamente nula","Relaciones territoriales; no causalidad."])await expect(story.getByText(text,{exact:true}).first()).toBeVisible();
  const context=story.locator('[data-victory-module="06"]');for(const removed of ["Primer voto","No identificable con los datos agregados disponibles","No podemos identificar la contribución de nuevos votantes o jóvenes que votaron por primera vez."])await expect(context.getByText(removed,{exact:true})).toHaveCount(0);await expect(context.locator("aside")).toHaveCount(0);await expect(context.locator(".victory-context-grid article")).toHaveCount(5);expect(await context.evaluate(node=>node.lastElementChild?.tagName)).toBe("P");
  for(const old of ["02 · Municipales 2023","03 · Diferencias territoriales","04 · Cambio del mapa municipal","05 · Distribución agregada del voto","06 · Participación"])await expect(page.locator(".electoral-diagnosis").getByText(old,{exact:true})).toHaveCount(0);
  const layout=await story.evaluate(node=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,slides:[...node.querySelectorAll<HTMLElement>(".victory-slide")].map(x=>({left:x.getBoundingClientRect().left,right:x.getBoundingClientRect().right,width:x.getBoundingClientRect().width}))}));expect(layout.overflow,`${viewport.width}x${viewport.height}`).toBe(false);expect(layout.slides.every(x=>x.left>=0&&x.right<=viewport.width+.5&&x.width>300)).toBe(true);
 }
});

test("capture PSOE 2023 victory review set",async({page})=>{test.setTimeout(180_000);const root="docs/review/campaign-intelligence/psoe-2023-victory/screenshots";for(const viewport of [{width:390,height:844,name:"mobile-390"},{width:1440,height:900,name:"desktop-1440"}]){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#electoral`);await page.reload();await page.locator(".exec-header,.campaign-progress").evaluateAll(nodes=>nodes.forEach(node=>(node as HTMLElement).style.visibility="hidden"));const story=page.locator(".psoe-victory-story");await story.locator(".victory-intro").screenshot({path:`${root}/${viewport.name}-intro.png`});for(let i=1;i<=8;i++)await story.locator(`[data-victory-module="${String(i).padStart(2,"0")}"]`).screenshot({path:`${root}/${viewport.name}-${String(i).padStart(2,"0")}.png`})}});

test("capture municipal map change review set",async({page})=>{test.setTimeout(120_000);const root="docs/review/campaign-intelligence/municipal-map-change-fix";await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}#municipal-map-change`);await page.locator(".exec-header,.campaign-progress").evaluateAll(nodes=>nodes.forEach(node=>(node as HTMLElement).style.visibility="hidden"));for(const [selector,name] of [["#municipal-map-change","01-mobile-complete"],[".exec-family-map--4","02-mobile-2019"],[".exec-family-map--1","03-mobile-2023"],["#municipal-map-change .exec-changed","04-mobile-changed-territories"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1440,height:900});for(const [selector,name] of [["#municipal-map-change","05-desktop-complete"],["#municipal-map-change .exec-family-pair","06-desktop-map-comparison"],["#municipal-map-change .exec-changed","07-desktop-changed-territories"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await page.setViewportSize({width:1920,height:1080});await page.locator("#municipal-map-change").screenshot({path:`${root}/08-large-complete.png`})});

test("comparable territories renders 32 real harmonised geometries",async({page})=>{test.setTimeout(120_000);for(const viewport of viewports){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#growth`);await page.reload();await page.getByRole("button",{name:"Explorar la evolución territorial",exact:true}).click();const section=page.locator("#comparable-territories"),map=section.locator(".evolution-comparable-map svg");await expect(section.getByRole("heading",{name:"32 territorios comparables a través del tiempo"})).toBeVisible();await expect(map.locator("path")).toHaveCount(32);const result=await map.evaluate((node:SVGSVGElement)=>{const r=node.getBoundingClientRect(),b=node.getBBox(),v=node.viewBox.baseVal,paths=[...node.querySelectorAll("path")];return{width:r.width,height:r.height,x:b.width/v.width,y:b.height/v.height,paths:paths.map(path=>({d:path.getAttribute("d")||"",fill:getComputedStyle(path).fill,stroke:getComputedStyle(path).stroke,opacity:getComputedStyle(path).opacity}))}});expect(result.width).toBeGreaterThan(viewport.width>=1024?500:viewport.width*.8);expect(result.height).toBeGreaterThanOrEqual(viewport.width>=1024?300:220);expect(Math.max(result.x,result.y)).toBeGreaterThan(.85);expect(Math.min(result.x,result.y)).toBeGreaterThan(.55);expect(result.paths.every(path=>path.d.length>10&&path.fill!=="none"&&path.stroke!=="none"&&Number(path.opacity)>0)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);for(const text of ["2021","2022","2023","2024","2025","Sección 026","Sección 028","Sección 018","Sección 024","La asignación espacial mínima entre las secciones anuales y su territorio comparable es del 96,4 %."])await expect(section.getByText(text,{exact:true}).first()).toBeAttached()}});

test("capture comparable territories review set",async({page})=>{test.setTimeout(240_000);const root="docs/review/campaign-intelligence/comparable-territories-fix",open=async(width:number,height:number)=>{await page.setViewportSize({width,height});await page.goto(`/campaigns/mijas-2027${member}#growth`);await page.reload();await page.getByRole("button",{name:"Explorar la evolución territorial",exact:true}).click();await page.locator("#comparable-territories").scrollIntoViewIfNeeded();await page.locator(".exec-header,.campaign-progress").evaluateAll(nodes=>nodes.forEach(node=>(node as HTMLElement).style.visibility="hidden"))};await open(390,844);for(const [selector,name] of [["#comparable-territories","01-mobile-complete"],["#comparable-territories .evolution-comparable-map","02-mobile-map"],["#comparable-territories .evolution-harmonisation","03-mobile-harmonisation"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await open(1440,900);for(const [selector,name] of [["#comparable-territories","04-desktop-complete"],["#comparable-territories .evolution-comparable-map","05-desktop-map"],["#comparable-territories .evolution-harmonisation","06-desktop-split-method"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await open(1920,1080);await page.locator("#comparable-territories").screenshot({path:`${root}/07-large-complete.png`})});

test("five territorial families renders all 37 verified sections initially",async({page})=>{test.setTimeout(180_000);for(const viewport of viewports){await page.setViewportSize(viewport);await page.goto(`/campaigns/mijas-2027${member}#typologies`);await page.reload();await page.locator("#typologies .exec-explore>button").click();const section=page.locator("#five-families-map"),map=section.locator(".typology-static-map svg"),paths=map.locator("path");await expect(section.getByRole("heading",{name:/37 secciones\.\s*Cinco lecturas compartidas\./})).toBeVisible();await expect(paths).toHaveCount(37);await expect(section.locator(".typology-static-legend>div")).toHaveCount(5);await expect(section.locator(".typology-family-summaries>article")).toHaveCount(5);await expect(section.locator("button")).toHaveCount(0);const result=await map.evaluate((node:SVGSVGElement)=>{const r=node.getBoundingClientRect(),b=node.getBBox(),v=node.viewBox.baseVal,paths=[...node.querySelectorAll<SVGPathElement>("path")],groups=new Set(paths.map(path=>path.dataset.group)),ids=paths.map(path=>path.dataset.sectionId);return{width:r.width,height:r.height,x:b.width/v.width,y:b.height/v.height,groups:[...groups],ids,paths:paths.map(path=>({d:path.getAttribute("d")||"",fill:getComputedStyle(path).fill,opacity:Number(getComputedStyle(path).opacity)}))}});expect(result.width).toBeGreaterThan(viewport.width>=1024?500:viewport.width*.8);expect(result.height).toBeGreaterThanOrEqual(viewport.width>=1024?300:240);expect(Math.max(result.x,result.y)).toBeGreaterThan(.7);expect(Math.min(result.x,result.y)).toBeGreaterThan(.5);expect(result.ids.filter(Boolean)).toHaveLength(37);expect(new Set(result.ids).size).toBe(37);expect(result.groups.sort()).toEqual(["Group 1","Group 2","Group 3","Group 4","Group 5"]);expect(result.paths.every(path=>path.d.length>10&&path.fill!=="none"&&path.opacity===1)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)}});

test("capture five families map review set",async({page})=>{test.setTimeout(240_000);const root="docs/review/campaign-intelligence/five-families-map-fix",open=async(width:number,height:number)=>{await page.setViewportSize({width,height});await page.goto(`/campaigns/mijas-2027${member}#typologies`);await page.reload();await page.locator("#typologies .exec-explore>button").click();await page.locator("#five-families-map").scrollIntoViewIfNeeded();await page.locator(".exec-header,.campaign-progress").evaluateAll(nodes=>nodes.forEach(node=>(node as HTMLElement).style.visibility="hidden"))};await open(390,844);for(const [selector,name] of [["#five-families-map","01-mobile-complete"],["#five-families-map .typology-static-map","02-mobile-map"],["#five-families-map","03-mobile-map-legend"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await open(1440,900);for(const [selector,name] of [["#five-families-map","04-desktop-complete"],["#five-families-map .typology-static-map","05-desktop-map"],["#five-families-map .typology-family-summaries","06-desktop-family-summaries"]] as [string,string][])await page.locator(selector).screenshot({path:`${root}/${name}.png`});await open(1920,1080);await page.locator("#five-families-map").screenshot({path:`${root}/07-large-complete.png`})});

test("representative territory cards render five deterministic locators without profile links",async({page})=>{test.setTimeout(180_000);const expected=[{id:"2907001013",name:"Sección 13 · Osunillas"},{id:"2907001017",name:"Sección 17 · Campo Mijas"},{id:"2907001022",name:"Sección 22 · El Chaparral"},{id:"2907001016",name:"Sección 16 · El Juncal"},{id:"2907001009",name:"Sección 09 · Barrio de las flores Este"}];await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}#typologies`);await page.reload();await page.locator("#typologies .exec-explore>button").click();const section=page.locator(".typology-representatives"),cards=section.locator(":scope>div>article");await expect(cards).toHaveCount(5);await expect(section.getByText("Ver perfil",{exact:false})).toHaveCount(0);for(let i=0;i<expected.length;i++){const card=cards.nth(i),map=card.locator("svg.typology-representative-locator"),paths=map.locator("path");await expect(card).toHaveAttribute("data-representative-section",expected[i].id);await expect(card.getByRole("heading",{name:expected[i].name})).toBeVisible();await expect(paths).toHaveCount(37);await expect(map.locator('path[data-representative="true"]')).toHaveCount(1);await expect(map.locator('path[data-representative="true"]')).toHaveAttribute("data-section-id",expected[i].id);expect(await paths.evaluateAll(nodes=>nodes.every(path=>(path.getAttribute("d")||"").length>10))).toBe(true)}for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await section.scrollIntoViewIfNeeded();const layout=await section.evaluate(node=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,maps:[...node.querySelectorAll<SVGSVGElement>(".typology-representative-locator")].map(map=>{const rect=map.getBoundingClientRect(),box=map.getBBox(),viewBox=map.viewBox.baseVal;return{width:rect.width,height:rect.height,x:box.width/viewBox.width,y:box.height/viewBox.height,active:map.querySelectorAll('path[data-representative="true"]').length}})}));expect(layout.overflow).toBe(false);expect(layout.maps.every(map=>map.width>250&&map.height>170&&Math.max(map.x,map.y)>.7&&Math.min(map.x,map.y)>.5&&map.active===1)).toBe(true)}});

test("transitional territory cards end with assignment detail and no profile links",async({page})=>{test.setTimeout(180_000);await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}#typologies`);await page.reload();await page.locator("#typologies .exec-explore>button").click();const section=page.locator(".typology-transitional"),cards=section.locator(":scope>div>article");await expect(cards).toHaveCount(6);await expect(section.getByRole("link",{name:/Abrir perfil/})).toHaveCount(0);await expect(cards.locator("details")).toHaveCount(6);await expect(cards.getByText("Detalle de la asignación",{exact:true})).toHaveCount(6);expect(await cards.evaluateAll(nodes=>nodes.every(card=>card.lastElementChild?.tagName==="DETAILS"&&card.querySelector("h4")&&card.querySelector(":scope > p")&&card.querySelector(":scope > span")))).toBe(true);for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await section.scrollIntoViewIfNeeded();const layout=await section.evaluate(node=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,cards:[...node.querySelectorAll<HTMLElement>(":scope>div>article")].map(card=>{const box=card.getBoundingClientRect(),last=card.lastElementChild!.getBoundingClientRect();return{width:box.width,bottomSpace:box.bottom-last.bottom}})}));expect(layout.overflow).toBe(false);expect(layout.cards.every(card=>card.width>280&&card.bottomSpace<=33)).toBe(true)}});

test("singular territory rows end with analytical content and no evidence links",async({page})=>{test.setTimeout(180_000);const expected=[{score:"3,11",name:"Sección 06 · María Barranco Sur",group:"Entornos urbanos compactos con menor renta y formación"},{score:"1,83",name:"Sección 14 · María Barranco Norte",group:"Territorios densos, jóvenes y participativos"},{score:"1,71",name:"Sección 07 · Cala de Mijas",group:"Mayor ventaja PP y menor participación"},{score:"1,37",name:"Sección 34 · Riviera Norte",group:"Mayor ventaja PP y menor participación"},{score:"1,1",name:"Sección 02 · Mijas Este",group:"Territorios maduros, dispersos y participativos"}];await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}#typologies`);await page.reload();await page.locator("#typologies .exec-explore>button").click();const section=page.locator(".typology-outliers"),rows=section.locator(":scope>div>article");await expect(section.getByRole("heading",{name:"Algunos territorios no encajan del todo en su familia."})).toBeVisible();await expect(section).toContainText("Cuanto mayor es el indicador de singularidad");await expect(rows).toHaveCount(5);await expect(section.getByRole("link",{name:"Ver evidencia territorial"})).toHaveCount(0);for(let i=0;i<expected.length;i++){const row=rows.nth(i);await expect(row.locator(":scope>strong")).toHaveText(expected[i].score);await expect(row.locator(".typology-group-badge")).toContainText(expected[i].group);await expect(row.getByRole("heading",{name:expected[i].name})).toBeVisible();await expect(row.locator(":scope>div>p")).toContainText("Variables principales:");expect(await row.locator(":scope>div").evaluate(node=>node.lastElementChild?.tagName)).toBe("P")}for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await section.scrollIntoViewIfNeeded();const layout=await section.evaluate(node=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,rows:[...node.querySelectorAll<HTMLElement>(":scope>div>article")].map(row=>({left:row.getBoundingClientRect().left,right:row.getBoundingClientRect().right,width:row.getBoundingClientRect().width}))}));expect(layout.overflow).toBe(false);expect(layout.rows.every(row=>row.left>=0&&row.right<=viewport.width+.5&&row.width>280)).toBe(true)}});

test("geographic similarity explains the distinction and formats adjacency consistently",async({page})=>{test.setTimeout(180_000);await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}#typologies`);await page.reload();await page.locator("#typologies .exec-explore>button").click();const section=page.locator(".typology-geography");await expect(section).toContainText("Dos territorios pueden parecerse aunque no sean vecinos");await expect(section).toContainText("¿Qué aporta?");await expect(section.locator(":scope>div>strong")).toHaveText("52,3 %");await expect(section.locator(":scope>div>p")).toHaveText("de las relaciones de vecindad conectan secciones de la misma familia analítica.");for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await section.scrollIntoViewIfNeeded();const layout=await section.evaluate(node=>{const box=node.getBoundingClientRect();return{overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,left:box.left,right:box.right}});expect(layout.overflow).toBe(false);expect(layout.left).toBeGreaterThanOrEqual(0);expect(layout.right).toBeLessThanOrEqual(viewport.width+.5)}});

test("standalone reliability scene is removed without leaving a journey gap",async({page})=>{test.setTimeout(180_000);await page.setViewportSize({width:390,height:844});await page.goto(`/campaigns/mijas-2027${member}#typologies`);await page.reload();await page.locator("#typologies .exec-explore>button").click();const story=page.locator(".territorial-typologies"),geography=story.locator(".typology-geography"),choice=story.locator(".typology-choice"),closing=story.locator(".typology-closing");await expect(story.getByText("10 · Fiabilidad",{exact:true})).toHaveCount(0);await expect(story.getByText("Estabilidad analítica moderada.",{exact:true})).toHaveCount(0);await expect(story.getByText("repetición del modelo",{exact:true})).toHaveCount(0);await expect(story.getByText("submuestras del 80%",{exact:true})).toHaveCount(0);await expect(choice.getByText("10 · Por qué cinco grupos",{exact:true})).toBeVisible();await expect(closing.getByText("11 · Síntesis consultiva basada en análisis multivariable",{exact:true})).toBeVisible();expect(await geography.evaluate(node=>node.nextElementSibling?.classList.contains("typology-choice"))).toBe(true);for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(viewport);await choice.scrollIntoViewIfNeeded();const layout=await story.evaluate(node=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,reliabilityScenes:node.querySelectorAll(".typology-stability").length}));expect(layout.overflow).toBe(false);expect(layout.reliabilityScenes).toBe(0)}});

test("typology synthesis ends without a relationships continuation CTA",async({page})=>{test.setTimeout(120_000);await page.goto(`/campaigns/mijas-2027${member}#typologies`);await page.reload();await page.locator("#typologies .exec-explore>button").click();const closing=page.locator(".typology-closing");await expect(closing.getByText("11 · Síntesis consultiva basada en análisis multivariable",{exact:true})).toBeVisible();await expect(closing.getByRole("heading",{name:"La estructura territorial y el comportamiento electoral deben leerse juntos, pero nunca confundirse.",exact:true})).toBeVisible();await expect(closing.getByText("Continuar a relaciones territoriales",{exact:true})).toHaveCount(0);await expect(closing.locator('a[href="#territorial-relationships"]')).toHaveCount(0);expect(await closing.evaluate(node=>node.lastElementChild?.tagName)).toBe("P");for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900}]){await page.setViewportSize(viewport);await closing.scrollIntoViewIfNeeded();const layout=await closing.evaluate(node=>{const style=getComputedStyle(node);return{overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,minHeight:style.minHeight,bottomPadding:parseFloat(style.paddingBottom)}});expect(layout.overflow).toBe(false);expect(layout.minHeight).toBe("0px");expect(layout.bottomPadding).toBeLessThanOrEqual(128)}});
